### ISSUE TITLE
crash on using mobile sdk android

### ISSUE THREAD

**Issue by ghchinoy** [dji-sdk/Mobile-SDK-Android#1]
Crashing when running latest samples.

Pulled from git, added to android studio (1.4 rc3), added m y DJI dev app key, and gradle built ok; but upon startup, crash:

```
09-28 12:30:01.575 16624-16624/? I/art: Late-enabling -Xcheck:jni
09-28 12:30:01.787 16624-16624/com.dji.sdkdemo W/ResourcesManager: Asset path '/system/framework/com.android.future.usb.accessory.jar' does not exist or contains no resources.
09-28 12:30:02.203 16624-16640/com.dji.sdkdemo I/art: Background sticky concurrent mark sweep GC freed 2118(114KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 11MB/11MB, paused 11.540ms total 83.029ms
09-28 12:30:02.246 16624-16640/com.dji.sdkdemo W/art: Suspending all threads took: 9.380ms
09-28 12:30:02.251 16624-16640/com.dji.sdkdemo I/art: Background partial concurrent mark sweep GC freed 506(38KB) AllocSpace objects, 1(36KB) LOS objects, 24% free, 11MB/15MB, paused 13.284ms total 41.159ms
09-28 12:30:02.486 16624-16698/com.dji.sdkdemo D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
09-28 12:30:02.498 16624-16624/com.dji.sdkdemo D/Atlas: Validating map...
09-28 12:30:02.502 16624-16696/com.dji.sdkdemo W/System.err: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/com.android.future.usb.accessory.jar", zip file "/data/app/com.dji.sdkdemo-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libGroudStation.so"
09-28 12:30:02.502 16624-16696/com.dji.sdkdemo W/System.err:     at java.lang.Runtime.loadLibrary(Runtime.java:366)
09-28 12:30:02.502 16624-16696/com.dji.sdkdemo W/System.err:     at java.lang.System.loadLibrary(System.java:988)
09-28 12:30:02.502 16624-16696/com.dji.sdkdemo W/System.err:     at dji.midware.natives.GroudStation.<clinit>(Unknown Source)
09-28 12:30:02.502 16624-16696/com.dji.sdkdemo W/System.err:     at dji.midware.data.params.P3.ParamInfoBean.getParamInfo(Unknown Source)
09-28 12:30:02.502 16624-16696/com.dji.sdkdemo W/System.err:     at dji.midware.data.manager.P3.c.a(Unknown Source)
09-28 12:30:02.502 16624-16696/com.dji.sdkdemo W/System.err:     at dji.midware.data.manager.P3.c.a(Unknown Source)
09-28 12:30:02.502 16624-16696/com.dji.sdkdemo W/System.err:     at dji.midware.data.manager.P3.d.run(Unknown Source)
09-28 12:30:02.502 16624-16696/com.dji.sdkdemo W/System.err:     at java.lang.Thread.run(Thread.java:818)
09-28 12:30:02.503 16624-16696/com.dji.sdkdemo D/GroudStation: Couldn't load lib
09-28 12:30:02.503 16624-16696/com.dji.sdkdemo E/art: No implementation found for long dji.midware.natives.GroudStation.native_hashFromString(byte[]) (tried Java_dji_midware_natives_GroudStation_native_1hashFromString and Java_dji_midware_natives_GroudStation_native_1hashFromString___3B)
09-28 12:30:02.610 16624-16696/com.dji.sdkdemo E/AndroidRuntime: FATAL EXCEPTION: Thread-277554
09-28 12:30:02.610 16624-16696/com.dji.sdkdemo E/AndroidRuntime: Process: com.dji.sdkdemo, PID: 16624
09-28 12:30:02.610 16624-16696/com.dji.sdkdemo E/AndroidRuntime: java.lang.UnsatisfiedLinkError: No implementation found for long dji.midware.natives.GroudStation.native_hashFromString(byte[]) (tried Java_dji_midware_natives_GroudStation_native_1hashFromString and Java_dji_midware_natives_GroudStation_native_1hashFromString___3B)
09-28 12:30:02.610 16624-16696/com.dji.sdkdemo E/AndroidRuntime:     at dji.midware.natives.GroudStation.native_hashFromString(Native Method)
09-28 12:30:02.610 16624-16696/com.dji.sdkdemo E/AndroidRuntime:     at dji.midware.data.params.P3.ParamInfoBean.getParamInfo(Unknown Source)
09-28 12:30:02.610 16624-16696/com.dji.sdkdemo E/AndroidRuntime:     at dji.midware.data.manager.P3.c.a(Unknown Source)
09-28 12:30:02.610 16624-16696/com.dji.sdkdemo E/AndroidRuntime:     at dji.midware.data.manager.P3.c.a(Unknown Source)
09-28 12:30:02.610 16624-16696/com.dji.sdkdemo E/AndroidRuntime:     at dji.midware.data.manager.P3.d.run(Unknown Source)
09-28 12:30:02.610 16624-16696/com.dji.sdkdemo E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:818)
09-28 12:30:02.622 16624-16698/com.dji.sdkdemo I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build:  ()
09-28 12:30:02.622 16624-16698/com.dji.sdkdemo I/Adreno-EGL: OpenGL ES Shader Compiler Version: E031.25.03.04
09-28 12:30:02.622 16624-16698/com.dji.sdkdemo I/Adreno-EGL: Build Date: 04/06/15 Mon
09-28 12:30:02.622 16624-16698/com.dji.sdkdemo I/Adreno-EGL: Local Branch: 
09-28 12:30:02.622 16624-16698/com.dji.sdkdemo I/Adreno-EGL: Remote Branch: 
09-28 12:30:02.622 16624-16698/com.dji.sdkdemo I/Adreno-EGL: Local Patches: 
09-28 12:30:02.622 16624-16698/com.dji.sdkdemo I/Adreno-EGL: Reconstruct Branch: 
09-28 12:30:02.624 16624-16698/com.dji.sdkdemo I/OpenGLRenderer: Initialized EGL, version 1.4
09-28 12:30:02.643 16624-16698/com.dji.sdkdemo D/OpenGLRenderer: Enabling debug mode 0
09-28 12:30:03.489 16624-16624/com.dji.sdkdemo I/Process: Sending signal. PID: 16624 SIG: 9
```

**Comment by oliverou** [comment]
Hi! Can you provide the following info for us to help fix the problem:

1. Android system version on your testing Android device, like android 5.1.1, android 6.0, etc
2. Android device's type, like Nexus5, Samsung, etc

Thanks!

**Comment by JonasVautherin** [comment]
It says it cannot find "libGroudStation.so". Can you check if you have this file somewhere?

**Comment by LukasSkywalker** [comment]
I might have figured out why. They are indeed wrongly linked, but this can be fixed by editing `build.gradle` inside the `DJI-SDK-LIB` folder and adding the following snippet to the `sourceSets.main` part:

    jniLibs.srcDir 'libs'

so it looks like this:

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            resources.srcDirs = ['src']
            aidl.srcDirs = ['src']
            renderscript.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
            jniLibs.srcDir 'libs'
        }
    ...

Hope that helps someone.

**Comment by FreemanX** [comment]
Or you can create a jniLibs directory in your own project and copy armeabi and armeabi-v7a from DJI-SDK-LIB to jniLibs.
