### ISSUE TITLE
LINK_LTE issue on 4.15 with M300

### ISSUE THREAD

**Issue by matsjoe** [dji-sdk/Mobile-SDK-Android#1002]
Hi.

Running SDK version 4.15 on the M300 we are getting the following error.

2021-08-11 15:00:21.533 11145-11876/mypackageE/AndroidRuntime: FATAL EXCEPTION: RxComputationThreadPool-5
    Process: mypackagePID: 11145
    java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
        at dji.thirdparty.rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: dji.thirdparty.rx.exceptions.OnErrorNotImplementedException: java.lang.NoSuchFieldException: LINK_LTE
        at dji.thirdparty.rx.Observable$27.onError(Observable.java:8566)
        at dji.thirdparty.rx.observers.SafeSubscriber._onError(SafeSubscriber.java:157)
        at dji.thirdparty.rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
        at dji.thirdparty.rx.exceptions.Exceptions.throwOrReport(Exceptions.java:201)
        at dji.thirdparty.rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:144)
        at dji.thirdparty.rx.internal.util.ScalarSynchronousObservable$ScalarAsyncProducer.call(ScalarSynchronousObservable.java:192)
        at dji.thirdparty.rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
     Caused by: java.lang.AssertionError: java.lang.NoSuchFieldException: LINK_LTE
        at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:792)
        at com.google.gson.internal.bind.TypeAdapters$30.create(TypeAdapters.java:818)
        at com.google.gson.Gson.getAdapter(Gson.java:458)
        at com.google.gson.Gson.toJson(Gson.java:696)
        at com.google.gson.Gson.toJson(Gson.java:683)
        at com.google.gson.Gson.toJson(Gson.java:638)
        at com.google.gson.Gson.toJson(Gson.java:618)
        at com.dji.frame.util.V_JsonUtil.toJson()
        at dji.internal.analytics.listener.DJIAnalyticsCacheInteractionListener.getValueJson()
        at dji.internal.analytics.listener.DJIAnalyticsCacheInteractionListener.metaDataWithKeyPath()
        at dji.internal.analytics.listener.DJIAnalyticsCacheInteractionListener.onEvent()
        at dji.sdksharedlib.DJISDKCache.fdd()
        at dji.sdksharedlib.DJISDKCache.access$lambda$0()
        at dji.sdksharedlib.DJISDKCache$$Lambda$1.call()
        at dji.thirdparty.rx.Observable$27.onNext(Observable.java:8571)
        at dji.thirdparty.rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
        at dji.thirdparty.rx.internal.util.ScalarSynchronousObservable$ScalarAsyncProducer.call(ScalarSynchronousObservable.java:192) 
        at dji.thirdparty.rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
     Caused by: java.lang.NoSuchFieldException: LINK_LTE
        at java.lang.Class.getField(Class.java:1549)
        at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:781)
        at com.google.gson.internal.bind.TypeAdapters$30.create(TypeAdapters.java:818) 
        at com.google.gson.Gson.getAdapter(Gson.java:458) 
        at com.google.gson.Gson.toJson(Gson.java:696) 
        at com.google.gson.Gson.toJson(Gson.java:683) 
        at com.google.gson.Gson.toJson(Gson.java:638) 
        at com.google.gson.Gson.toJson(Gson.java:618) 
        at com.dji.frame.util.V_JsonUtil.toJson() 
        at dji.internal.analytics.listener.DJIAnalyticsCacheInteractionListener.getValueJson() 
        at dji.internal.analytics.listener.DJIAnalyticsCacheInteractionListener.metaDataWithKeyPath() 
        at dji.internal.analytics.listener.DJIAnalyticsCacheInteractionListener.onEvent() 
        at dji.sdksharedlib.DJISDKCache.fdd() 
        at dji.sdksharedlib.DJISDKCache.access$lambda$0() 
        at dji.sdksharedlib.DJISDKCache$$Lambda$1.call() 
        at dji.thirdparty.rx.Observable$27.onNext(Observable.java:8571) 
        at dji.thirdparty.rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139) 
        at dji.thirdparty.rx.internal.util.ScalarSynchronousObservable$ScalarAsyncProducer.call(ScalarSynchronousObservable.java:192) 
        at dji.thirdparty.rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 

I saw another ticket with the same issue stating it was fixed in 4.14.1. But we are running 4.15 and the error still occurs. 

Any solutions?

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/51616'>Zendesk ticket #51616</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>
