### ISSUE TITLE
Crash due to UserAccountInfo.isValid

### ISSUE THREAD

**Issue by jeryini** [dji-sdk/Mobile-SDK-Android#1050]
Hello!

In my production app I'm currently seeing the following crash that happens sporadically for some users:

```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'boolean dji.internal.useraccount.UserAccountInfo.isValid()' on a null object reference
dji.sdk.realname.uid.uio.nbb (Unknown Source:17)
dji.sdk.realname.uid.uio.ghu (Unknown Source:1)
dji.sdk.realname.uid.uio.hgf (Unknown Source:1)
dji.sdk.realname.uid.uio.gfd (Unknown Source:90)
dji.sdk.realname.AppActivationManager.init (Unknown Source:4)
dji.sdk.sdkmanager.DJISDKManager.initParams (Unknown Source:115)
dji.sdk.sdkmanager.DJISDKManager.initSDKManager (Unknown Source:12)
dji.sdk.sdkmanager.DJISDKManager.registerApp (Unknown Source:39)
dji.sdk.sdkmanager.DJISDKManager.access$800
dji.sdk.sdkmanager.DJISDKManager$6$1.onDownloadSuccess (Unknown Source:8)
dji.internal.ghu.ghu.fdd (Unknown Source:19)
dji.sdk.sdkmanager.DJISDKManager$6.run (Unknown Source:37)
dji.sdksharedlib.gfd.koy.run (Unknown Source:5)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.lang.Thread.run (Thread.java:923)
```

Not sure where this gets triggered. I'm using `Mobile-UXSDK-Beta-Android` (https://github.com/dji-sdk/Mobile-UXSDK-Beta-Android), which uses `UserAccountManager` and could probably be the reason behind this exception. Though the issue is, that internal sdk call triggers null pointer exception and should therefore probably be fixed internally. Also it might be related to this issue FYI https://github.com/dji-sdk/Mobile-SDK-Android/issues/410.

**Comment by DJI-William** [comment]
Will fix in next sprint.

**Comment by jeryini** [comment]
Hello @DJI-William !

Still getting these crashes even though using 4.16v.

**Comment by DJI-William** [comment]
@jeryini Can you post a crash log for me please?

**Comment by jeryini** [comment]
Hello @DJI-William !

Sure thing, here are they:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean dji.internal.useraccount.UserAccountInfo.isValid()' on a null object reference
       at dji.sdk.realname.uid.nhf.nbb()
       at dji.sdk.realname.uid.nhf.nhf()
       at dji.sdk.realname.uid.nhf.hgf()
       at dji.sdk.realname.uid.nhf.uio()
       at dji.sdk.realname.AppActivationManager.init()
       at dji.sdk.sdkmanager.DJISDKManager.initParams()
       at dji.sdk.sdkmanager.DJISDKManager.initSDKManager()
       at dji.sdk.sdkmanager.DJISDKManager.registerApp()
       at dji.sdk.sdkmanager.DJISDKManager.access$1000()
       at dji.sdk.sdkmanager.DJISDKManager$8$1.onDownloadSuccess()
       at dji.internal.jhg.fdd.fdd()
       at dji.sdk.sdkmanager.DJISDKManager$8.run()
       at dji.sdksharedlib.dgh.gfd$fdd.run()
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)
```

Also the user device that caused this crash had quite an old Android version 7.0. Might this be the reason behind it?

**Comment by jeryini** [comment]
There is a similar crash happening also on the latest 4.16 SDK version:
```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.lang.String dji.internal.useraccount.UserAccountInfo.token' on a null object reference
       at dji.internal.useraccount.gfd$ghu.fdd(:6)
       at dji.internal.useraccount.gfd$uio.onSuccess(:155)
       at dji.internal.useraccount.gfd$uio.onSuccess(:2)
       at dji.thirdparty.afinal.http.HttpHandler.onProgressUpdate(:30)
       at dji.thirdparty.afinal.core.AsyncTask$InternalHandler.handleMessage(:17)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8582)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:563)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
```

**Comment by DJI-William** [comment]
Will assign to a developer to look at it soon.

**Comment by DJI-William** [comment]
@jeryini  I think the last fix does not take effects, may I ask how to reproduce it, then we will test the new fix.

**Comment by DJI-William** [comment]
@jeryini Thank you for your support, the previous fix didn't make the effect, we will fix in 4.16.1 again. I am sorry for your inconvenience.
