### ISSUE TITLE
NullPointerException - dji.ux.beta.map.widget.map.FlyZoneHelper.addCircleToMap 

### ISSUE THREAD

**Issue by luoyexk** [dji-sdk/Mobile-SDK-Android#1061]
Fatal Exception: java.lang.NullPointerException
       at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1019)
       at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1014)
       at dji.ux.beta.map.widget.map.FlyZoneHelper.addCircleToMap(FlyZoneHelper.java:632)
       at dji.ux.beta.map.widget.map.FlyZoneHelper.drawFlyZone(FlyZoneHelper.java:511)
       at dji.ux.beta.map.widget.map.FlyZoneHelper.onFlyZoneListUpdate(FlyZoneHelper.java:204)
       at dji.ux.beta.map.widget.map.MapWidget.onFlyZoneListUpdate(MapWidget.java:653)
       at dji.ux.beta.map.widget.map.MapWidget.lambda$CC8HqsDVt_Ue_wJysFAlWmsF6h8()
       at dji.ux.beta.map.widget.map.-$$Lambda$MapWidget$CC8HqsDVt_Ue_wJysFAlWmsF6h8.accept(:4)
       at dji.thirdparty.io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(:2)
       at dji.thirdparty.io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(:14)
       at dji.thirdparty.io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(:2)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/56322'>Zendesk ticket #56322</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by DJI-William** [comment]
beta是开源版本，你们自己可以修一下提个PR嘛，给开源项目做做贡献。

**Comment by DJI-William** [comment]
https://github.com/dji-sdk/Mobile-UXSDK-Beta-Android/issues/49
准备提PR。
