### ISSUE TITLE
Samsung Galaxy S21 Ultra 5G running Android 12 crashes SDK Helper.install

### ISSUE THREAD

**Issue by codeversed** [dji-sdk/Mobile-SDK-Android#1069]
**Device**: Samsung Galaxy S21 Ultra 5G
**Software**: OneUI 4.0, Android 12
**DJI SDK**: 4.15.1
**Tested**: Our app and the latest sample app

**Issue**: `com.secneo.sdk.Helper.install(this)` crashes

This is currently ONLY affecting Galaxy S21 devices but it seems to be crashing for all versions of the DJI SDK. Testing the sample app points to an issue with the SDK itself and not my setup. From the stack trace below, I do not have enough information or code access to resolve the issue. This is a huge concern because the S21 is a very popular device with our app userbase. 

_________________________________________________________________________________________________________

**Stack Trace**: 
```
2021-11-29 18:06:29.859 18288-18288/com.dji.sdk.sample A/.dji.sdk.sampl: java_vm_ext.cc:579] JNI DETECTED ERROR IN APPLICATION: buf == null
    java_vm_ext.cc:579]     in call to SetPrimitiveArrayRegion
    java_vm_ext.cc:579]     from java.lang.Object[] com.secneo.sdk.Helper.makeInMemoryDexElements(java.lang.Object, java.util.List, java.lang.String)
2021-11-29 18:06:29.889 18288-18288/com.dji.sdk.sample A/.dji.sdk.sampl:  Runtime aborting...
     Dumping all threads without mutator lock held
     All threads:
     DALVIK THREADS (19):
     "main" prio=10 tid=1 Runnable
       | group="" sCount=0 ucsCount=0 flags=0 obj=0x72288f68 self=0x793f715be0
       | sysTid=18288 nice=-10 cgrp=top-app sched=0/0 handle=0x7af3a0c500
       | state=R schedstat=( 195948182 9194790 54 ) utm=13 stm=5 core=7 HZ=100
       | stack=0x7fc88fa000-0x7fc88fc000 stackSize=8188KB
       | held mutexes= "abort lock" "mutator lock"(shared held)
       native: (no native stack frames for thread 18288)
       at com.secneo.sdk.Helper.makeInMemoryDexElements(Native method)
       at com.secneo.sdk.DexInstall.V28install(:144)
       at com.secneo.sdk.DexInstall.installSecondaryDexes(:58)
       at com.secneo.sdk.DexInstall.install(:33)
       at java.lang.Runtime.nativeLoad(Native method)
       at java.lang.Runtime.nativeLoad(Runtime.java:1121)
       at java.lang.Runtime.loadLibrary0(Runtime.java:1075)
       - locked <0x03717822> (a java.lang.Runtime)
       at java.lang.Runtime.loadLibrary0(Runtime.java:998)
       at java.lang.System.loadLibrary(System.java:1656)
       at com.secneo.sdk.Helper.install(:41)
       at com.dji.sdk.sample.internal.controller.DJISampleApplication.attachBaseContext(:78)
       at android.app.Application.attach(Application.java:350)
       at android.app.Instrumentation.newApplication(Instrumentation.java:1178)
       at android.app.LoadedApk.makeApplication(LoadedApk.java:1456)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7381)
       at android.app.ActivityThread.access$1700(ActivityThread.java:309)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2268)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8582)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:563)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
     
     "Runtime worker thread 0" prio=10 tid=2 Native (still starting up)
       | group="" sCount=1 ucsCount=0 flags=1 obj=0x0 self=0x793f749e40
       | sysTid=18289 nice=-20 cgrp=top-app sched=0/0 handle=0x7af2349cb0
       | state=S schedstat=( 255155 53386 2 ) utm=0 stm=0 core=6 HZ=100
       | stack=0x7af233a000-0x7af233c000 stackSize=63KB
       | held mutexes=
       native: #00 pc 0000000000010fb0  /apex/com.android.runtime/lib64/bionic/libc.so (offset 3d000) (???)
       (no managed stack frames)
     
     "Runtime worker thread 3" prio=10 tid=3 Native (still starting up)
       | group="" sCount=1 ucsCount=0 flags=1 obj=0x0 self=0x793f7466a0
       | sysTid=18293 nice=-20 cgrp=top-app sched=0/0 handle=0x7ae5497cb0
       | state=S schedstat=( 66198 0 1 ) utm=0 stm=0 core=4 HZ=100
       | stack=0x7ae5488000-0x7ae548a000 stackSize=63KB
       | held mutexes=
       native: #00 pc 0000000000010fb0  /apex/com.android.runtime/lib64/bionic/libc.so (offset 3d000) (???)
       (no managed stack frames)
     
     "Runtime worker thread 1" prio=10 tid=4 Native (still starting up)
       | group="" sCount=1 ucsCount=0 flags=1 obj=0x0 self=0x793f72c570
2021-11-29 18:06:29.889 18288-18288/com.dji.sdk.sample A/.dji.sdk.sampl:    | sysTid=18290 nice=-20 cgrp=top-app sched=0/0 handle=0x7af2333cb0
       | state=S schedstat=( 57604 163229 1 ) utm=0 stm=0 core=4 HZ=100
       | stack=0x7af2324000-0x7af2326000 stackSize=63KB
       | held mutexes=
       native: #00 pc 0000000000010fb0  /apex/com.android.runtime/lib64/bionic/libc.so (offset 3d000) (???)
       (no managed stack frames)
     
     "Signal Catcher" prio=10 tid=5 WaitingInMainSignalCatcherLoop
       | group="" sCount=1 ucsCount=0 flags=1 obj=0x12c409e0 self=0x793f723a60
       | sysTid=18294 nice=-20 cgrp=top-app sched=0/0 handle=0x77b92e7cb0
       | state=S schedstat=( 342187 0 1 ) utm=0 stm=0 core=4 HZ=100
       | stack=0x77b91f0000-0x77b91f2000 stackSize=991KB
       | held mutexes=
       native: #00 pc 0000000000001bac  /apex/com.android.runtime/lib64/bionic/libc.so (offset a1000) (???)
       (no managed stack frames)
     
     "Runtime worker thread 2" prio=10 tid=6 Native (still starting up)
       | group="" sCount=1 ucsCount=0 flags=1 obj=0x0 self=0x793f74ba10
       | sysTid=18292 nice=-20 cgrp=top-app sched=0/0 handle=0x7ae558fcb0
       | state=S schedstat=( 398906 0 1 ) utm=0 stm=0 core=7 HZ=100
       | stack=0x7ae5580000-0x7ae5582000 stackSize=63KB
       | held mutexes=
       native: #00 pc 0000000000010fb0  /apex/com.android.runtime/lib64/bionic/libc.so (offset 3d000) (???)
       (no managed stack frames)
     
     "perfetto_hprof_listener" prio=10 tid=7 Native (still starting up)
       | group="" sCount=1 ucsCount=0 flags=1 obj=0x0 self=0x793f72a9a0
       | sysTid=18295 nice=-20 cgrp=top-app sched=0/0 handle=0x77b81e9cb0
       | state=S schedstat=( 143281 0 1 ) utm=0 stm=0 core=5 HZ=100
       | stack=0x77b80f2000-0x77b80f4000 stackSize=991KB
       | held mutexes=
       native: #00 pc 0000000000000f08  /apex/com.android.runtime/lib64/bionic/libc.so (offset a1000) (???)
       (no managed stack frames)
     
     "ADB-JDWP Connection Control Thread" prio=10 tid=8 WaitingInMainDebuggerLoop
       | group="" sCount=1 ucsCount=0 flags=1 obj=0x12c19698 self=0x793f725630
       | sysTid=18296 nice=-20 cgrp=top-app sched=0/0 handle=0x77b80ebcb0
       | state=S schedstat=( 1701460 145625 6 ) utm=0 stm=0 core=5 HZ=100
       | stack=0x77b7ff4000-0x77b7ff6000 stackSize=991KB
       | held mutexes=
       native: #00 pc 000000000000026c  /apex/com.android.runtime/lib64/bionic/libc.so (offset a3000) (???)
       (no managed stack frames)
     
     "Jit thread pool worker thread 0" prio=5 tid=9 Native
       | group="" sCount=1 ucsCount=0 flags=1 obj=0x12cc0e40 self=0x793f744ad0
       | sysTid=18297 nice=9 cgrp=top-app sched=0/0 handle=0x77b7fedcb0
       | state=S schedstat=( 8884947 849897 36 ) utm=0 stm=0 core=4 HZ=100
       | stack=0x77b7eee000-0x77b7ef0000 stackSize=1023KB
       | held mutexes=
       native: #00 pc 0000000000010fb0  /apex/com.android.runtime/lib64/bionic/libc.so (offset 3d000) (???)
       (no managed stack frames)
     
     "HeapTaskDaemon" prio=5 tid=10 WaitingForTaskProcessor
       | group="" sCount=1 ucsCount=0 flags=1 obj=0x12c19740 self=0x793f72fd10
       | sysTid=18298 nice=4 cgrp=top-app sched=0/0 handle=0x77b7ee7cb0
       | state=S schedstat=( 137188 31667 2 ) utm=0 stm=0 core=6 HZ=100
       | stack=0x77b7de4000-0x77b7de6000 stackSize=1039KB
       | held mutexes=
2021-11-29 18:06:29.889 18288-18288/com.dji.sdk.sample A/.dji.sdk.sampl:    native: #00 pc 0000000000010fb4  /apex/com.android.runtime/lib64/bionic/libc.so (offset 3d000) (???)
       at dalvik.system.VMRuntime.runHeapTasks(Native method)
       at java.lang.Daemons$HeapTaskDaemon.runInternal(Daemons.java:531)
       at java.lang.Daemons$Daemon.run(Daemons.java:139)
       at java.lang.Thread.run(Thread.java:920)
     
     "FinalizerDaemon" prio=5 tid=11 Waiting
       | group="" sCount=1 ucsCount=0 flags=1 obj=0x12c19860 self=0x793f74f1b0
       | sysTid=18300 nice=4 cgrp=top-app sched=0/0 handle=0x77b7c7fcb0
       | state=S schedstat=( 100261 0 2 ) utm=0 stm=0 core=5 HZ=100
       | stack=0x77b7b7c000-0x77b7b7e000 stackSize=1039KB
       | held mutexes=
       native: #00 pc 0000000000010fb0  /apex/com.android.runtime/lib64/bionic/libc.so (offset 3d000) (???)
       at java.lang.Object.wait(Native method)
       - waiting on <0x0636b2b3> (a java.lang.Object)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:190)
       - locked <0x0636b2b3> (a java.lang.Object)
       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:211)
       at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:273)
       at java.lang.Daemons$Daemon.run(Daemons.java:139)
       at java.lang.Thread.run(Thread.java:920)
     
     "FinalizerWatchdogDaemon" prio=5 tid=12 Waiting
       | group="" sCount=1 ucsCount=0 flags=1 obj=0x12c198f0 self=0x793f750d80
       | sysTid=18302 nice=4 cgrp=top-app sched=0/0 handle=0x77b7b75cb0
       | state=S schedstat=( 61042 0 1 ) utm=0 stm=0 core=7 HZ=100
       | stack=0x77b7a72000-0x77b7a74000 stackSize=1039KB
       | held mutexes=
       native: #00 pc 0000000000010fb0  /apex/com.android.runtime/lib64/bionic/libc.so (offset 3d000) (???)
       at java.lang.Object.wait(Native method)
       - waiting on <0x092ed070> (a java.lang.Daemons$FinalizerWatchdogDaemon)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.Object.wait(Object.java:568)
       at java.lang.Daemons$FinalizerWatchdogDaemon.sleepUntilNeeded(Daemons.java:341)
       - locked <0x092ed070> (a java.lang.Daemons$FinalizerWatchdogDaemon)
       at java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:321)
       at java.lang.Daemons$Daemon.run(Daemons.java:139)
       at java.lang.Thread.run(Thread.java:920)
     
     "ReferenceQueueDaemon" prio=5 tid=13 Waiting
       | group="" sCount=1 ucsCount=0 flags=1 obj=0x12c197d0 self=0x793f728dd0
       | sysTid=18299 nice=4 cgrp=top-app sched=0/0 handle=0x77b7d89cb0
       | state=S schedstat=( 275365 0 1 ) utm=0 stm=0 core=4 HZ=100
       | stack=0x77b7c86000-0x77b7c88000 stackSize=1039KB
       | held mutexes=
       native: #00 pc 0000000000010fb0  /apex/com.android.runtime/lib64/bionic/libc.so (offset 3d000) (???)
       at java.lang.Object.wait(Native method)
       - waiting on <0x03110fe9> (a java.lang.Class<java.lang.ref.ReferenceQueue>)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.Object.wait(Object.java:568)
       at java.lang.Daemons$ReferenceQueueDaemon.runInternal(Daemons.java:217)
       - locked <0x03110fe9> (a java.lang.Class<java.lang.ref.ReferenceQueue>)
       at java.lang.Daemons$Daemon.run(Daemons.java:139)
       at java.lang.Thread.run(Thread.java:920)
     
     "Binder:18288_1" prio=5 tid=14 Native
2021-11-29 18:06:29.889 18288-18288/com.dji.sdk.sample A/.dji.sdk.sampl:    | group="" sCount=1 ucsCount=0 flags=1 obj=0x12c80e60 self=0x793f73f760
       | sysTid=18303 nice=0 cgrp=top-app sched=0/0 handle=0x77b796dcb0
       | state=S schedstat=( 564115 1563177 4 ) utm=0 stm=0 core=5 HZ=100
       | stack=0x77b7876000-0x77b7878000 stackSize=991KB
       | held mutexes=
       native: #00 pc 00000000000011ac  /apex/com.android.runtime/lib64/bionic/libc.so (offset a1000) (???)
       (no managed stack frames)
     
     "Binder:18288_2" prio=5 tid=15 Native
       | group="" sCount=1 ucsCount=0 flags=1 obj=0x12d00020 self=0x793f752950
       | sysTid=18305 nice=0 cgrp=top-app sched=0/0 handle=0x77b786fcb0
       | state=S schedstat=( 5880987 452917 5 ) utm=0 stm=0 core=0 HZ=100
       | stack=0x77b7778000-0x77b777a000 stackSize=991KB
       | held mutexes=
       native: #00 pc 00000000000011ac  /apex/com.android.runtime/lib64/bionic/libc.so (offset a1000) (???)
       (no managed stack frames)
     
     "Binder:18288_3" prio=5 tid=16 Native
       | group="" sCount=1 ucsCount=0 flags=1 obj=0x12d80020 self=0x793f71cb20
       | sysTid=18306 nice=0 cgrp=top-app sched=0/0 handle=0x77b7721cb0
       | state=S schedstat=( 1890052 6406 2 ) utm=0 stm=0 core=5 HZ=100
       | stack=0x77b762a000-0x77b762c000 stackSize=991KB
       | held mutexes=
       native: #00 pc 00000000000011ac  /apex/com.android.runtime/lib64/bionic/libc.so (offset a1000) (???)
       (no managed stack frames)
     
     "Binder:18288_4" prio=5 tid=17 Native
       | group="" sCount=1 ucsCount=0 flags=1 obj=0x12dc0020 self=0x793f74d5e0
       | sysTid=18318 nice=0 cgrp=top-app sched=0/0 handle=0x77b740ecb0
       | state=S schedstat=( 665417 4233021 7 ) utm=0 stm=0 core=4 HZ=100
       | stack=0x77b7317000-0x77b7319000 stackSize=991KB
       | held mutexes=
       native: #00 pc 00000000000011ac  /apex/com.android.runtime/lib64/bionic/libc.so (offset a1000) (???)
       (no managed stack frames)
     
     "Profile Saver" prio=5 tid=18 Native
       | group="" sCount=1 ucsCount=0 flags=1 obj=0x12e00020 self=0x793f71e6f0
       | sysTid=18325 nice=9 cgrp=top-app sched=0/0 handle=0x77b2419cb0
       | state=S schedstat=( 152136 0 2 ) utm=0 stm=0 core=5 HZ=100
       | stack=0x77b2322000-0x77b2324000 stackSize=991KB
       | held mutexes=
       native: #00 pc 0000000000010fb4  /apex/com.android.runtime/lib64/bionic/libc.so (offset 3d000) (???)
       (no managed stack frames)
     
     "queued-work-looper-timer" prio=5 tid=19 TimedWaiting
       | group="" sCount=1 ucsCount=0 flags=1 obj=0x12c2f5f0 self=0x793f757cc0
       | sysTid=18326 nice=0 cgrp=top-app sched=0/0 handle=0x77b0ab7cb0
       | state=S schedstat=( 108698 0 1 ) utm=0 stm=0 core=6 HZ=100
       | stack=0x77b09b4000-0x77b09b6000 stackSize=1039KB
       | held mutexes=
       native: #00 pc 0000000000010fb4  /apex/com.android.runtime/lib64/bionic/libc.so (offset 3d000) (???)
       at java.lang.Object.wait(Native method)
       - waiting on <0x0852f46e> (a java.util.TaskQueue)
       at java.lang.Object.wait(Object.java:442)
       at java.util.TimerThread.mainLoop(Timer.java:559)
       - locked <0x0852f46e> (a java.util.TaskQueue)
       at java.util.TimerThread.run(Timer.java:512)
     
     Aborting thread:
     "main" prio=10 tid=1 Native
       | group="" sCount=0 ucsCount=0 flags=0 obj=0x72288f68 self=0x793f715be0
2021-11-29 18:06:29.890 18288-18288/com.dji.sdk.sample A/.dji.sdk.sampl:    | sysTid=18288 nice=-10 cgrp=top-app sched=0/0 handle=0x7af3a0c500
       | state=R schedstat=( 215745474 9227290 90 ) utm=14 stm=6 core=7 HZ=100
       | stack=0x7fc88fa000-0x7fc88fc000 stackSize=8188KB
       | held mutexes= "abort lock"
       native: (no native stack frames for thread 18288)
       at com.secneo.sdk.Helper.makeInMemoryDexElements(Native method)
       at com.secneo.sdk.DexInstall.V28install(:144)
       at com.secneo.sdk.DexInstall.installSecondaryDexes(:58)
       at com.secneo.sdk.DexInstall.install(:33)
       at java.lang.Runtime.nativeLoad(Native method)
       at java.lang.Runtime.nativeLoad(Runtime.java:1121)
       at java.lang.Runtime.loadLibrary0(Runtime.java:1075)
       - locked <0x03717822> (a java.lang.Runtime)
       at java.lang.Runtime.loadLibrary0(Runtime.java:998)
       at java.lang.System.loadLibrary(System.java:1656)
       at com.secneo.sdk.Helper.install(:41)
       at com.dji.sdk.sample.internal.controller.DJISampleApplication.attachBaseContext(:78)
       at android.app.Application.attach(Application.java:350)
       at android.app.Instrumentation.newApplication(Instrumentation.java:1178)
       at android.app.LoadedApk.makeApplication(LoadedApk.java:1456)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7381)
       at android.app.ActivityThread.access$1700(ActivityThread.java:309)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2268)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8582)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:563)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
     
2021-11-29 18:06:29.890 18288-18288/com.dji.sdk.sample A/.dji.sdk.sampl: runtime.cc:677] JNI DETECTED ERROR IN APPLICATION: buf == null
    runtime.cc:677]     in call to SetPrimitiveArrayRegion
    runtime.cc:677]     from java.lang.Object[] com.secneo.sdk.Helper.makeInMemoryDexElements(java.lang.Object, java.util.List, java.lang.String)
    
    --------- beginning of crash
2021-11-29 18:06:29.890 18288-18288/com.dji.sdk.sample A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 18288 (.dji.sdk.sample), pid 18288 (.dji.sdk.sample)
```

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/57076'>Zendesk ticket #57076</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by codeversed** [comment]
@dji-dev Ticket has been submitted.

**Comment by ajanes3** [comment]
Also hitting this issue. I understand that the fix is coming at 4.16. But I think a hotfix should come out before then. This is breaking all third party apps on Galaxy S21 (a very popular device) with Android 12 (OS being rolled out to this device by carriers in the US right now).

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/57076'>Zendesk ticket #57076</a>:<br><br>I understand your concerns. But 4.16 version will be released at the end of December. So you will be able to use it on Android 12 soon.
<br><p><em><small>°°°</small></em></p>

**Comment by gg-deploy-dd** [comment]
Hello @dji-dev Our customers have been facing this issue at an increasing rate as they upgrade to Android 12. Not seeing any updates on the github project (branches, PR's) is a bit concerning. Are we still on for a 4.16 release by end of December?

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/57076'>Zendesk ticket #57076</a>:<br><br>Hi. Yes it will be released at the end of December. And in this version we will solve the problem of android 12 crash.
<br><p><em><small>°°°</small></em></p>

**Comment by dicisoft** [comment]
Hi @dji-dev any news about it ?

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/57076'>Zendesk ticket #57076</a>:<br><br>Yes. MSDK 4.16 has been released.
<br><p><em><small>°°°</small></em></p>

**Comment by Michael-DJI** [comment]
update to 4.16.1
