### ISSUE TITLE
 java.lang.AbstractMethodError: abstract method "okio.Cursor okio.Source.cursor()"

### ISSUE THREAD

**Issue by zhufeixiang** [dji-sdk/Mobile-SDK-Android#1075]
release 版本 不管混不混淆都会报这个错误！！以下为错误日志：
AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: *************, PID: 32358
    java.lang.AbstractMethodError: abstract method "okio.Cursor okio.Source.cursor()"
        at okio.RealBufferedSource.<init>(SourceFile:3)
        at okio.Okio__OkioKt.buffer(SourceFile:1)
        at okio.Okio.buffer(SourceFile:2)
        at dji.thirdparty.okhttp3.internal.http1.Http1Codec.openResponseBody(Unknown Source:89)
        at dji.thirdparty.okhttp3.internal.http.CallServerInterceptor.intercept(Unknown Source:365)
        at dji.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:77)
        at dji.thirdparty.okhttp3.internal.connection.ConnectInterceptor.intercept(Unknown Source:33)
        at dji.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:77)
        at dji.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:6)
        at dji.thirdparty.okhttp3.internal.cache.CacheInterceptor.intercept(Unknown Source:132)
        at dji.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:77)
        at dji.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:6)
        at dji.thirdparty.okhttp3.internal.http.BridgeInterceptor.intercept(Unknown Source:160)
        at dji.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:77)
        at dji.thirdparty.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(Unknown Source:49)
        at dji.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:77)
        at dji.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:6)
        at dji.thirdparty.okhttp3.RealCall.getResponseWithInterceptorChain(Unknown Source:114)
        at dji.thirdparty.okhttp3.RealCall$AsyncCall.execute(Unknown Source:4)
        at dji.thirdparty.okhttp3.internal.NamedRunnable.run(Unknown Source:17)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Thread

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/57939'>Zendesk ticket #57939</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by DJI-William** [comment]
怎么触发得呢？debug版本就没问题嘛？Sample是否能复现？
