### ISSUE TITLE
cannot locate symbol "getpagesize" referenced by "libffmpeg.so"

### ISSUE THREAD

**Issue by Yezersky** [dji-sdk/Mobile-SDK-Android#108]
-  Description: cannot locate symbol "getpagesize" referenced by "libffmpeg.so"
-  Steps to reproduce the bug or crash issues: run the sample code on Android 4.4.2
-  Crash logs: 
```
05-18 08:35:44.520 2293-2293/? E/dalvikvm: dlopen("/data/app-lib/com.dji.sdk.sample-1/libSDKRelativeJNI.so") failed: dlopen failed: could not load library "libdjivideo.so" needed by "libSDKRelativeJNI.so"; caused by could not load library "libffmpeg.so" needed by "libdjivideo.so"; caused by cannot locate symbol "getpagesize" referenced by "libffmpeg.so"...
05-18 08:35:44.520 2293-2293/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.dji.sdk.sample, PID: 2293
                                                 java.lang.UnsatisfiedLinkError: Native method not found: dji.midware.natives.SDKRelativeJNI.native_getUsbAccessoryAttachedString:()Ljava/lang/String;
                                                     at dji.midware.natives.SDKRelativeJNI.native_getUsbAccessoryAttachedString(Native Method)
                                                     at dji.sdk.sdkmanager.DJISDKManager.<clinit>(Unknown Source)
                                                     at com.dji.sdk.sample.internal.controller.DJISampleApplication.onCreate(DJISampleApplication.java:82)
                                                     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4344)
                                                     at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                     at dalvik.system.NativeStart.main(Native Method)

```
-  DJI Android SDK version: Android SDK 4.0.2
-  Android system version: Android 4.4.2
-  Android device: Emulator x86
-  Android Studio version: Android Studio 2.3.2

**Comment by talobin** [comment]
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this issue (x86) already.
Please feel free to reopen if the problem still exists.
Thanks!
