### ISSUE TITLE
Registering of app causing DJI internal exception

### ISSUE THREAD

**Issue by gg-deploy-dd** [dji-sdk/Mobile-SDK-Android#1098]
Calling of `DJISdkManager.startConnectionToProduct() ` causes the app to crash in sometimes with the following exception
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
    at dji.internal.analytics.helper.GuidUtil.queryUri
    at dji.internal.analytics.helper.GuidUtil.getFromMediaFile
    at dji.internal.analytics.helper.GuidUtil.getFromFile
    at dji.internal.analytics.helper.GuidUtil.createGUID
    at dji.internal.analytics.helper.DJIAnalyticsSession.getInstallId
    at dji.internal.analytics.helper.DJIAnalyticsHeaderManager.getInstallId
    at dji.internal.analytics.helper.DJIAnalyticsHeaderManager.initHeaders
    at dji.internal.analytics.helper.DJIAnalyticsHeaderManager.init
    at dji.internal.analytics.DJIAnalyticsEngine.<init>
    at dji.internal.analytics.DJIAnalyticsEngine.<init>
    at dji.internal.analytics.DJIAnalyticsEngine$ddf.<clinit>
    at dji.internal.analytics.DJIAnalyticsEngine$ddf.fdd
    at dji.internal.analytics.DJIAnalyticsEngine.getInstance
    at dji.sdk.sdkmanager.DJISDKManager.initParams
    at dji.sdk.sdkmanager.DJISDKManager.initSDKManager
    at dji.sdk.sdkmanager.DJISDKManager.registerApp
    at dji.sdk.sdkmanager.DJISDKManager.access$1000
    at dji.sdk.sdkmanager.DJISDKManager$8$1.onDownloadSuccess
    at dji.internal.jhg.fdd$dgh.onDownloadSuccess
    at dji.internal.jhg.fdd$gfd.onResponse
    at dji.thirdparty.okhttp3.RealCall$AsyncCall.execute
    at dji.thirdparty.okhttp3.internal.NamedRunnable.run
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:923)
java.lang.ExceptionInInitializerError: null
    at dji.internal.analytics.DJIAnalyticsEngine$ddf.fdd
    at dji.internal.analytics.DJIAnalyticsEngine.getInstance
    at dji.sdk.sdkmanager.DJISDKManager.initParams
    at dji.sdk.sdkmanager.DJISDKManager.initSDKManager
    at dji.sdk.sdkmanager.DJISDKManager.registerApp
    at dji.sdk.sdkmanager.DJISDKManager.access$1000
    at dji.sdk.sdkmanager.DJISDKManager$8$1.onDownloadSuccess
    at dji.internal.jhg.fdd$dgh.onDownloadSuccess
    at dji.internal.jhg.fdd$gfd.onResponse
    at dji.thirdparty.okhttp3.RealCall$AsyncCall.execute
    at dji.thirdparty.okhttp3.internal.NamedRunnable.run
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:923)
```

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/59653'>Zendesk ticket #59653</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by DJI-William** [comment]
A known issue, already fixed and merged in 4.16.1 version. It will be released in the end of February.

**Comment by gg-deploy-dd** [comment]
@DJI-William Any update on this fix?

**Comment by DJI-William** [comment]
@gg-deploy-dd We are still fixing other bugs, it will be released within 2 weeks.
