### ISSUE TITLE
ArrayIndexOutOfBoundsException in dji.midware.usb.P3.UsbAccessoryService

### ISSUE THREAD

**Issue by JonasVautherin** [dji-sdk/Mobile-SDK-Android#11]
Here is an error I get on a Samsung Galaxy Tab 4 (SM-T330NU) running Android 5.1.1:

    java.lang.ArrayIndexOutOfBoundsException: src.length=4096 srcPos=0 dst.length=5120 dstPos=1980 length=3592
           at java.lang.System.arraycopy(System.java)
           at dji.midware.usb.P3.UsbAccessoryService.b()
           at dji.midware.usb.P3.UsbAccessoryService.a()
           at dji.midware.usb.P3.UsbAccessoryService$RecvOsdRunnable.run()
           at java.lang.Thread.run(Thread.java:818)

**Comment by SilverChangjian** [comment]
Thanks for provide this problem. We will try to reproduce it and solve this ASAP.

**Comment by SilverChangjian** [comment]
Please use the latest SDK for your project, we are not going to support the 2.x version of the SDK.
