### ISSUE TITLE
 Verifier rejected class dji.sdk.sdkmanager.DJISDKManager:

### ISSUE THREAD

**Issue by amirhossinD** [dji-sdk/Mobile-SDK-Android#1104]
java.lang.VerifyError: Verifier rejected class dji.sdk.sdkmanager.DJISDKManager: void dji.sdk.sdkmanager.DJISDKManager.<init>() failed to verify: void dji.sdk.sdkmanager.DJISDKManager.<init>(): [0x0] Constructor returning without calling superclass constructor (declaration of 'dji.sdk.sdkmanager.DJISDKManager' appears in /data/app/~~_7ulHiKK0p9SiK_nexwbxQ==/com.example.dji-DGJLaR-adwU0aS6zNc7CWA==/base.apk!classes10.dex)
        at dji.sdk.sdkmanager.DJISDKManager.getInstance(Unknown Source:0)
        at com.example.dji.ui.mission.MissionActivity$startSDKRegistration$1.invokeSuspend(MissionActivity.kt:123)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/59923'>Zendesk ticket #59923</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by DJI-William** [comment]
It seems like the MSDK hasn't been found. Are you running this sample without any modification?

**Comment by Chamud** [comment]
Did you figure out the fix?
