### ISSUE TITLE
MSDK 4.16版本，DJISDKManager.registerApp发生异常导致闪退。

### ISSUE THREAD

**Issue by pwj1568** [dji-sdk/Mobile-SDK-Android#1116]
Tinker.UncaughtHandler: TinkerUncaughtHandler catch exception:java.lang.ExceptionInInitializerError
        at dji.internal.analytics.DJIAnalyticsEngine$ddf.fdd(Unknown Source:0)
        at dji.internal.analytics.DJIAnalyticsEngine.getInstance(Unknown Source:0)
        at dji.sdk.sdkmanager.DJISDKManager.initParams(Unknown Source:27)
        at dji.sdk.sdkmanager.DJISDKManager.initSDKManager(Unknown Source:12)
        at dji.sdk.sdkmanager.DJISDKManager.registerApp(Unknown Source:37)
        at dji.sdk.sdkmanager.DJISDKManager.access$1000(Unknown Source:0)
        at dji.sdk.sdkmanager.DJISDKManager$8$1.onDownloadFailed(Unknown Source:18)
        at dji.internal.jhg.fdd.fdd(Unknown Source:31)
        at dji.sdk.sdkmanager.DJISDKManager$8.run(Unknown Source:37)
        at dji.sdksharedlib.dgh.gfd$fdd.run(Unknown Source:5)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at dji.internal.analytics.helper.GuidUtil.queryUri(Unknown Source:67)
        at dji.internal.analytics.helper.GuidUtil.getFromMediaFile(Unknown Source:1)
        at dji.internal.analytics.helper.GuidUtil.getFromFile(Unknown Source:6)
        at dji.internal.analytics.helper.GuidUtil.createGUID(Unknown Source:21)
        at dji.internal.analytics.helper.DJIAnalyticsSession.getInstallId(Unknown Source:8)
        at dji.internal.analytics.helper.DJIAnalyticsHeaderManager.getInstallId(Unknown Source:0)
        at dji.internal.analytics.helper.DJIAnalyticsHeaderManager.initHeaders(Unknown Source:0)
        at dji.internal.analytics.helper.DJIAnalyticsHeaderManager.init(Unknown Source:3)
        at dji.internal.analytics.DJIAnalyticsEngine.<init>(Unknown Source:79)
        at dji.internal.analytics.DJIAnalyticsEngine.<init>(Unknown Source:0)
        at dji.internal.analytics.DJIAnalyticsEngine$ddf.<clinit>(Unknown Source:3)
        at dji.internal.analytics.DJIAnalyticsEngine$ddf.fdd(Unknown Source:0) 
        at dji.internal.analytics.DJIAnalyticsEngine.getInstance(Unknown Source:0) 
        at dji.sdk.sdkmanager.DJISDKManager.initParams(Unknown Source:27) 
        at dji.sdk.sdkmanager.DJISDKManager.initSDKManager(Unknown Source:12) 
        at dji.sdk.sdkmanager.DJISDKManager.registerApp(Unknown Source:37) 
        at dji.sdk.sdkmanager.DJISDKManager.access$1000(Unknown Source:0) 
        at dji.sdk.sdkmanager.DJISDKManager$8$1.onDownloadFailed(Unknown Source:18) 
        at dji.internal.jhg.fdd.fdd(Unknown Source:31) 
        at dji.sdk.sdkmanager.DJISDKManager$8.run(Unknown Source:37) 
        at dji.sdksharedlib.dgh.gfd$fdd.run(Unknown Source:5) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923)

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/61255'>Zendesk ticket #61255</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by DJI-William** [comment]
是bug，在下周的4.16.1版本会修复。
