### ISSUE TITLE
SDK 4.16 - Failed to Create Unique File - App Crash Bug

### ISSUE THREAD

**Issue by jacobboesch** [dji-sdk/Mobile-SDK-Android#1121]
Hello, we're currently experiencing a bug using the 4.16 version of the SDK. The issue is that the new version of the sdk is creating files called dji_guid.jpg in the users picture directory. This happens each time the user launches the application. Eventually, the sdk creates enough of these files where they conflict and crash the app. This bug is not present in the previous version of the SDK however, we need to use version 4.16 to support the DJI Mini 2. 

Steps to reproduce:
1. Install the app for the first time
2. Navigate to the android device's file manager
3. Navigate to the internalStorage/Pictures/dji directory
4. The user will see dji_guid.jpg in the directory
5. Uninstall the application and reinstall it 
6. In that same directory they will see another jpg in the dji folder dji_guid(x).jpg  where x is a number
7. Repeat step 5 until the app crashes due to the files conflicting with each other. Usually takes about 30 times to reproduce the error. 

App crash error:

2022-03-02 11:27:03.199 27772-28464/com.mapware.fly E/AndroidRuntime: FATAL EXCEPTION: UrgentThreadPool#1
    Process: com.mapware.fly, PID: 27772
    java.lang.ExceptionInInitializerError
        at dji.internal.analytics.DJIAnalyticsEngine$ddf.fdd(Unknown Source:0)
        at dji.internal.analytics.DJIAnalyticsEngine.getInstance(Unknown Source:0)
        at dji.sdk.sdkmanager.DJISDKManager.initParams(Unknown Source:27)
        at dji.sdk.sdkmanager.DJISDKManager.initSDKManager(Unknown Source:12)
        at dji.sdk.sdkmanager.DJISDKManager.registerApp(Unknown Source:37)
        at dji.sdk.sdkmanager.DJISDKManager.access$1000(Unknown Source:0)
        at dji.sdk.sdkmanager.DJISDKManager$8$1.onDownloadSuccess(Unknown Source:8)
        at dji.internal.jhg.fdd.fdd(Unknown Source:19)
        at dji.sdk.sdkmanager.DJISDKManager$8.run(Unknown Source:37)
        at dji.sdksharedlib.dgh.gfd$fdd.run(Unknown Source:5)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.IllegalStateException: Failed to build unique file: /storage/emulated/0/Pictures/dji/dji-guid.jpg owner_package_name=com.mapware.fly _display_name=dji-guid.jpg mime_type=image/jpeg _data=/storage/emulated/0/Pictures/dji/dji-guid.jpg relative_path=Pictures/dji/
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2393)
        at android.os.Parcel.createException(Parcel.java:2369)
        at android.os.Parcel.readException(Parcel.java:2352)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
        at android.content.ContentProviderProxy.insert(ContentProviderNative.java:549)
        at android.content.ContentResolver.insert(ContentResolver.java:2159)
        at android.content.ContentResolver.insert(ContentResolver.java:2121)
        at dji.internal.analytics.helper.GuidUtil.setToMediaStore(Unknown Source:40)
        at dji.internal.analytics.helper.GuidUtil.updateFile(Unknown Source:6)
        at dji.internal.analytics.helper.GuidUtil.getFromSP(Unknown Source:12)
        at dji.internal.analytics.helper.GuidUtil.createGUID(Unknown Source:10)
        at dji.internal.analytics.helper.DJIAnalyticsSession.getInstallId(Unknown Source:8)
        at dji.internal.analytics.helper.DJIAnalyticsHeaderManager.getInstallId(Unknown Source:0)
        at dji.internal.analytics.helper.DJIAnalyticsHeaderManager.initHeaders(Unknown Source:0)
        at dji.internal.analytics.helper.DJIAnalyticsHeaderManager.init(Unknown Source:3)
        at dji.internal.analytics.DJIAnalyticsEngine.<init>(Unknown Source:79)
        at dji.internal.analytics.DJIAnalyticsEngine.<init>(Unknown Source:0)
        at dji.internal.analytics.DJIAnalyticsEngine$ddf.<clinit>(Unknown Source:3)
        at dji.internal.analytics.DJIAnalyticsEngine$ddf.fdd(Unknown Source:0) 
        at dji.internal.analytics.DJIAnalyticsEngine.getInstance(Unknown Source:0) 
        at dji.sdk.sdkmanager.DJISDKManager.initParams(Unknown Source:27) 
        at dji.sdk.sdkmanager.DJISDKManager.initSDKManager(Unknown Source:12) 
        at dji.sdk.sdkmanager.DJISDKManager.registerApp(Unknown Source:37) 
        at dji.sdk.sdkmanager.DJISDKManager.access$1000(Unknown Source:0) 
        at dji.sdk.sdkmanager.DJISDKManager$8$1.onDownloadSuccess(Unknown Source:8) 
        at dji.internal.jhg.fdd.fdd(Unknown Source:19) 
        at dji.sdk.sdkmanager.DJISDKManager$8.run(Unknown Source:37) 
        at dji.sdksharedlib.dgh.gfd$fdd.run(Unknown Source:5) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923)

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/61681'>Zendesk ticket #61681</a>:<br><br>We have fixed this bug on 4.16.1 version; it will be released next week.
<br><p><em><small>°°°</small></em></p>
