### ISSUE TITLE
BUG App crashes with "Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent" when using compileSdkVersion 31

### ISSUE THREAD

**Issue by ShakedDovrat** [dji-sdk/Mobile-SDK-Android#1152]
The SDK seems to cause a crash after upgrading compileSdkVersion from 30 to 31. I need version 31 because my app uses Android's CameraX which requires version 31 or more.
When searching the issue online, it seems that a (small) fix is required on the SDK side.
It happends when I start the app w/o giving it permission to use DJI's controller (USB device).

Full crash dump:
```
=====	Device Info	=====
manufacture:samsung
product:b0qxxx
model:SM-S908E
version:SP1A.210812.016.S908EXXU2AVE4
android version:12
build num:
build name:
sdk version:31
=====	App Info	=====
versionCode:0
versionName:null
=====	Crash	=====
java.lang.RuntimeException: Failed to call observer method
	at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:226)
	at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:194)
	at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:185)
	at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:37)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361)
	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:188)
	at dji.sdk.sdkmanager.DJISDKManager.lambda$initParams$1(Unknown Source:10)
	at dji.sdk.sdkmanager.DJISDKManager$$Lambda$1.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: java.lang.IllegalArgumentException: com.appname.test: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:673)
	at android.app.PendingIntent.getBroadcast(PendingIntent.java:660)
	at dji.midware.usb.P3.DJIUsbAccessoryReceiver.fdd(Unknown Source:10)
	at dji.midware.usb.P3.DJIUsbAccessoryReceiver.fdd(Unknown Source:146)
	at dji.midware.usb.P3.DJIUsbAccessoryReceiver.fdd(Unknown Source:64)
	at dji.midware.usb.P3.DJIUsbAccessoryReceiver.nhf(Unknown Source:5)
	at dji.midware.usb.P3.UsbAccessoryService.dgh(Unknown Source:5)
	at dji.sdk.sdkmanager.DJISDKManager$DJILifecycleListener.onMoveToForeground(Unknown Source:10)
	at java.lang.reflect.Method.invoke(Native Method)
	at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:216)
	... 15 more
java.lang.IllegalArgumentException: com.appname.test: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:673)
	at android.app.PendingIntent.getBroadcast(PendingIntent.java:660)
	at dji.midware.usb.P3.DJIUsbAccessoryReceiver.fdd(Unknown Source:10)
	at dji.midware.usb.P3.DJIUsbAccessoryReceiver.fdd(Unknown Source:146)
	at dji.midware.usb.P3.DJIUsbAccessoryReceiver.fdd(Unknown Source:64)
	at dji.midware.usb.P3.DJIUsbAccessoryReceiver.nhf(Unknown Source:5)
	at dji.midware.usb.P3.UsbAccessoryService.dgh(Unknown Source:5)
	at dji.sdk.sdkmanager.DJISDKManager$DJILifecycleListener.onMoveToForeground(Unknown Source:10)
	at java.lang.reflect.Method.invoke(Native Method)
	at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:216)
	at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:194)
	at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:185)
	at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:37)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361)
	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:188)
	at dji.sdk.sdkmanager.DJISDKManager.lambda$initParams$1(Unknown Source:10)
	at dji.sdk.sdkmanager.DJISDKManager$$Lambda$1.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

=======Thread info======Crash name:java.lang.RuntimeException: Failed to call observer method
 Cause is:java.lang.IllegalArgumentException: com.appname.test: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
 Thread name is:main 2
 Thread count is:115
 Fd count is:203
 
Name:	om.appname.test
Umask:	0077
State:	R (running)
Tgid:	12313
Ngid:	0
Pid:	12313
PPid:	1356
TracerPid:	0
Uid:	10350	10350	10350	10350
Gid:	10350	10350	10350	10350
FDSize:	256
Groups:	3001 3002 3003 9997 20350 50350 
VmPeak:	19529072 kB
VmSize:	19529060 kB
VmLck:	      72 kB
VmPin:	       0 kB
VmHWM:	  303180 kB
VmRSS:	  303180 kB
RssAnon:	  189764 kB
RssFile:	  111368 kB
RssShmem:	    2048 kB
VmData:	 2077552 kB
VmStk:	    8192 kB
VmExe:	       8 kB
VmLib:	  178460 kB
VmPTE:	    2300 kB
VmSwap:	   27820 kB
CoreDumping:	0
THP_enabled:	1
Threads:	146
SigQ:	0/37977
SigPnd:	0000000000000000
ShdPnd:	0000000000000000
SigBlk:	0000000080001204
SigIgn:	0000000000000001
SigCgt:	0000006e400086f8
CapInh:	0000000000000000
CapPrm:	0000000000000000
CapEff:	0000000000000000
CapBnd:	0000000000000000
CapAmb:	0000000000000000
NoNewPrivs:	0
Seccomp:	2
Seccomp_filters:	1
Speculation_Store_Bypass:	thread vulnerable
Cpus_allowed:	ff
Cpus_allowed_list:	0-7
Mems_allowed:	1
Mems_allowed_list:	0
voluntary_ctxt_switches:	814
nonvoluntary_ctxt_switches:	330

============Start dump thread info============
total =115
线程号：38 = Signal Catcher
线程号：40 = HeapTaskDaemon
线程号：41 = ReferenceQueueDaemon
线程号：42 = FinalizerDaemon
线程号：43 = FinalizerWatchdogDaemon
线程号：46 = Jit thread pool worker thread 0
线程号：49 = Profile Saver
线程号：205 = process reaper
线程号：2 = main
线程号：45 = Binder:12313_1
线程号：47 = Binder:12313_2
线程号：48 = Binder:12313_3
线程号：52 = queued-work-looper-data
线程号：56 = Crashlytics Exception Handler1
线程号：58 = com.google.firebase.crashlytics.startup1
线程号：61 = awaitEvenIfOnMainThread task continuation executor1
线程号：63 = pool-6-thread-1
线程号：66 = WM.task-1
线程号：67 = WM.task-2
线程号：78 = pool-8-thread-1
线程号：81 = queued-work-looper
线程号：82 = pool-8-thread-2
线程号：83 = pool-8-thread-3
线程号：86 = Okio Watchdog
线程号：87 = Binder:12313_4
线程号：88 = RenderThread
线程号：89 = DefaultDispatcher-worker-1
线程号：90 = DefaultDispatcher-worker-2
线程号：91 = DefaultDispatcher-worker-3
线程号：92 = glide-active-resources
线程号：93 = RxCachedWorkerPoolEvictor-1
线程号：94 = RxComputationThreadPool-1
线程号：95 = RxComputationThreadPool-2
线程号：96 = dji_background_thread
线程号：97 = Timer-0
线程号：98 = Timer-1
线程号：99 = LogHandlerThread
线程号：100 = SingleBackgroundLooper
线程号：101 = UrgentThreadPool#1
线程号：102 = dji_sdk_callback_thread
线程号：103 = hwuiTask0
线程号：104 = hwuiTask1
线程号：106 = UrgentThreadPool#2
线程号：107 = CommonThreadPool#1
线程号：108 = midware_background_thread
线程号：109 = DataBaseProcessor
线程号：110 = ThreadPoolUtil:handlerThread
线程号：111 = DJIVideoPackManager-data-parser
线程号：112 = xss-data-parser
线程号：113 = CommonThreadPool#2
线程号：114 = CommonThreadPool#3
线程号：115 = SwUdpService timer
线程号：116 = parse_package
线程号：121 = Timer-2
线程号：122 = file_download_thread
线程号：123 = Timer-3
线程号：126 = Timer-4
线程号：127 = parse_package
线程号：128 = file_download_thread
线程号：131 = Timer-5
线程号：133 = ddf-data-parser
线程号：135 = nhf timer
线程号：137 = P3CCameraService timer
线程号：139 = Thread-19
线程号：140 = Thread-20
线程号：141 = Thread-21
线程号：142 = Thread-22
线程号：143 = Thread-23
线程号：144 = Thread-24
线程号：145 = RxComputationThreadPool-3
线程号：146 = RxComputationThreadPool-4
线程号：147 = RxComputationThreadPool-5
线程号：148 = RxComputationThreadPool-6
线程号：149 = RxComputationThreadPool-7
线程号：150 = RxComputationThreadPool-8
线程号：151 = RxSchedulerPurge-1
线程号：152 = RxCachedWorkerPoolEvictor-1
线程号：153 = RxComputationThreadPool-1
线程号：154 = RxComputationThreadPool-2
线程号：155 = RxComputationThreadPool-3
线程号：156 = RxComputationThreadPool-4
线程号：157 = RxComputationThreadPool-5
线程号：158 = RxComputationThreadPool-6
线程号：159 = RxComputationThreadPool-7
线程号：160 = RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@e5533f9
线程号：161 = CommonThreadPool#4
线程号：162 = CommonThreadPool#5
线程号：163 = thread_link_mode
线程号：167 = CommonThreadPool#6
线程号：171 = CommonThreadPool#7
线程号：174 = OkHttp https://mydjiflight.dji.com/...
线程号：175 = OkHttp https://mydjiflight.dji.com/...
线程号：176 = RxCachedThreadScheduler-1
线程号：177 = RxCachedThreadScheduler-2
线程号：178 = RxCachedThreadScheduler-3
线程号：179 = battery validating thread
线程号：180 = OkHttp https://statistical-report.djiservice.org/...
线程号：182 = CommonThreadPool#8
线程号：190 = OkHttp https://flysafe-api.dji.com/...
线程号：191 = OkHttp https://flysafe-api.dji.com/...
线程号：196 = OkHttp https://flysafe-api.dji.com/...
线程号：197 = OkHttp https://flysafe-api.dji.com/...
线程号：199 = OkHttp https://flysafe-api.dji.com/...
线程号：200 = geo-sync-file
线程号：201 = UrgentThreadPool#3
线程号：202 = UrgentThreadPool#4
线程号：203 = UrgentThreadPool#5
线程号：204 = UrgentThreadPool#6
线程号：208 = DJI Log #1
线程号：213 = CommonThreadPool#9
线程号：223 = OkHttp https://mydjiflight.dji.com/...
线程号：224 = pool-14-thread-1
线程号：225 = SDKAgentManager
线程号：235 = DJI Log #2
线程号：239 = OkHttp https://mydjiflight.dji.com/...
============end of dump ==========
```

Please help

**Comment by DJI-William** [comment]
Our sample in this github also targets sdk version 31, have you tried our sample and what is the outcome? You can check our [build.gradle file](https://github.com/dji-sdk/Mobile-SDK-Android/blob/master/Sample%20Code/app/build.gradle).
