### ISSUE TITLE
OSMO+ - if DJI crash if wifi connected prior to starting the app

### ISSUE THREAD

**Issue by Djacob502** [dji-sdk/Mobile-SDK-Android#117]
When starting an app with OSMO+ and with the OSMO+ wifi already connected, the following DJI uncaught exception 4 is thrown: 

06-04 10:45:57.096 17926-17971/ E/DJICrashHandler: uncaughtException 4
06-04 10:45:57.097 17926-17971/ E/AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
 Process: PID: 17926
 java.lang.NullPointerException: Attempt to invoke virtual method 'dji.midware.data.config.P3.ProductType dji.midware.data.manager.P3.DJIProductManager.c()' on a null object reference at dji.midware.data.model.P3.DataSpecialControl.useNewControl(Unknown Source)
 at dji.midware.data.model.P3.DataSpecialControl.getInstance(Unknown Source)
 at dji.midware.data.manager.P3.h.a(Unknown Source)
 at dji.midware.data.manager.P3.i.a(Unknown Source)
 at dji.midware.data.manager.P3.i.c(Unknown Source)
 at dji.midware.data.manager.P3.i$2.run(Unknown Source)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)

If I keep restarting the app, then occasionally the app will run without error at startup. Perhaps 2 in 10 times the app will restart without error so this error is intermittent. 

I'm using the 4.10 sdk and the standard boiler plate code. This error did not occur when using the 3.* sdk. 

If the OSMO+ wifi is not connected when starting the program, then the program starts without error. Next when the OSMO+ wifi is connected, then the program connnects without error. 

This is on a Nvidia k1 shield running android 7.0. Using android studio 2.3.2

**Comment by Djacob502** [comment]
This issue is still present in sdk 4.1.1 
I noticed that there was a release note stating the startup issue with DjiSdkManager was corrected but I'm still getting the same crash with the latest release.

**Comment by Djacob502** [comment]
This is fixed in 4.2 Thanks!

**Comment by akorosi** [comment]
This issue still present in sdk 4.3.2

**Comment by talobin** [comment]
@akorosi Please include stack trace for your crash

**Comment by jumli** [comment]
11-09 11:47:15.917 21081-21081/com.okolo.okolo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.okolo.okolo, PID: 21081
                                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'dji.midware.data.config.P3.ProductType dji.midware.data.manager.P3.DJIProductManager.c()' on a null object reference
                                                                     at dji.midware.media.e.c.b.a(Unknown Source)
                                                                     at dji.midware.media.e.c.b.a(Unknown Source)
                                                                     at dji.midware.media.e.c.b.a(Unknown Source)
                                                                     at dji.sdk.codec.DJICodecManager.<init>(Unknown Source)
                                                                     at dji.sdk.codec.DJICodecManager.<init>(Unknown Source)
                                                                     at com.okolo.app.Activities.MainActivity.onSurfaceTextureAvailable(MainActivity.java:238)
                                                                     at android.view.TextureView.getHardwareLayer(TextureView.java:368)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:15246)
                                                                     at android.view.View.draw(View.java:16042)
                                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3615)
                                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3405)
                                                                     at android.view.View.draw(View.java:16275)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:15269)
                                                                     at android.view.View.draw(View.java:16042)
                                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3615)
                                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3405)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:15264)
                                                                     at android.view.View.draw(View.java:16042)
                                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3615)
                                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3405)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:15264)
                                                                     at android.view.View.draw(View.java:16042)
                                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3615)
                                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3405)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:15264)
                                                                     at android.view.View.draw(View.java:16042)
                                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3615)
                                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3405)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:15264)
                                                                     at android.view.View.draw(View.java:16042)
                                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3615)
                                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3405)
                                                                     at android.view.View.draw(View.java:16275)
                                                                     at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2740)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:15269)
                                                                     at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:295)
                                                                     at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:301)
                                                                     at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:336)
                                                                     at android.view.ViewRootImpl.draw(ViewRootImpl.java:2760)
                                                                     at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2564)
                                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2164)
                                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1174)
                                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6241)
                                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:873)
                                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:676)
                                                                     at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:859)
                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:168)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5845)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)

**Comment by windless** [comment]
check this: #177

**Comment by talobin** [comment]
Duplicate with 
https://github.com/dji-sdk/Mobile-SDK-Android/issues/177
