### ISSUE TITLE
java.lang.VerifyError: Verifier rejected class dji.sdk.sdkmanager

### ISSUE THREAD

**Issue by Needrom** [dji-sdk/Mobile-SDK-Android#1172]
LogCat
```
2022-08-29 14:38:13.885 5728-5757/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.example.androiddjiemptytest, PID: 5728
    java.lang.VerifyError: Verifier rejected class dji.sdk.sdkmanager.DJISDKManager: void dji.sdk.sdkmanager.DJISDKManager.<init>() failed to verify: void dji.sdk.sdkmanager.DJISDKManager.<init>(): [0x0] Constructor returning without calling superclass constructor (declaration of 'dji.sdk.sdkmanager.DJISDKManager' appears in /data/data/com.example.androiddjiemptytest/code_cache/.overlay/base.apk/classes.dex)
        at dji.sdk.sdkmanager.DJISDKManager.getInstance(Unknown Source:0)
        at com.example.androiddjiemptytest.MainActivity$1.run(MainActivity.java:137)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

I had seen all the issue about this problem.Not any means is the solution about this question.
All I just know a bunch of empty function in class SDKManager but I could do nothing but ask you for help how to fix '''Constructor returning without calling superclass constructor'''
the device I use is OPPO K3 on Android 11.

**Comment by DJI-William** [comment]
The tutorial is out of date, please don't follow the guide. I suggest you just try this Sample with the latest Android 4.16.2 now.

**Comment by Needrom** [comment]
> The tutorial is out of date, please don't follow the guide. I suggest you just try this Sample with the latest Android 4.16.2 now.

But how could I just merge it into the other project not build on it.

**Comment by DJI-William** [comment]
> > The tutorial is out of date, please don't follow the guide. I suggest you just try this Sample with the latest Android 4.16.2 now.
> 
> But how could I just merge it into the other project not build on it.

I am sorry for the out of date of tutorials. I know this is very hard, you have to compare the tutorials and the Sample to find out a difference and write your own project. Which aircraft are you using? If you are using M300RTK or M30 series, we suggest you switch to MSDK V5.
