### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "dji.sdk.sdkmanager.DJISDKManager$SDKManagerCallback"

### ISSUE THREAD

**Issue by gg-deploy-dd** [dji-sdk/Mobile-SDK-Android#1203]
Our users are seeing crashes with the following stacktrace.
Android dji sdk version - 4.16.4 but this issue has existed for a long time and on other versions as well

java.lang.ClassNotFoundException: Didn't find class "dji.sdk.sdkmanager.DJISDKManager$SDKManagerCallback" on path: DexPathList[[zip file "/system/framework/com.android.future.usb.accessory.jar", zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.dronedeploy.beta-1/base.apk"],nativeLibraryDirectories=[/data/app/com.dronedeploy.beta-1/lib/arm, /data/app/com.dronedeploy.beta-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /data/downloads, /data/priv-downloads]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    at com.dronedeploy.beta.MApplication.attachBaseContext(MApplication.java:20)
    at android.app.Application.attach(Application.java:189)
    at android.app.Instrumentation.newApplication(Instrumentation.java:1037)
    at android.app.Instrumentation.newApplication(Instrumentation.java:1021)
    at android.app.LoadedApk.makeApplication(LoadedApk.java:796)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5392)
    at android.app.ActivityThread.-wrap2(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1548)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6138)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
java.lang.NoClassDefFoundError: Failed resolution of: Ldji/sdk/sdkmanager/DJISDKManager$SDKManagerCallback;
    at com.dronedeploy.beta.MApplication.attachBaseContext(MApplication.java:20)
    at android.app.Application.attach(Application.java:189)
    at android.app.Instrumentation.newApplication(Instrumentation.java:1037)
    at android.app.Instrumentation.newApplication(Instrumentation.java:1021)
    at android.app.LoadedApk.makeApplication(LoadedApk.java:796)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5392)
    at android.app.ActivityThread.-wrap2(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1548)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6138)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

**Comment by DJI-William** [comment]
A known issue, currently people cannot use 32 bit architecture(armeabi-v7a) mobile device after 4.16.2. We we will fix this in 4.16.5.

**Comment by jaredmassey** [comment]
> A known issue, currently people cannot use 32 bit architecture(armeabi-v7a) mobile device after 4.16.2. We we will fix this in 4.16.5.

Is this release ( 4.16.5 ) still planned? Is there an ETA on it? There does not seem to have been much recent activity on the project.
