### ISSUE TITLE
Crash on tap "Register APP" in official sample app on Samsung SM-M115F

### ISSUE THREAD

**Issue by IlnazMan** [dji-sdk/Mobile-SDK-Android#1222]
The official sample app of [Mobile-SDK-Android](https://github.com/dji-sdk/Mobile-SDK-Android) is crashed on Samsung SM-M115F on tap to button "Register APP" (on calling the DJISDKManager.getInstance().registerApp(...)).

**The crash logs:**
18:02:51.365   704-704   audit                   auditd                               E  type=1400 audit(1680102171.358:12993): avc:  denied  { execmod } for  pid=6042 comm=4173796E635461736B202331 path="/data/app/~~VQEa6j2Rm4YS_EPy5KEYhg==/com.dji.sdk.sample-zD_pQLRzWMUWtpin1qDCTw==/lib/arm/libDJISDKLOGJNI.so" dev="mmcblk0p78" ino=56294 scontext=u:r:untrusted_app:s0:c22,c257,c512,c768 tcontext=u:object_r:apk_data_file:s0 tclass=file permissive=0 SEPF_SM-M115F_11_0004 audit_filtered
2023-03-29 18:02:51.444  6042-7894  DJISDKManager           com.dji.sdk.sample                   E  Failed to load LDM Plus license file /storage/emulated/0/Android/data/com.dji.sdk.sample/files/DJI/com.dji.sdk.sample.dlf: open failed: ENOENT (No such file or directory)
2023-03-29 

The DJI MSDK version is 4.16.4 or 4.16.3. In 4.16.2 registration is ended successful.
Android version is 11. 

**Please help to solve the problem.**

**The full logs:**
023-03-29 18:02:51.174  6042-6042  ViewRootIm...nActivity] com.dji.sdk.sample                   I  ViewPostIme pointer 0
2023-03-29 18:02:51.280  6042-6042  ViewRootIm...nActivity] com.dji.sdk.sample                   I  ViewPostIme pointer 1
2023-03-29 18:02:51.304  6042-6042  Compatibil...geReporter com.dji.sdk.sample                   D  Compat change id reported: 147798919; UID 10278; state: ENABLED
2023-03-29 18:02:51.312  6042-6042  Toast                   com.dji.sdk.sample                   D  show: caller = com.dji.sdk.sample.internal.utils.ToastUtils.showToast:47 
2023-03-29 18:02:51.312  6042-6042  Toast                   com.dji.sdk.sample                   I  show: focusDisplayId = 0, isFocusInDesktop = false mCustomDisplayId=-1 isDexDualMode=false
2023-03-29 18:02:51.313  6042-6042  Toast                   com.dji.sdk.sample                   I  show: isActivityContext = false
2023-03-29 18:02:51.365   704-704   audit                   auditd                               E  type=1400 audit(1680102171.358:12993): avc:  denied  { execmod } for  pid=6042 comm=4173796E635461736B202331 path="/data/app/~~VQEa6j2Rm4YS_EPy5KEYhg==/com.dji.sdk.sample-zD_pQLRzWMUWtpin1qDCTw==/lib/arm/libDJISDKLOGJNI.so" dev="mmcblk0p78" ino=56294 scontext=u:r:untrusted_app:s0:c22,c257,c512,c768 tcontext=u:object_r:apk_data_file:s0 tclass=file permissive=0 SEPF_SM-M115F_11_0004 audit_filtered
2023-03-29 18:02:51.444  6042-7894  DJISDKManager           com.dji.sdk.sample                   E  Failed to load LDM Plus license file /storage/emulated/0/Android/data/com.dji.sdk.sample/files/DJI/com.dji.sdk.sample.dlf: open failed: ENOENT (No such file or directory)
2023-03-29 18:02:51.516  6042-7898  .dji.sdk.sampl          com.dji.sdk.sample                   W  Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (greylist,core-platform-api, reflection, allowed)
2023-03-29 18:02:51.516  6042-7898  .dji.sdk.sampl          com.dji.sdk.sample                   W  Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (greylist,core-platform-api, reflection, allowed)
2023-03-29 18:02:51.516  6042-7898  .dji.sdk.sampl          com.dji.sdk.sample                   W  Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (greylist,core-platform-api, reflection, allowed)
2023-03-29 18:02:51.939   704-704   audit                   auditd                               E  type=1400 audit(1680102171.928:12994): avc:  denied  { execmod } for  pid=6042 comm="CommonThreadPoo" path="/data/app/~~VQEa6j2Rm4YS_EPy5KEYhg==/com.dji.sdk.sample-zD_pQLRzWMUWtpin1qDCTw==/lib/arm/libGroudStation.so" dev="mmcblk0p78" ino=56306 scontext=u:r:untrusted_app:s0:c22,c257,c512,c768 tcontext=u:object_r:apk_data_file:s0 tclass=file permissive=0 SEPF_SM-M115F_11_0004 audit_filtered
2023-03-29 18:02:51.939  6042-7902  onLoad                  com.dji.sdk.sample                   I  loaded onLoad.cpp :JNI_OnLoad() go to end
2023-03-29 18:02:51.940  6042-7902  libc                    com.dji.sdk.sample                   A  Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0xabf500f4 in tid 7902 (CommonThreadPoo), pid 6042 (.dji.sdk.sample)
2023-03-29 18:02:52.084  7931-7931  DEBUG                   pid-7931                             A  pid: 6042, tid: 7902, name: CommonThreadPoo  >>> com.dji.sdk.sample <<<
2023-03-29 18:02:52.085  7931-7931  DEBUG                   pid-7931                             A        #00 pc 000040f4  /data/app/~~VQEa6j2Rm4YS_EPy5KEYhg==/com.dji.sdk.sample-zD_pQLRzWMUWtpin1qDCTw==/lib/arm/libGroudStation.so (offset 0x4000)
2023-03-29 18:02:52.390  6042-7898  System.err              com.dji.sdk.sample                   W  java.lang.NoSuchMethodException: dji.midware.data.model.P3.DataGetProductInfoFromPayload.getInstance []
2023-03-29 18:02:52.391  6042-7898  System.err              com.dji.sdk.sample                   W  	at java.lang.Class.getMethod(Class.java:2072)
2023-03-29 18:02:52.391  6042-7898  System.err              com.dji.sdk.sample                   W  	at java.lang.Class.getMethod(Class.java:1693)
2023-03-29 18:02:52.391  6042-7898  System.err              com.dji.sdk.sample                   W  	at dji.midware.data.config.P3.nhf.getDataBaseInstRefl(Unknown Source:14)
2023-03-29 18:02:52.391  6042-7898  System.err              com.dji.sdk.sample                   W  	at dji.midware.data.config.P3.CmdIdPayloadSDK$CmdIdType.<init>(Unknown Source:12)
2023-03-29 18:02:52.391  6042-7898  System.err              com.dji.sdk.sample                   W  	at dji.midware.data.config.P3.CmdIdPayloadSDK$CmdIdType.<clinit>(Unknown Source:252)
2023-03-29 18:02:52.391  6042-7898  System.err              com.dji.sdk.sample                   W  	at dji.midware.data.config.P3.CmdIdPayloadSDK$CmdIdType.getValues(Unknown Source:0)
2023-03-29 18:02:52.391  6042-7898  System.err              com.dji.sdk.sample                   W  	at dji.midware.data.config.P3.CmdIdPayloadSDK.fdd(Unknown Source:0)
2023-03-29 18:02:52.391  6042-7898  System.err              com.dji.sdk.sample                   W  	at dji.midware.data.config.P3.fdd.<init>(Unknown Source:10)
2023-03-29 18:02:52.391  6042-7898  System.err              com.dji.sdk.sample                   W  	at dji.midware.data.config.P3.CmdIdPayloadSDK.<init>(Unknown Source:0)
2023-03-29 18:02:52.392  6042-7898  System.err              com.dji.sdk.sample                   W  	at dji.midware.data.config.P3.CmdSet.<clinit>(Unknown Source:762)
2023-03-29 18:02:52.392  6042-7898  System.err              com.dji.sdk.sample                   W  	at dji.midware.data.manager.P3.nhf.<init>(Unknown Source:97)
2023-03-29 18:02:52.392  6042-7898  System.err              com.dji.sdk.sample                   W  	at dji.midware.data.manager.P3.hjn.<init>(Unknown Source:35)
2023-03-29 18:02:52.392  6042-7898  System.err              com.dji.sdk.sample                   W  	at dji.midware.data.manager.P3.DJIVideoPackManager.<init>(Unknown Source:1)
2023-03-29 18:02:52.392  6042-7898  System.err              com.dji.sdk.sample                   W  	at dji.midware.data.manager.P3.DJIVideoPackManager.getInstance(Unknown Source:9)
2023-03-29 18:02:52.392  6042-7898  System.err              com.dji.sdk.sample                   W  	at dji.midware.link.fdd.gfd(Unknown Source:36)
2023-03-29 18:02:52.392  6042-7898  System.err              com.dji.sdk.sample                   W  	at dji.midware.link.fdd.<init>(Unknown Source:10)
2023-03-29 18:02:52.392  6042-7898  System.err              com.dji.sdk.sample                   W  	at dji.midware.link.fdd.getInstance(Unknown Source:9)
2023-03-29 18:02:52.392  6042-7898  System.err              com.dji.sdk.sample                   W  	at dji.midware.data.manager.P3.ServiceManager.ddf(Unknown Source:30)
2023-03-29 18:02:52.392  6042-7898  System.err              com.dji.sdk.sample                   W  	at dji.midware.dgh.fdd(Unknown Source:27)
2023-03-29 18:02:52.392  6042-7898  System.err              com.dji.sdk.sample                   W  	at dji.sdksharedlib.fdd.fdd(Unknown Source:6)
2023-03-29 18:02:52.392  6042-7898  System.err              com.dji.sdk.sample                   W  	at dji.sdk.sdkmanager.DJISDKManager.initParams(Unknown Source:15)
2023-03-29 18:02:52.392  6042-7898  System.err              com.dji.sdk.sample                   W  	at dji.sdk.sdkmanager.DJISDKManager.initSDKManager(Unknown Source:27)
2023-03-29 18:02:52.392  6042-7898  System.err              com.dji.sdk.sample                   W  	at dji.sdk.sdkmanager.DJISDKManager.registerApp(Unknown Source:37)
2023-03-29 18:02:52.393  6042-7898  System.err              com.dji.sdk.sample                   W  	at dji.sdk.sdkmanager.DJISDKManager.access$1400(Unknown Source:0)
2023-03-29 18:02:52.393  6042-7898  System.err              com.dji.sdk.sample                   W  	at dji.sdk.sdkmanager.DJISDKManager$8.onDownloadSuccess(Unknown Source:6)
2023-03-29 18:02:52.393  6042-7898  System.err              com.dji.sdk.sample                   W  	at dji.internal.jhg.fdd.fdd(Unknown Source:19)
2023-03-29 18:02:52.393  6042-7898  System.err              com.dji.sdk.sample                   W  	at dji.sdk.sdkmanager.DJISDKManager.lambda$registerApp$2(Unknown Source:27)
2023-03-29 18:02:52.393  6042-7898  System.err              com.dji.sdk.sample                   W  	at dji.sdk.sdkmanager.DJISDKManager$$Lambda$4.run(Unknown Source:2)
2023-03-29 18:02:52.393  6042-7898  System.err              com.dji.sdk.sample                   W  	at dji.sdksharedlib.dgh.dgh$fdd.run(Unknown Source:5)
2023-03-29 18:02:52.393  6042-7898  System.err              com.dji.sdk.sample                   W  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2023-03-29 18:02:52.393  6042-7898  System.err              com.dji.sdk.sample                   W  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2023-03-29 18:02:52.393  6042-7898  System.err              com.dji.sdk.sample                   W  	at java.lang.Thread.run(Thread.java:923)
2023-03-29 18:02:52.463  6042-7927  .dji.sdk.sampl          com.dji.sdk.sample                   W  Long monitor contention with owner UrgentThreadPool#1 (7898) at dji.midware.data.manager.P3.DJIVideoPackManager dji.midware.data.manager.P3.DJIVideoPackManager.getInstance()(:-1) waiters=0 in dji.midware.data.manager.P3.DJIVideoPackManager dji.midware.data.manager.P3.DJIVideoPackManager.getInstance() for 527ms
2023-03-29 18:02:52.493  6042-7898  DJIUsbAccessoryReceiver com.dji.sdk.sample                   E  start accessory receiver
2023-03-29 18:02:52.503  6042-7898  .dji.sdk.sampl          com.dji.sdk.sample                   W  Accessing hidden method Landroid/app/ActivityThread;->currentApplication()Landroid/app/Application; (greylist, reflection, allowed)
2023-03-29 18:02:52.514  6042-7868  DJIUsbAccessoryReceiver com.dji.sdk.sample                   E  receive action: android.hardware.usb.action.USB_STATE
2023-03-29 18:02:52.515  6042-7868  DJIUsbAccessoryReceiver com.dji.sdk.sample                   E  android.hardware.usb.action.USB_STATE: is connected
2023-03-29 18:02:52.530  6042-7938  logWrite.cpp            com.dji.sdk.sample                   D  UDT JNI_OnLoad---------------->
2023-03-29 18:02:52.530  6042-7938  logWrite.cpp            com.dji.sdk.sample                   D  UDP jniRegisterNativeMethods: jniRegisterNativeMethods
2023-03-29 18:02:52.530  6042-7938  logWrite.cpp            com.dji.sdk.sample                   D  loaded UDT :JNI_OnLoad() go to end
2023-03-29 18:02:52.567  6042-7898  BluetoothAdapter        com.dji.sdk.sample                   I  STATE_BLE_ON
2023-03-29 18:02:52.567  6042-7898  BluetoothAdapter        com.dji.sdk.sample                   I  appoCount is = 0 G/S = 2/2
2023-03-29 18:02:52.568  6042-7898  BluetoothAdapter        com.dji.sdk.sample                   W  getBluetoothLeScanner() ble not available
2023-03-29 18:02:52.591  6042-7958  Lightbridge             com.dji.sdk.sample                   E  Failed to obtain JNIEnv
2023-03-29 18:02:52.591  6042-7959  Lightbridge             com.dji.sdk.sample                   E  Failed to obtain JNIEnv
2023-03-29 18:02:52.591  6042-7961  Lightbridge             com.dji.sdk.sample                   E  Failed to obtain JNIEnv
2023-03-29 18:02:52.591  6042-7960  Lightbridge             com.dji.sdk.sample                   E  Failed to obtain JNIEnv
2023-03-29 18:02:52.592  6042-7963  Lightbridge             com.dji.sdk.sample                   E  Failed to obtain JNIEnv
2023-03-29 18:02:52.592  6042-7962  Lightbridge             com.dji.sdk.sample                   E  Failed to obtain JNIEnv
2023-03-29 18:02:52.634  6042-7945  TetheringManager        com.dji.sdk.sample                   I  registerTetheringEventCallback:com.dji.sdk.sample
2023-03-29 18:02:52.635  6042-7945  ConnectivityManager     com.dji.sdk.sample                   D  ConnectivityManager() mContext=com.dji.sdk.sample.internal.controller.DJISampleApplication@d12fd6c getOpPackageName()=com.dji.sdk.sample getBasePackageName()=com.dji.sdk.sample getPackageName()=com.dji.sdk.sample
2023-03-29 18:02:52.651  6042-7898  DJIComponentManager     com.dji.sdk.sample                   E  Service Not Connected
2023-03-29 18:02:52.651  6042-7898  DJIComponentManager     com.dji.sdk.sample                   E  Service Not Connected
2023-03-29 18:02:52.651  6042-7898  DJIComponentManager     com.dji.sdk.sample                   E  Service Not Connected
2023-03-29 18:02:53.088  6042-7898  CertificatePolicyCache  com.dji.sdk.sample                   D  Creating new instance of CertificatePolicyCache myUid: 10278 callingUid: 10278
2023-03-29 18:02:53.088  6042-7898  CertificatePolicyCache  com.dji.sdk.sample                   D  readVariables type: null userId: 0
2023-03-29 18:02:53.174  6042-6042  ViewRootIm...nActivity] com.dji.sdk.sample                   I  MSG_WINDOW_FOCUS_CHANGED 0 1
2023-03-29 18:02:53.220  6042-6042  SurfaceControl          com.dji.sdk.sample                   I  nativeRelease nativeObject s[3442597952]
2023-03-29 18:02:53.220  6042-6042  SurfaceControl          com.dji.sdk.sample                   I  nativeRelease nativeObject e[3442597952]
2023-03-29 18:02:53.220  6042-6042  SurfaceControl          com.dji.sdk.sample                   I  nativeRelease nativeObject s[3865051008]
2023-03-29 18:02:53.220  6042-6042  SurfaceControl          com.dji.sdk.sample                   I  nativeRelease nativeObject e[3865051008]
2023-03-29 18:02:53.220  6042-6042  SurfaceControl          com.dji.sdk.sample                   I  nativeRelease nativeObject s[3865050976]
2023-03-29 18:02:53.220  6042-6042  SurfaceControl          com.dji.sdk.sample                   I  nativeRelease nativeObject e[3865050976]

**Comment by DJI-William** [comment]
What is your Android version? We ony support up to Android 31.

**Comment by IlnazMan** [comment]
@DJI-William , the Android version is 11 (Api level 30)

**Comment by DJI-William** [comment]
We have noticed some Samsung devices are not working with our SDK, please try other brand smart phones.

**Comment by IlnazMan** [comment]
@DJI-William , thank you for answer. We checked in Xiaomi, DJI SRC, Samsung Galaxy Tab. In this devices registering works without any troubles.
