### ISSUE TITLE
4.1.1 DownloadWaypoint SDK Crash

### ISSUE THREAD

**Issue by marksmith1231** [dji-sdk/Mobile-SDK-Android#126]
SDK: 4.1.1
Android: 7.1.1
Device: Nexus 6
Drone: M100 1.2.0.90
Android Studio: 2.3.2

I'm trying to download a waypoint mission that is already running. According to what I've read, I believe you have to call downloadMission() and then getLoadedMission() so that the mission will be fully populated. Right now its crashing just trying to download the mission. I've verified that I am in the correct mode (EXECUTING) and a waypoint mission is currently being carried out. Any info would be great, thanks!

Crash:
```
06-27 16:09:30.484 20073-20205/com.dji.TestApp E/Event: Could not dispatch event: class dji.midware.data.model.P3.DataFlycGetPushWayPointMissionInfo to subscribing class class dji.internal.d.a.f.c
  java.lang.NullPointerException: Attempt to invoke virtual method 'dji.common.mission.waypoint.WaypointMissionFinishedAction dji.common.mission.waypoint.WaypointMission$Builder.getFinishedAction()' on a null object reference
      at dji.internal.d.a.f.c.a(Unknown Source)
      at dji.internal.d.a.f.c.onEventBackgroundThread(Unknown Source)
      at java.lang.reflect.Method.invoke(Native Method)
      at dji.thirdparty.eventbus.EventBus.invokeSubscriber(EventBus.java:569)
      at dji.thirdparty.eventbus.EventBus.postToSubscription(EventBus.java:513)
      at dji.thirdparty.eventbus.EventBus.postSingleEvent(EventBus.java:475)
      at dji.thirdparty.eventbus.EventBus.post(EventBus.java:365)
      at dji.midware.data.manager.P3.DataBase.post(Unknown Source)
      at dji.midware.data.manager.P3.DataBase.setPushRecData(Unknown Source)
      at dji.midware.data.manager.P3.DataBase.setPushRecPack(Unknown Source)
      at dji.midware.data.manager.P3.i.b(Unknown Source)
      at dji.midware.data.manager.P3.i.a(Unknown Source)
      at dji.midware.data.manager.P3.i.c(Unknown Source)
      at dji.midware.data.manager.P3.i$2.run(Unknown Source)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
      at java.lang.Thread.run(Thread.java:761)
```

Code:
```
private void downloadWaypoints(){
        WaypointMissionOperator mWaypointMissionOperator = (WaypointMissionOperator) DJISDKManager.getInstance().getMissionControl().getWaypointMissionOperator();
        
        mWaypointMissionOperator.downloadMission(new CommonCallbacks.CompletionCallback() {
            @Override
            public void onResult(DJIError djiError) {
                if (djiError == null ){
                    Log.v(TAG,"Successfully downloaded waypoint mission");
                }
                else{
                    Log.e(TAG,djiError.getDescription());
                    Log.e(TAG,"Error downloading waypoint mission");
                    return;
                }
            }
        });
}
```

**Comment by marksmith1231** [comment]
Just tried this on the new SDK version 4.2 and no longer get the error.
However, now the WaypointList has no data.
I am downloading the mission and then calling on success.
```
WaypointMissionOperator mWaypointMissionOperator = (WaypointMissionOperator) DJISDKManager.getInstance().getMissionControl().getWaypointMissionOperator();

WaypointMission mWaypointMission = mWaypointMissionOperator.getLoadedMission();
Log.e(TAG, Integer.toString(mWaypointMission.getWaypointCount())); = 16
Log.e(TAG, Integer.toString(mWaypointMission.getWaypointList().size())); = 0
```

**Comment by oliverou** [comment]
Hi @marksmith1231 , we just tested the new SDK 4.2 and try to download the mission. We found that the getWaypointCount and getWaypointList 's size show the same number. When did you call the download mission ? Did you call it when you just uploaded the mission or after the mission has started?

**Comment by marksmith1231** [comment]
After the mission has started, and is being executed.

**Comment by talobin** [comment]
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!

**Comment by ageofish** [comment]
Still seeing this in 4.3.2, can someone regression test this?
