### ISSUE TITLE
Crashes app sometimes when disconnecting from remote controller

### ISSUE THREAD

**Issue by kwong93** [dji-sdk/Mobile-SDK-Android#138]
-  Description of the issue.

App crashes sometimes when disconnecting cable from the device.

-  Steps to reproduce the bug or crash issues(It would be great if you can provide this)

Follow the UI library tutorial, have the screen up with the first person view, status bar etc.

Disconnect the cable, and a crash will sometimes follow.

-  Crash logs (If you can find it, it would be very helpful)

```
E/AndroidRuntime: FATAL EXCEPTION: SingleBackgroundLooper
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object dji.sdksharedlib.store.DJISDKCacheParamValue.getData()' on a null object reference
	at dji.sdk.realname.aircraftbinding.a.n(Unknown Source)
	at dji.sdk.realname.aircraftbinding.a.h(Unknown Source)
	at dji.sdk.realname.aircraftbinding.a.q(Unknown Source)
	at dji.sdk.realname.aircraftbinding.a.b(Unknown Source)
	at dji.sdk.realname.aircraftbinding.a$1.onValueChange(Unknown Source)
	at dji.sdksharedlib.listener.DJISDKCacheListenerLayer$ValueChangeRunnable.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:158)
	at android.os.HandlerThread.run(HandlerThread.java:61)

```
-  DJI Android SDK version you are using (Like Android SDK 3.4, etc)
4.2.1
https://github.com/dji-sdk/Mobile-UILibrary-Android/tree/master/libs
-  DJI Product you are using (Like Phantom 4, Mavic Pro, etc)
`
PHANTOM 4 PRO`

-  Android system version you are using (Like Android 6.0.1, Android 5.1.1, etc)
`Android 6.0.1`
-  Android device you are using (Like Samsung Galaxy Note 5, Nexus 5, etc)
`Samsung Galaxy S7`
-  Android Studio version you are using (Like Android Studio 2.2, etc)
`Android Studio 2.3.3`

**Comment by talobin** [comment]
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!
