### ISSUE TITLE
java.lang.NoSuchMethodError: No static method lambda$addListener

### ISSUE THREAD

**Issue by jayakrishnan1236** [dji-sdk/Mobile-SDK-Android#140]
Doing this after registration

```
void addDjiCallbacks() {
        Aircraft aircraft = getAircraft();
        if (aircraft != null && aircraft.getModel() != Model.UNKNOWN_AIRCRAFT) {
            aircraft.getBattery().setStateCallback(djiCallbackCollection.getBatteryCallback());
            aircraft.getFlightController().setStateCallback(djiCallbackCollection.getFlightCallback());
            Camera camera = getCamera();
            if (camera != null) {
                camera.setMediaFileCallback(djiCallbackCollection.getMediaCallback());
            }
            VideoFeeder.getInstance().getVideoFeeds().get(0).setCallback(djiCallbackCollection.getVideoDataCallback());
            getWaypointMissionOperator().addListener(djiCallbackCollection.getMissionOperatorListener());
        }
    }
```
to load mission
```
for (int i = 0; i < inputPoints.size(); i++) {
                        waypoints.add(new Waypoint(inputPoints.get(i).latitude
                                , inputPoints.get(i).longitude, (float) data.getAltitude()));
                    }

                    WaypointMissionFinishedAction mFinishedAction = WaypointMissionFinishedAction.GO_HOME;
                    WaypointMissionHeadingMode mHeadingMode = WaypointMissionHeadingMode.AUTO;

                    WaypointMission.Builder waypointMissionBuilder
                            = new WaypointMission.Builder()
                            .finishedAction(mFinishedAction)
                            .headingMode(mHeadingMode)
                            .autoFlightSpeed(speed)
                            .maxFlightSpeed(speed)
                            .flightPathMode(WaypointMissionFlightPathMode.NORMAL)
                            .waypointList(waypoints)
                            .waypointCount(waypoints.size())
                            .setExitMissionOnRCSignalLostEnabled(true);
                    for (int i = 0; i < waypointMissionBuilder.getWaypointList().size(); i++) {
                        waypointMissionBuilder.getWaypointList().get(i).altitude = (float) data.getAltitude();
                    }

                    waypointMissionBuilder.getWaypointList().get(0).speed = 14;

                    WaypointMission waypointMission = waypointMissionBuilder.build();

                    DJIError loadError = getWaypointMissionOperator().loadMission(waypointMission);
                    if (loadError == null) {
                        showToast("loaded mission");
                        uploadMission();
                    } else {
                        // TODO: 7/17/2017 load error
                    }
```
To upload mission

```
WaypointMissionState state = getWaypointMissionOperator().getCurrentState();
        if (state == WaypointMissionState.UPLOADING) {
            // TODO: 7/17/2017 already uploading alert
            showToast("Cannot upload state is UPLOADING");
            return;
        }
        if (state == WaypointMissionState.READY_TO_UPLOAD) {
            getWaypointMissionOperator().uploadMission(djiCallbackCollection.getUploadMissionCallback());
        } else if (state == WaypointMissionState.READY_TO_EXECUTE) {
            // TODO: 7/17/2017 in state to start Mission
            showToast("IS IN THE STATE TO EXECUTE STARTING MISSION");
            startMission();
        }
```

The `loadmission` happens fine, but when the `uploadMission` is called on `WaypointMissionOperator ` it crashs with the error

```
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
        at dji.thirdparty.rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
        Caused by: java.lang.NoSuchMethodError: No static method lambda$addListener$18(Ldji/sdk/mission/waypoint/WaypointMissionOperator;Ldji/sdk/mission/waypoint/WaypointMissionOperatorListener;Ldji/internal/d/a/f/b;)V in class Ldji/sdk/mission/waypoint/WaypointMissionOperator; or its super classes (declaration of 'dji.sdk.mission.waypoint.WaypointMissionOperator' appears in /data/app/com.sample.app-2/split_lib_dependencies_apk.apk:classes2.dex)
        at dji.sdk.mission.waypoint.WaypointMissionOperator$$Lambda$1.call(Unknown Source)
        at dji.thirdparty.rx.Observable$27.onNext(Observable.java:8474)
        at dji.thirdparty.rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
        at dji.thirdparty.rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:202)
        at dji.thirdparty.rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818)
```

I am using **Phantom 4 pro**.
devices tested : **samsung j7 prime (android 6), moto g4 plus (android 7)**
Android studio : **3.0 Canary 7**

Please correct me if i am wrong.

**Comment by jayakrishnan1236** [comment]
I tried the same the AAR instead of the API LIBRARY and the same crash happens.
```
07-24 13:15:11.912 16773-16844/? E/DJICrashHandler: uncaughtException 2
07-24 13:15:11.913 16773-17236/? E/ErrorLogger: (SDK | 2017/07/24 13:15:11)
                                                upload command given
07-24 13:15:11.914 16773-16844/? E/UsbAccessoryService: final destroy() 71
07-24 13:15:12.015 16773-16844/? E/UsbAccessoryService: final destroy() 72
07-24 13:15:12.015 16773-16844/? E/wm220: ****resetSwitchFromWifiFlag
07-24 13:15:12.015 16773-16844/? E/DJIUsbAccessoryReceiver: receiver destroySession
07-24 13:15:12.016 16773-16844/? E/UsbAccessoryService: final destroy() 73
07-24 13:15:12.016 16773-16844/? E/UsbAccessoryService: final destroy() 75
07-24 13:15:12.016 16773-16844/? E/UsbAccessoryService: final destroy() 76
07-24 13:15:12.016 16773-16844/? E/DJICrashHandler: uncaughtException 3
07-24 13:15:12.199 1662-4323/? E/LocSvc_eng: E/Calling gnss_sv_status_cb
07-24 13:15:12.216 16773-16844/? E/DJICrashHandler: uncaughtException 4
07-24 13:15:12.217 16773-16844/? E/AndroidRuntime: FATAL EXCEPTION: RxComputationThreadPool-7
                                                   Process: com.sensehawk.link, PID: 16773
                                                   java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                       at dji.thirdparty.rx.internal.schedulers.ScheduledAction.run(Unknown Source)
                                                       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                       at java.lang.Thread.run(Thread.java:761)
                                                    Caused by: java.lang.NoSuchMethodError: No static method lambda$addListener$0(Ldji/sdk/mission/waypoint/WaypointMissionOperator;Ldji/sdk/mission/waypoint/WaypointMissionOperatorListener;Ldji/internal/d/a/f/b;)V in class Ldji/sdk/mission/waypoint/WaypointMissionOperator; or its super classes (declaration of 'dji.sdk.mission.waypoint.WaypointMissionOperator' appears in /data/app/com.sensehawk.link-1/split_lib_slice_8_apk.apk)
                                                       at dji.sdk.mission.waypoint.WaypointMissionOperator$$Lambda$1.call(Unknown Source)
                                                       at dji.thirdparty.rx.Observable$27.onNext(Unknown Source)
                                                       at dji.thirdparty.rx.observers.SafeSubscriber.onNext(Unknown Source)
                                                       at dji.thirdparty.rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(Unknown Source)
                                                       at dji.thirdparty.rx.internal.schedulers.ScheduledAction.run(Unknown Source) 
                                                       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428) 
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272) 
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                       at java.lang.Thread.run(Thread.java:761) 
```

**Comment by jayakrishnan1236** [comment]
Not sure what is happening but removing this line 
```
getWaypointMissionOperator().addListener(djiCallbackCollection.getMissionOperatorListener());
```
 doesn't give me any issue. But how would i get a call back. for now i am using .


```
future = executor.scheduleAtFixedRate(new Runnable() {
                    @Override
                    public void run() {
                        try {
                            if (getDroneState() == WaypointMissionState.UPLOADING) {
                                showToast("uploading...");
                            }
                        } catch (Exception e) {
                            Timber.e(e);
                        }
                    }
                }, 0, 3000, TimeUnit.MILLISECONDS);

private synchronized WaypointMissionState getDroneState() {
        return getWaypointMissionOperator().getCurrentState();
    }
```

**Comment by jayakrishnan1236** [comment]
Hai I have found the issue. As I am using the Android Studio Canary 3.0 which directly supports the java 8 without any plugins(retrolamda). i have removed my plugin. which has lead me to this crash.  Now i have added the plugin retrolamda again now the SDK doesn't have any issues.

retrolambda {
  javaVersion JavaVersion.VERSION_1_6
}
