### ISSUE TITLE
Cash app when connect to P3

### ISSUE THREAD

**Issue by thucld** [dji-sdk/Mobile-SDK-Android#172]
My application crashed when connected to Phantom 3, and I got the log as 
`
                                                                            java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
                                                                                at dji.thirdparty.v3.eventbus.EventBus.postSingleEvent(EventBus.java:363)
                                                                                at dji.thirdparty.v3.eventbus.EventBus.post(EventBus.java:251)
                                                                                at dji.midware.link.a.a(Unknown Source)
                                                                                at dji.midware.link.a.a(Unknown Source)
                                                                                at dji.midware.sockets.P3.e.onConnect(Unknown Source)
                                                                                at dji.midware.sockets.P3.a.onConnect(Unknown Source)
                                                                                at dji.midware.sockets.b.i$1.run(Unknown Source)
                                                                                at android.os.Handler.handleCallback(Handler.java:815)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                                at android.os.Looper.loop(Looper.java:207)
                                                                                at android.os.HandlerThread.run(HandlerThread.java:61)`

SDK ver 4.2.1
Product: DJI Phantom 3 Standard
Device: LENOVO TB3-850M - Android M

**Comment by zoemcateedji** [comment]
Could you please try to reproduce with our 4.3.2 build and let us know if it reproduces? 

https://developer.dji.com/mobile-sdk/downloads/

I double checked with the 4.3.2 sample app and didn't see anything like this.
