### ISSUE TITLE
Fatal Exception: net.sqlcipher.database.SQLiteDatabaseCorruptException: database disk image is malformed:

### ISSUE THREAD

**Issue by martindroneharmony** [dji-sdk/Mobile-SDK-Android#176]
**-  Description of the issue.**
This crash occurs in DJI SDK 4.3.2 for some of our users when executing native call:

> Fatal Exception: net.sqlcipher.database.SQLiteDatabaseCorruptException: database disk image is malformed: DELETE FROM polygon_tfr_remote_data

**-  Steps to reproduce the bug or crash issues**
Some of our users sometimes run into this crash. We never experienced it ourselves but we see in fabric that this crash occasionally occurs for our users. Here are the crash log:

**-  Crash logs:**

#0. Crashed: main: 0 0 0x0000000000000000
       at net.sqlcipher.database.SQLiteDatabase.native_execSQL(SQLiteDatabase.java)
       at net.sqlcipher.database.SQLiteDatabase.execSQL(SQLiteDatabase.java:2265)
       at dji.thirdparty.afinal.FinalDb.deleteAll(Unknown Source)
       at dji.midware.data.forbid.db.FlyfrbBaseDbManager.deleteAll(Unknown Source)
       at dji.pilot.flyforbid.c$1.a(Unknown Source)
       at dji.pilot.flyforbid.c$1.onSuccess(Unknown Source)
       at dji.thirdparty.afinal.http.HttpHandler.onProgressUpdate(Unknown Source)
       at dji.thirdparty.afinal.core.AsyncTask$InternalHandler.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

Fatal Exception: net.sqlcipher.database.SQLiteDatabaseCorruptException: database disk image is malformed: DELETE FROM polygon_tfr_remote_data
       at net.sqlcipher.database.SQLiteDatabase.native_execSQL(SQLiteDatabase.java)
       at net.sqlcipher.database.SQLiteDatabase.execSQL(SQLiteDatabase.java:2265)
       at dji.thirdparty.afinal.FinalDb.deleteAll(Unknown Source)
       at dji.midware.data.forbid.db.FlyfrbBaseDbManager.deleteAll(Unknown Source)
       at dji.pilot.flyforbid.c$1.a(Unknown Source)
       at dji.pilot.flyforbid.c$1.onSuccess(Unknown Source)
       at dji.thirdparty.afinal.http.HttpHandler.onProgressUpdate(Unknown Source)
       at dji.thirdparty.afinal.core.AsyncTask$InternalHandler.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**-  DJI Android SDK version you are using**
Android SDK 4.3.2 (but also happend on older SDK 4.2)

**-  DJI Product you are using (Like Phantom 4, Mavic Pro, etc)**
N/A (not contained in crash log, sorry)

**-  Android system version you are using (Like Android 6.0.1, Android 5.1.1, etc)**
Android 6, 7 and 8

**-  Android device you are using (Like Samsung Galaxy Note 5, Nexus 5, etc)**
Crash occurred for:
Samsung Galaxy S6
Samsung Galaxy S7
LGE Nexus 5X

**Comment by kwong93** [comment]
Anybody from DJI able to reproduce this? I'm hitting this more frequently now

**Comment by martindroneharmony** [comment]
Have not heard yet from DJI on this issue yet.

But our fabric crashlytics show that quite a few users experience crashes since SDK 4.3.2 related to their fly forbid base SQLLiteDatabase combined with missing exception wrapping by DJI.

Here another Crash log:
#0. Crashed: main: 0 0 0x0000000000000000
       at net.sqlcipher.database.SQLiteDatabase.execSQL(SQLiteDatabase.java:2262)
       at dji.thirdparty.afinal.FinalDb.deleteAll(Unknown Source)
       at dji.midware.data.forbid.db.FlyfrbBaseDbManager.deleteAll(Unknown Source)
       at dji.pilot.flyforbid.c$1.a(Unknown Source)
       at dji.pilot.flyforbid.c$1.onSuccess(Unknown Source)
       at dji.thirdparty.afinal.http.HttpHandler.onProgressUpdate(Unknown Source)
       at dji.thirdparty.afinal.core.AsyncTask$InternalHandler.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6688)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

--

Fatal Exception: java.lang.IllegalStateException: database not open
       at net.sqlcipher.database.SQLiteDatabase.execSQL(SQLiteDatabase.java:2262)
       at dji.thirdparty.afinal.FinalDb.deleteAll(Unknown Source)
       at dji.midware.data.forbid.db.FlyfrbBaseDbManager.deleteAll(Unknown Source)
       at dji.pilot.flyforbid.c$1.a(Unknown Source)
       at dji.pilot.flyforbid.c$1.onSuccess(Unknown Source)
       at dji.thirdparty.afinal.http.HttpHandler.onProgressUpdate(Unknown Source)
       at dji.thirdparty.afinal.core.AsyncTask$InternalHandler.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6688)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

#0. Crashed: main: 0 0 0x0000000000000000
       at net.sqlcipher.database.SQLiteDatabase.execSQL(SQLiteDatabase.java:2262)
       at dji.thirdparty.afinal.FinalDb.deleteAll(Unknown Source)
       at dji.midware.data.forbid.db.FlyfrbBaseDbManager.deleteAll(Unknown Source)
       at dji.pilot.flyforbid.c$1.a(Unknown Source)
       at dji.pilot.flyforbid.c$1.onSuccess(Unknown Source)
       at dji.thirdparty.afinal.http.HttpHandler.onProgressUpdate(Unknown Source)
       at dji.thirdparty.afinal.core.AsyncTask$InternalHandler.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6688)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by talobin** [comment]
@martindroneharmony 
Thank you for reporting this.
We are aware of this crash.
We are still not able to replicate this ourselves.
If you have a way to repoduce this, please let us know.

**Comment by martindroneharmony** [comment]
@talobin 
Will do, so far we can not reliably replicate the crash.

Even if you do not have the instance / scenario for replicating the issue, you could consider adding exception wrapping around native calls such as  net.sqlcipher.database.SQLiteDatabase.execSQL so that the SDK does not just crash immediately when they throw fatal exceptions.

**Comment by martindroneharmony** [comment]
Hello, 

We suspect the cause of these crashes is a race condition: It happens during application start, likely when we call DJI SDK registration. But the crashes occur only once in a while on one of our test devices, and not consistently,

This issue becomes quite serious and affects about 5% of our user base, and other developers seem to be affected by it as well judging from the github issue reports (i.e. https://github.com/dji-sdk/Mobile-SDK-Android/issues/164).

Is there an estimate of when this will be fixed? 

Thanks,
Drone Harmony

**Comment by JamesMasterman** [comment]
I agree with Drone Harmony, this looks very much like a thread issue, given the inconsistency. 

When dealing with SQLite databases, it's generally a good idea to make use of synchronized blocks or use other techniques to make interactions with the database thread safe. 

Accessing the DB from two different threads may be the cause of this crash.

**Comment by talobin** [comment]
We are still working on this issue.
Will keep you all posted.

**Comment by Djacob502** [comment]
+1 on this bug. It is quite intermittent and typically on start up.

**Comment by xxmaestroxx** [comment]
I have a little different crash after startupt, but as well by using the db.

`E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: d.v.s.d, PID: 18572
                                                                            net.sqlcipher.database.SQLiteException: no such table: polygon_tfr_remote_data: DELETE FROM polygon_tfr_remote_data
                                                                                at net.sqlcipher.database.SQLiteDatabase.native_execSQL(Native Method)
                                                                                at net.sqlcipher.database.SQLiteDatabase.execSQL(SQLiteDatabase.java:2265)
                                                                                at dji.thirdparty.afinal.FinalDb.deleteAll(Unknown Source:13)
                                                                                at dji.midware.data.forbid.db.FlyfrbBaseDbManager.deleteAll(Unknown Source:9)
                                                                                at dji.pilot.flyforbid.c$1.a(Unknown Source:65)
                                                                                at dji.pilot.flyforbid.c$1.onSuccess(Unknown Source:2)
                                                                                at dji.thirdparty.afinal.http.HttpHandler.onProgressUpdate(Unknown Source:29)
                                                                                at dji.thirdparty.afinal.core.AsyncTask$InternalHandler.handleMessage(Unknown Source:14)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                at android.os.Looper.loop(Looper.java:164)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`

**Comment by KleytonPascoal** [comment]
Hello everyone, 
In my scenery, this issue is more frequently. At moment, I work with drone M210 RTK. I thinking which this product is a good point to start the analysis this issue. Like @martindroneharmony said, this problem occurs always at starting the app.

**Comment by martindroneharmony** [comment]
Hello DJI,

Is there any progress on this issue? 5% of our daily users experience crashs due to this issue and juding by the comments above it happens to a broad user base of the Android SDK.

Thanks for an update,
Martin

**Comment by mikepschneider** [comment]
If it's an issue of wrapping calls with some code to catch the errors that could be theoretically fixed independently of DJI via aspectj patching.  I've been considering trying to set that up.  There are probably other DJI bugs that could be fixed this way.

**Comment by martindroneharmony** [comment]
Hello DJI,

Asking again... any news on the progress to fix this SEVERE bug?

Thanks for an update,
Martin

**Comment by mikepschneider** [comment]
Martin, I have heard through a back channel that this will be fixed in version 4.4 "soon"

**Comment by Djacob502** [comment]
It will be good to have this bug fixed. Thanks for the update!

**Comment by kwong93** [comment]
Any news DJI?

**Comment by mikepschneider** [comment]
Looks like DJI released 4.4 of the SDK recently.  Curious if anybody on here has noticed if this bug was addressed?    I've not yet gotten it to compile.

**Comment by Michael-DJI** [comment]
it's fixed, pls try with 4.4.0 or later version

**Comment by Djacob502** [comment]
I've been testing 4.4.0 with the CS and I have not noticed this error again.

**Comment by ChronoSheets** [comment]
I was having the same issue (confirmed by checking crash logs), so I tried to upgrade from v4.3 to v4.4.  Now my app won't run on my device and I can't debug.  Is there a good guide on how to perform the upgrade?  I had to guess because I couldn't find a decent guide - I changed my dependencies in the Gradle file.  The project is building and I can generate a signed APK fine.  When I run on my device it crashes immediately.  When I try to debug on my device I get the following error:

Error:Execution failed for task ':app:transformClassesWithInstantRunForDebug'.
> Code attribute in native or abstract methods in class file dji/sdk/gimbal/Gimbal

I was able to debug before I upgraded.  Part of my app doesn't require a connection to the aircraft (previewing photos that have been captured and download in flight sessions).

**Comment by oliverou** [comment]
Hi @ChronoSheets , please check this tutorial for the Android SDK 4.4 integration: https://developer.dji.com/mobile-sdk/documentation/application-development-workflow/workflow-integrate.html#android-studio-project-integration

**Comment by ChronoSheets** [comment]
I was hoping I could upgrade my existing project as I've done heaps so far using 4.3.2.

I was able to eventually debug and I get the following:

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.lachlanpearce.skyspheres, PID: 4756
                  java.lang.NoClassDefFoundError: Failed resolution of: Ldji/sdk/sdkmanager/DJISDKManager$SDKManagerCallback;
                      at java.lang.Class.newInstance(Native Method)
                      at android.app.Instrumentation.newApplication(Instrumentation.java:1015)
                      at android.app.Instrumentation.newApplication(Instrumentation.java:1000)
                      at android.app.LoadedApk.makeApplication(LoadedApk.java:835)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5859)
                      at android.app.ActivityThread.-wrap3(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1703)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6692)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "dji.sdk.sdkmanager.DJISDKManager$SDKManagerCallback" on path: DexPathList[[zip file "/system/framework/com.android.future.usb.accessory.jar", zip file "/data/app/com.lachlanpearce.skyspheres-1/base.apk"],nativeLibraryDirectories=[/data/app/com.lachlanpearce.skyspheres-1/lib/arm, /data/app/com.lachlanpearce.skyspheres-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                      at java.lang.Class.newInstance(Native Method) 
                      at android.app.Instrumentation.newApplication(Instrumentation.java:1015) 
                      at android.app.Instrumentation.newApplication(Instrumentation.java:1000) 
                      at android.app.LoadedApk.makeApplication(LoadedApk.java:835) 
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5859) 
                      at android.app.ActivityThread.-wrap3(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1703) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6692) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358) 
```

**Comment by Michael-DJI** [comment]
@ChronoSheets,do you have your own Application class?

**Comment by ChronoSheets** [comment]
Yes, it's based off the following guide which is for 4.3.2 (and looks like it hasn't been updated for 4.4.0 yet?):

https://developer.dji.com/mobile-sdk/documentation/android-tutorials/index.html

**Comment by ChronoSheets** [comment]
Might be something to do with this method signature?

```
private DJISDKManager.SDKManagerCallback mDJISDKManagerCallback = new DJISDKManager.SDKManagerCallback() 
```

**Comment by Michael-DJI** [comment]
@ChronoSheets ok, we are updating this page:
https://developer.dji.com/mobile-sdk/documentation/android-tutorials/index.html
pls wait for it

**Comment by Djacob502** [comment]
@ChronoSheets  - I ran into the same error as you. I ended up following the example in the DJI sample code since that was updated for v4.4.0 There are changes from 4.3.x to where all the startup code goes between the manifest, application, and mainactivity ( the activity where you capture registration/connection info).

**Comment by mikepschneider** [comment]
I get this error at runtime when trying to upgrade to 4.4.1, run with a clean build.  Any ideas?



```
12-30 17:39:49.794 29744-29744/com.dronebase.pilotapp.internal.dev E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "dji.sdk.sdkmanager.DJISDKManager" on path: DexPathList[[zip file "/data/app/com.dronebase.pilotapp.internal.dev-o5rotI3KU3CNY0xVezdW0A==/base.apk", zip file "/data/app/com.dronebase.pilotapp.internal.dev-o5rotI3KU3CNY0xVezdW0A==/split_lib_dependencies_apk.apk", zip file "/data/app/com.dronebase.pilotapp.internal.dev-o5rotI3KU3CNY0xVezdW0A==/split_lib_slice_0_apk.apk", zip file "/data/app/com.dronebase.pilotapp.internal.dev-o5rotI3KU3CNY0xVezdW0A==/split_lib_slice_1_apk.apk", zip file "/data/app/com.dronebase.pilotapp.internal.dev-o5rotI3KU3CNY0xVezdW0A==/split_lib_slice_2_apk.apk", zip file "/data/app/com.dronebase.pilotapp.internal.dev-o5rotI3KU3CNY0xVezdW0A==/split_lib_slice_3_apk.apk", zip file "/data/app/com.dronebase.pilotapp.internal.dev-o5rotI3KU3CNY0xVezdW0A==/split_lib_slice_4_apk.apk", zip file "/data/app/com.dronebase.pilotapp.internal.dev-o5rotI3KU3CNY0xVezdW0A==/split_lib_slice_5_apk.apk", zip file "/data/app/com.dronebase.pilotapp.internal.dev-o5rotI3KU3CNY0xVezdW0A==/split_lib_slice_6_apk.apk", zip file "/data/app/com.dronebase.pilotapp.internal.dev-o5rotI3KU3CNY0xVezdW0A==/split_lib_slice_7_apk.apk", zip file "/data/app/com.dronebase.pilotapp.internal.dev-o5rotI3KU3CNY0xVezdW0A==/split_lib_slice_8_apk.apk", zip file "/data/app/com.dronebase.pilotapp.internal.dev-o5rotI3KU3CNY0xVezdW0A==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.dronebase.pilotapp.internal.dev-o5rotI3KU3CNY0xVezdW0A==/lib/arm64, /data/app/com.dronebase.pilotapp.internal.dev-o5rotI3KU3CNY0xVezdW0A==/base.apk!/lib/arm64-v8a, /data/app/com.dronebase.pilotapp.internal.dev-o5rotI3KU3CNY0xVezdW0A==/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/com.dronebase.pilotapp.internal.dev-o5rotI3KU3CNY0xVezdW0A==/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/com.dronebase.pilotapp.internal.dev-o5rotI3KU3CNY0xVezdW0A==/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/com.dronebase.pilotapp.internal.dev-o5rotI3KU3CNY0xVezdW0A==/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/com.dronebase.pilotapp.internal.dev-o5rotI3KU3CNY0xVezdW0A==/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/com.dronebase.pilotapp.internal.dev-o5rotI3KU3CNY0xVezdW0A==/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/com.dronebase.pilotapp.internal.dev-o5rotI3KU3CNY0xVezdW0A==/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/com.dronebase.pilotapp.internal.dev-o5rotI3KU3CNY0xVezdW0A==/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/com.dronebase.pilotapp.internal.dev-o5rotI3KU3CNY0xVezdW0A==/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/com.dronebase.pilotapp.internal.dev-o5rotI3KU3CNY0xVezdW0A==/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/com.dronebase.pilotapp.internal.dev-o5rotI3KU3CNY0xVezdW0A==/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
                                                                                         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
                                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:312)```

**Comment by Michael-DJI** [comment]
@mikepschneider pls check if you miss following line in your Application class:
com.secneo.sdk.Helper.install(this);

**Comment by itsdebs** [comment]
After following each part of tutorial, I find that I cannot set context to the application as described here


```
public class MApplication extends Application {
    private FPVDemoApplication fpvDemoApplication;
    @Override
    protected void attachBaseContext(Context paramContext) {
        super.attachBaseContext(paramContext);
        Helper.install(MApplication.this);
        if (fpvDemoApplication == null) {
            fpvDemoApplication = new FPVDemoApplication();
            fpvDemoApplication.setContext(this);
        }
    }
    @Override
    public void onCreate() {
        super.onCreate();
        fpvDemoApplication.onCreate();
    }
}
```

I am using Target SDK 27, so I just put **Helper.install(this)** in my onCreate() method of my Application class. Still not able to run the app on Marshmallow. It's running in API 25(7.1.1 Nougat)
