### ISSUE TITLE
Registration failed in Android SDK Sample App

### ISSUE THREAD

**Issue by amirfarazmand** [dji-sdk/Mobile-SDK-Android#195]
I simply downloaded latest repository and added my DJI Developer key. But as soon as I open the app it crashes and gives this error:

12-01 22:52:46.596 18090-18090/? D/SDKRelativeJNI: Couldn't load lib
12-01 22:52:46.596 18090-18090/? E/art: No implementation found for java.lang.String dji.midware.natives.SDKRelativeJNI.native_getUsbAccessoryAttachedString() (tried Java_dji_midware_natives_SDKRelativeJNI_native_1getUsbAccessoryAttachedString and Java_dji_midware_natives_SDKRelativeJNI_native_1getUsbAccessoryAttachedString__)
12-01 22:52:46.597 18090-18090/? D/AndroidRuntime: Shutting down VM
12-01 22:52:46.597 18090-18090/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.dji.sdk.sample, PID: 18090
                                                   java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String dji.midware.natives.SDKRelativeJNI.native_getUsbAccessoryAttachedString() (tried Java_dji_midware_natives_SDKRelativeJNI_native_1getUsbAccessoryAttachedString and Java_dji_midware_natives_SDKRelativeJNI_native_1getUsbAccessoryAttachedString__)
                                                       at dji.midware.natives.SDKRelativeJNI.native_getUsbAccessoryAttachedString(Native Method)
                                                       at dji.sdk.sdkmanager.DJISDKManager.<clinit>(Unknown Source)
                                                       at dji.sdk.sdkmanager.DJISDKManager.getInstance(Unknown Source)
                                                       at com.dji.sdk.sample.internal.controller.DJISampleApplication.onCreate(DJISampleApplication.java:94)
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
                                                       at android.app.ActivityThread.-wrap3(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1699)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
12-01 22:52:48.100 18090-18097/? I/art: Ignoring second debugger -- accepting and dropping

#### Is this issue about bugs or crash issues of DJI Android SDK and Sample Code?

Yep, then please delete this template and provide the following infos for us to help investigate the issue:

-  Description of the issue.
-  Steps to reproduce the bug or crash issues(It would be great if you can provide this)
-  Crash logs (If you can find it, it would be very helpful)
-  DJI Android SDK version you are using (Like Android SDK 3.4, etc)
-  DJI Product you are using (Like Phantom 4, Mavic Pro, etc)
-  Android system version you are using (Like Android 6.0.1, Android 5.1.1, etc)
-  Android device you are using (Like Samsung Galaxy Note 5, Nexus 5, etc)
-  Android Studio version you are using (Like Android Studio 2.2, etc)

#### Is this issue about DJI iOS SDK and Sample Code?

Then this is the wrong place, please refer to the Mobile-SDK-iOS Github: <https://github.com/dji-sdk/Mobile-SDK-iOS/issues>

**Comment by talobin** [comment]
Hello,

Please provide enough information about your set up so we can look further into the crash.
All information in the section: `please delete this template and provide the following infos for us to help investigate the issue:` need to be filled out

**Comment by amirfarazmand** [comment]
There is definitely something wrong with my package name on your developer website. Is this package names allowed:  com.dji.sdk?
The error is related to this:
            DJISDKManager.getInstance().registerApp(this, mDJISDKManagerCallback);

**Comment by amirfarazmand** [comment]
All I did added the API key from the developer website to Android Manifest  and built the app My phone is running Android 7.0.

**Comment by Michael-DJI** [comment]
pls make sure the app package name in website is same as it in your manifest file.
