### ISSUE TITLE
SDK 4.4.0 proguard error

### ISSUE THREAD

**Issue by VolodymyrCj** [dji-sdk/Mobile-SDK-Android#207]
I get the error when run application on device after proguard:

```java
java.lang.NoSuchMethodError: No super method buildUnknownFields()Lokio/ByteString; in class Lcom/squareup/wire/Message$Builder; or its super classes (declaration of 'com.squareup.wire.Message$Builder')
	at com.dji.service.areacode.wire.DJIACCityModel$a.a(Unknown Source)
	at com.dji.service.areacode.wire.DJIACCityModel$b.a(Unknown Source)
	at com.dji.service.areacode.wire.DJIACCityModel$b.decode(Unknown Source)
	at com.dji.service.areacode.wire.DJIACCityListModel$b.a(Unknown Source)
	at com.dji.service.areacode.wire.DJIACCityListModel$b.decode(Unknown Source)
	at com.squareup.wire.ProtoAdapter.decode(Unknown Source)
	at com.squareup.wire.ProtoAdapter.decode(Unknown Source)
	at com.dji.service.areacode.d.a(Unknown Source)
	at com.dji.service.areacode.d.a(Unknown Source)
	at com.dji.service.areacode.d.a(Unknown Source)
	at com.dji.service.areacode.DJIAreaCodeManger.a(Unknown Source)
	at com.dji.service.areacode.DJIAreaCodeManger.a(Unknown Source)
	at com.dji.service.areacode.DJIAreaCodeManger$e$1.handleMessage(Unknown Source)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.os.HandlerThread.run(HandlerThread.java:61)
```

-  minSdkVersion: 21; targetSdkVersion: 22;compileSdkVersion: 26;
-  Android Studio version: 3.0.1

I have already add proguard rule:
```java
-keep class com.squareup.wire.** { *; }
```
so, how can I fix it?
Thanks!

**Comment by Michael-DJI** [comment]
@VolodymyrCj hi, are you using another version of wire?

**Comment by VolodymyrCj** [comment]
@Michael-DJI yes, I use the official [protobuf java sdk](https://github.com/google/protobuf),
how can I fix it if I dont want to change it to wire?

**Comment by Michael-DJI** [comment]
@VolodymyrCj, I think the best way is changing to wire, otherwise you need separately download all the dependencies in form of aar or jar, and use "jarjar" to rename the package name for wire and the code where are using wire inside dji sdk(both aar and jar), it's much more complicated than changing to wire.

**Comment by VolodymyrCj** [comment]
@Michael-DJI I remove protobuf denpendency used in my project, but the same error occus?

**Comment by VolodymyrCj** [comment]
@Michael-DJI I try to proguard the [Sample Code](https://github.com/dji-sdk/Mobile-SDK-Android/tree/master/Sample%20Code), the same error occurs

**Comment by Michael-DJI** [comment]
@VolodymyrCj then, could u pls check the mapping file to verify if com.squareup.wire.Message$Builder is obfuscated?

**Comment by VolodymyrCj** [comment]
@Michael-DJI the proguard rule list in the [wire](https://github.com/square/wire) is that
```java
-keep class com.squareup.wire.** { *; }
-keep class com.yourcompany.yourgeneratedcode.** { *; }
```
as the second line discribe,
I think it is the class dji sdk used are obfuscated, can you provide the rule, Thanks!

**Comment by Michael-DJI** [comment]
@VolodymyrCj pls try:
https://github.com/dji-sdk/Mobile-SDK-Android/blob/master/proguard-project.txt

**Comment by VolodymyrCj** [comment]
@Michael-DJI thanks, it solved
