### ISSUE TITLE
Database malformed causes application crash

### ISSUE THREAD

**Issue by justintuchek** [dji-sdk/Mobile-SDK-Android#209]
-  Description of the issue.
>Updating no fly zones appears doesn't handle malformed database files.

-  Steps to reproduce the bug or crash issues(It would be great if you can provide this)
>Cannot reproduce, not sure if device or file is legitimate or tampered, but since NFZ updates happen somewhat transparently to a user it means exceptions from this can propagate whenever in the runtime.

-  Crash logs (If you can find it, it would be very helpful)
First: SM-G930R4
>net.sqlcipher.database.SQLiteDatabaseCorruptException: database disk image is malformed: DELETE FROM polygon_tfr_remote_data
    at net.sqlcipher.database.SQLiteDatabase.native_execSQL(SQLiteDatabase.java)
    at net.sqlcipher.database.SQLiteDatabase.execSQL(SQLiteDatabase.java:2265)
    at dji.thirdparty.afinal.FinalDb.deleteAll
    at dji.midware.data.forbid.db.FlyfrbBaseDbManager.deleteAll
    at dji.pilot.flyforbid.c$1.a
    at dji.pilot.flyforbid.c$1.onSuccess
    at dji.thirdparty.afinal.http.HttpHandler.onProgressUpdate
    at dji.thirdparty.afinal.core.AsyncTask$InternalHandler.handleMessage
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6688)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

Second: SM-N950U
> net.sqlcipher.database.SQLiteDatabaseCorruptException: error code 11: database disk image is malformed
    at net.sqlcipher.database.SQLiteStatement.native_execute(SQLiteStatement.java)
    at net.sqlcipher.database.SQLiteStatement.execute(SQLiteStatement.java:58)
    at net.sqlcipher.database.SQLiteDatabase.execSQL(SQLiteDatabase.java:2319)
    at dji.thirdparty.afinal.FinalDb.exeSqlInfo
    at dji.thirdparty.afinal.FinalDb.save
    at dji.midware.data.forbid.db.FlyfrbBaseDbManager.save
    at dji.pilot.flyforbid.c$1.a
    at dji.pilot.flyforbid.c$1.onSuccess
    at dji.thirdparty.afinal.http.HttpHandler.onProgressUpdate
    at dji.thirdparty.afinal.core.AsyncTask$InternalHandler.handleMessage
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6823)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)

Third: Pixel XL
> net.sqlcipher.database.SQLiteDatabaseCorruptException: database disk image is malformed: DELETE FROM polygon_tfr_remote_data
    at net.sqlcipher.database.SQLiteDatabase.native_execSQL(SQLiteDatabase.java)
    at net.sqlcipher.database.SQLiteDatabase.execSQL(SQLiteDatabase.java:2265)
    at dji.thirdparty.afinal.FinalDb.deleteAll
    at dji.midware.data.forbid.db.FlyfrbBaseDbManager.deleteAll
    at dji.pilot.flyforbid.c$1.a
    at dji.pilot.flyforbid.c$1.onSuccess
    at dji.thirdparty.afinal.http.HttpHandler.onProgressUpdate
    at dji.thirdparty.afinal.core.AsyncTask$InternalHandler.handleMessage
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6494)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

-  DJI Android SDK version you are using (Like Android SDK 3.4, etc)
> 4.3.2
-  DJI Product you are using (Like Phantom 4, Mavic Pro, etc)
> Crash reporting, seems probably there doesn't need to be a drone connected for issue to occur
-  Android system version you are using (Like Android 6.0.1, Android 5.1.1, etc)
> Android 7.0
-  Android device you are using (Like Samsung Galaxy Note 5, Nexus 5, etc)
> SM-G930R4, SM-N950U, Pixel XL
-  Android Studio version you are using (Like Android Studio 2.2, etc)
> 3.0 stable

**Comment by jtuchek** [comment]
Fourth occurrence.
Device: LGMP260
Device Family: LGMP260
Android Version: 7.0

>java.lang.IllegalStateException: database not open
    at net.sqlcipher.database.SQLiteDatabase.execSQL(SQLiteDatabase.java:2262)
    at dji.thirdparty.afinal.FinalDb.deleteAll
    at dji.midware.data.forbid.db.FlyfrbBaseDbManager.deleteAll
    at dji.pilot.flyforbid.c$1.a
    at dji.pilot.flyforbid.c$1.onSuccess
    at dji.thirdparty.afinal.http.HttpHandler.onProgressUpdate
    at dji.thirdparty.afinal.core.AsyncTask$InternalHandler.handleMessage
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6316)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)

**Comment by jtuchek** [comment]
If it's of any relevance - the release that these are coming from was our 3.x -> 4.x migration.

**Comment by Michael-DJI** [comment]
@jtuchek which version of DJI SDK? did you try 4.4.1?

**Comment by jtuchek** [comment]
@Michael-DJI `4.3.2` is the SDK Version being used in those crash reports.

No, I haven't tried 4.4.1. Unless if there's a way to force an NFZ sync event I can't really try and see if this works. Only wait a few weeks and see if there's an absence of reported crashes.
