### ISSUE TITLE
Crash due to occusync signal strength listener

### ISSUE THREAD

**Issue by JamesMasterman** [dji-sdk/Mobile-SDK-Android#218]
In my code I have registered for Ocusync and lightbridge (depending on the drone) signal strength via 

 airlink.setDownlinkSignalQualityCallback();

This all works fine, but sometimes when shutting down the drone, I get a null pointer exception that crashes my app. This only occurs on Mavic Pros,  which use the Ocusync link.

Edit: Changed the steps to reproduce: It seems that just registering for setDownloadSignalQualityCallback when the drone first connects can cause the error. It's a little bit random, but should be easy to fix by simply checking for nulls

The stack trace is:

` E/UncaughtException: java.lang.NullPointerException: Attempt to invoke virtual method int java.lang.Integer.intValue() on a null object reference
                                                        at dji.sdk.airlink.OcuSyncLink$5.onValueChange(Unknown Source)
                                                        at dji.sdksharedlib.listener.DJISDKCacheListenerLayer$ValueChangeRunnable.run(Unknown Source)
                                                        at android.os.Handler.handleCallback(Handler.java:761)
                                                        at android.os.Handler.dispatchMessage(Handler.java:98)
                                                        at android.os.Looper.loop(Looper.java:156)
                                                        at android.os.HandlerThread.run(HandlerThread.java:61)
E/AndroidRuntime: FATAL EXCEPTION: SingleBackgroundLooper
                                                 java.lang.NullPointerException: Attempt to invoke virtual method int java.lang.Integer.intValue() on a null object reference
                                                     at dji.sdk.airlink.OcuSyncLink$5.onValueChange(Unknown Source)
                                                     at dji.sdksharedlib.listener.DJISDKCacheListenerLayer$ValueChangeRunnable.run(Unknown Source)
                                                     at android.os.Handler.handleCallback(Handler.java:761)
                                                     at android.os.Handler.dispatchMessage(Handler.java:98)
                                                     at android.os.Looper.loop(Looper.java:156)
                                                     at android.os.HandlerThread.run(HandlerThread.java:61)`

I am using Android 7 on various devices (Samsung S7, Samsung S2, Huawei media pad M3)
SDK: 4.4.1 (this does not occur in earlier SDK versions)
Drone: Mavic Pro running the latest 1.4.100 firmware

Seems like this would be an easy fix by checking for nulls before calling onValueChange

**Comment by EranRos** [comment]
Having that issue as well. Not random at all.
Happens each time I power off the drone or the drone loses connection during flight (RF obstruction or too far away).
If I don't register the downlink/uplink callbacks it's ok, but then I can't show signal quality, obviously.
All attempts at working around this have failed, so far.
Trying to unregister when receiving a product disconnect callback doesn't work.

Does this happen on version 4.4 or was this bug "added" on version 4.4.1?

Seriously considering reverting back to version 4.3.2, which had other bugs but not ths one.

**Comment by Michael-DJI** [comment]
thanks, it will be fixed in next version.

**Comment by EranRos** [comment]
ETA for next version?

**Comment by Michael-DJI** [comment]
we are very sorry about that, maybe one month later?
