### ISSUE TITLE
java.lang.VerifyError

### ISSUE THREAD

**Issue by kjknair** [dji-sdk/Mobile-SDK-Android#234]
```
java.lang.VerifyError: Constructor must call super() or this() before return
Exception Details:
  Location:
    dji/logic/receiver/DJIPilotStartupReceiver.<init>()V @0: return
  Reason:
    Error exists in the bytecode
  Bytecode:
    0x0000000: b1                                     


	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at org.robolectric.util.ReflectionHelpers.callConstructor(ReflectionHelpers.java:337)
	at org.robolectric.internal.bytecode.ShadowImpl.newInstanceOf(ShadowImpl.java:21)
	at org.robolectric.shadow.api.Shadow.newInstanceOf(Shadow.java:35)
	at org.robolectric.shadows.ShadowApplication.registerBroadcastReceivers(ShadowApplication.java:159)
	at org.robolectric.shadows.ShadowApplication.bind(ShadowApplication.java:136)
	at org.robolectric.android.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:134)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:328)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:241)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:123)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:77)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
```
Dji sdk version : 4.4.1.

after upgrading my app from 4.3.2 to 4.4.1. All my  roboelectric tests fail due to this. Only change i have made on upgrade is adding 

`Helper.install(this);`
any how i am using it as 
```
if(!isInUnitTests()){
      Helper.install(this);
    }
```
my unit tests doesnt use any of dji code. what is the issue.

**Comment by oliverou** [comment]
Hi @kjknair, for the new Android SDK 4.4.1, since some of SDK classes now need to be loaded before using, the loading process is done by `Helper.install()`. Developer must invoke this method before using any SDK functionality. Failing to do so will result in unexpected crashes.

**Comment by kjknair** [comment]
Yes I am doing that.  Every robolectric tests fails by showing the above error after the upgrade.

**Comment by wocoltd** [comment]
Hi - does your DJIPilotStartupReceiver class implement a DJI callback? I had all kinds of similar problems because of this - classes were getting instantiated before I'd had a chance to call Helper.install(), and that may be what is happening to your unit tests?

**Comment by kjknair** [comment]
@wocoltd I am not using DJIPilotStartupReceiver at all!

**Comment by wocoltd** [comment]
Interesting! I don't really know anything about your testing approach to help much, but like I said, I found objects kept trying to get instantiated when I didn't ask for it!

I ended up only ever dynamically creating objects that would have anything to do with the DJI sdk once I was sure everything was registered, even though it means an annoying extra level of abstraction.

**Comment by kjknair** [comment]
How are you registering without calling `Helper#install`?

**Comment by kjknair** [comment]
@wocoltd can you please elaborate the solution?

**Comment by kjknair** [comment]
The only thing  I can do right now is to test code by changing the SDK version to 4.3.2.

**Comment by wocoltd** [comment]
@kjknair, if your app is working fine in normal execution mode then I'm not sure my solution will help you? 

In my case I had a singleton object that originally implemented FlightcontrollerState.Callback, and this was getting instantiated before any of my other code had a chance to run and causing a crash. I therefore changed it to look like this (simplified quite a bit):

public class mySingleton {

    @Subscribe
    public void onConnectivityChange( myApp.ConnectivityChangeEvent event ) {

            // Set up flight controller status callbacks
            // This has to be created here rather than have this class
            // statically inherit from the callback class.
            FlightControllerState.Callback cb = new FlightControllerState.Callback() {
                @Override
                public void onUpdate(FlightControllerState flightControllerState) {

                    // Reflect up to parent class
                    handleFCCallback(flightControllerState);
                }
        }
      
      private void handleFCCallback(@NonNull final FlightControllerState flightControllerState) {
            // Actually do stuff in here
      }
}

Like I said I don't really know much about what the automated testing you're using is doing in terms of creating objects, but I'd look to see if anything could be trying to statically create an object that includes something from the DJI SDK?

Sorry I can't be more helpful!

**Comment by Michael-DJI** [comment]
@kjknair problem solved?

**Comment by kjknair** [comment]
no. I am still using 4.3.2

**Comment by kjknair** [comment]
Hai @Michael-DJI this issue isn't resolved in 4.5.1 either.

**Comment by Michael-DJI** [comment]
@kjknair could u pls show me your build.gradle file? and pls test with our sample app, to check if the sample app have the same issue, if not could u pls provide a gitHub repo, which could reproduce this issue?

**Comment by kjknair** [comment]
When i run the test from Android Studio it shows the above error. But i just tried it in the terminal 
`./gradlew test`. It just runs fine. Seems to be some other issue not related to DJI SDK.
