### ISSUE TITLE
Internal NullpointerException in WaypointMission$Builder

### ISSUE THREAD

**Issue by reddigfabian** [dji-sdk/Mobile-SDK-Android#235]
We are experiencing a crash when attempting to upload a waypoint mission. Our current app runs hotpoint missions using the timeline logic but we have not yet migrated waypoint missions to the timeline. If we upload a waypoint mission, then set up a hotpoint mission in the timeline, and then try to upload another waypoint mission, we receive the following crash.

> 02-15 13:57:14.712 7451-7451/com.precisionhawk.inflightmobile E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: com.precisionhawk.inflightmobile, PID: 7451
                                                                                java.lang.NullPointerException: Attempt to invoke virtual method 'void dji.internal.c.a.f.a.a(dji.common.mission.waypoint.WaypointMission$Builder)' on a null object reference
                                                                                    at dji.internal.c.a.f.c.a(Unknown Source:18)
                                                                                    at dji.sdk.mission.waypoint.WaypointMissionOperator.uploadMission(Unknown Source:108)
                                                                                    at com.precisionhawk.inflightmobile.flightcontrol.controller.MissionController.uploadMissionToAircraft(MissionController.java:503)
                                                                                    at com.precisionhawk.inflightmobile.flightcontrol.controller.MissionController.access$700(MissionController.java:54)
                                                                                    at com.precisionhawk.inflightmobile.flightcontrol.controller.MissionController$3.run(MissionController.java:488)
                                                                                    at android.os.Handler.handleCallback(Handler.java:790)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                    at android.os.Looper.loop(Looper.java:164)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
02-15 13:57:14.881 7451-7451/com.precisionhawk.inflightmobile E/DJICrashHandler: uncaughtException 3
02-15 13:57:14.882 7451-8674/com.precisionhawk.inflightmobile E/UsbAccessoryService: final destroy() 71

All DJI Products
Android SDK 4.4.1
All Android versions
Pixel 2, Huawei M3
Android Studio 3.0.1

**Comment by Michael-DJI** [comment]
did you resolve your issue with new version?
if not, pls report the issue to dev@dji.com it's the official channel to request DJI SDK support now.
