### ISSUE TITLE
Index out of bound on FPVOverlayWidget.updateCameraTargetIfNeeded

### ISSUE THREAD

**Issue by martindroneharmony** [dji-sdk/Mobile-SDK-Android#236]
Description:
In FPVOverlayWidget.updateCameraTargetIfNeeded, index out of bound exception, 
access with index -1, should be an easy fix.

Android SDK: 4.4.1

Stack trace:
#0. Crashed: main
       at dji.ui.widget.FPVOverlayWidget.updateCameraTargetIfNeeded(Unknown Source)
       at dji.ui.widget.FPVOverlayWidget.onTouch(Unknown Source)
       at android.view.View.dispatchTouchEvent(View.java:10012)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2833)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2504)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
       at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2869)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1861)
       at android.app.Activity.dispatchTouchEvent(Activity.java:3061)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
       at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2830)
       at android.view.View.dispatchPointerEvent(View.java:10253)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5523)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5359)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4804)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4857)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4823)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4964)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4831)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5021)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4804)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4857)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4823)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4831)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4804)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7525)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7393)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7354)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7635)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:323)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:7422)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

--

Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
       at dji.ui.widget.FPVOverlayWidget.updateCameraTargetIfNeeded(Unknown Source)
       at dji.ui.widget.FPVOverlayWidget.onTouch(Unknown Source)
       at android.view.View.dispatchTouchEvent(View.java:10012)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2833)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2504)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
       at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2869)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1861)
       at android.app.Activity.dispatchTouchEvent(Activity.java:3061)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
       at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2830)
       at android.view.View.dispatchPointerEvent(View.java:10253)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5523)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5359)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4804)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4857)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4823)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4964)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4831)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5021)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4804)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4857)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4823)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4831)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4804)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7525)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7393)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7354)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7635)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:323)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:7422)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by Michael-DJI** [comment]
@martindroneharmony thanks for your feedback! this will be fixed in next version.

**Comment by Michael-DJI** [comment]
did you resolve your issue with new version?
if not, pls report the issue to dev@dji.com it's the official channel to request DJI SDK support now.

**Comment by martindroneharmony** [comment]
@Michael-DJI yes, looks like the newer SDKs fixed this issue.

**Comment by Michael-DJI** [comment]
@martindroneharmony ok, got you!
