### ISSUE TITLE
DJI registration crashes because of database corruption

### ISSUE THREAD

**Issue by martindroneharmony** [dji-sdk/Mobile-SDK-Android#237]
Description:
It happens sometimes that the DJI database gets corrupted during flight. Bad thing about this is that once it happens the only solution known to us is to reinstall the app or clear all app data. 
It looks very bad for the user as the app simply crashes on DJI registration. A possible short term workaround would be a method isCorrupted that will test if DB is ok, then either fix method to reformat the database or instruct the user to clear data. Since DJI is using a native implementation for the database, it is not possible to catch the exception either.

Android SDK: 4.4.1
 
net.sqlcipher.database.SQLiteDatabaseCorruptException: database disk image is malformed: DELETE FROM polygon_tfr_remote_data
	at net.sqlcipher.database.SQLiteDatabase.native_execSQL(Native Method)
	at net.sqlcipher.database.SQLiteDatabase.execSQL(SQLiteDatabase.java:2265)
	at dji.thirdparty.afinal.FinalDb.deleteAll(Unknown Source)
	at dji.midware.data.forbid.db.FlyfrbBaseDbManager.deleteAll(Unknown Source)
	at dji.pilot.flyforbid.c$1.a(Unknown Source)
	at dji.pilot.flyforbid.c$1.onSuccess(Unknown Source)
	at dji.thirdparty.afinal.http.HttpHandler.onProgressUpdate(Unknown Source)
	at dji.thirdparty.afinal.core.AsyncTask$InternalHandler.handleMessage(Unknown Source)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5527)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)

**Comment by Djacob502** [comment]
I thought this was fixed? How often are you seeing this error?

**Comment by martindroneharmony** [comment]
> I thought this was fixed? How often are you seeing this error?

DJI fixed the occasional crash that happened on registration in SDK 4.3.2, so it is much more stable now. We estimate that the above corruption of the database happens in the low digits percentage wise. We had so far two confirmed reports on this error (including stacktrace) from our user base / fabric.

**Comment by Michael-DJI** [comment]
@martindroneharmony did you resolve your issue with new version?
if not, pls report the issue to dev@dji.com it's the official channel to request DJI SDK support now.

**Comment by martindroneharmony** [comment]
@Michael-DJI seems like it is resolved with newer SDKs as we do not see this error in crash logs anymore.

**Comment by Michael-DJI** [comment]
@martindroneharmony ok, thanks for the replay:)
