### ISSUE TITLE
App crashes when shrinkResources is enabled

### ISSUE THREAD

**Issue by reddigfabian** [dji-sdk/Mobile-SDK-Android#239]
Connecting a product to any app with 4.3.2 SDK and `shrinkResources true` results in the following crash:

```
com.dji.sdk.sample E/AndroidRuntime: FATAL EXCEPTION: dji_background_thread
                                                                    Process: com.dji.sdk.sample, PID: 29153
                                                                    java.lang.NullPointerException: Attempt to read from field 'long dji.midware.data.params.P3.ParamInfo.hash' on a null object reference
                                                                        at dji.midware.data.model.P3.DataFlycGetParams.doPack(Unknown Source)
                                                                        at dji.midware.data.manager.P3.DataBase.getSendData(Unknown Source)
                                                                        at dji.midware.data.manager.P3.DataBase.start(Unknown Source)
                                                                        at dji.midware.data.model.P3.DataFlycGetParams.start(Unknown Source)
                                                                        at dji.sdksharedlib.hardware.abstractions.flightcontroller.b.a.a(Unknown Source)
                                                                        at dji.sdksharedlib.hardware.a.i.b(Unknown Source)
                                                                        at dji.sdksharedlib.hardware.a.i.a(Unknown Source)
                                                                        at dji.sdksharedlib.hardware.a.i$1.handleMessage(Unknown Source)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by Michael-DJI** [comment]
@reddigfabian add a "keep.xml" file under your res/raw/ folder:
the content is:
<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:tools="http://schemas.android.com/tools"
           tools:keep="@raw/flyc_param_infos"/>

**Comment by reddigfabian** [comment]
Looks like that resolves the issue. Thank you @Michael-DJI !
