### ISSUE TITLE
OcuSyncLink Crash

### ISSUE THREAD

**Issue by MikeWoots** [dji-sdk/Mobile-SDK-Android#244]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
       at dji.sdk.airlink.OcuSyncLink$4.onValueChange(Unknown Source)
       at dji.sdksharedlib.listener.DJISDKCacheListenerLayer$ValueChangeRunnable.run(Unknown
Source)
       at android.os.Handler.handleCallback(Handler.java:836)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:203)
       at android.os.HandlerThread.run(HandlerThread.java:61)

I am getting multiple occurrences of this crash report via Fabric on my production build since upgrading to SDK version 4.4.1

**Comment by ysffood** [comment]
I have the same problem.

**Comment by Michael-DJI** [comment]
it will be fixed in next version

**Comment by EranRos** [comment]
When will that be?
