### ISSUE TITLE
连接上飞机后，偶发性出现异常，找不到发生源

### ISSUE THREAD

**Issue by Raozhu** [dji-sdk/Mobile-SDK-Android#255]
不管是在飞行时，还是放置不管时，只要连接了飞机后偶发性的会有下面异常发生，找不到发生源……
net.sqlcipher.database.SQLiteException: no such table: polygon_tfr_area: DELETE FROM polygon_tfr_area
	at net.sqlcipher.database.SQLiteDatabase.native_execSQL(Native Method)
	at net.sqlcipher.database.SQLiteDatabase.execSQL(SQLiteDatabase.java:2265)
	at dji.thirdparty.afinal.FinalDb.deleteAll(Unknown Source)
	at dji.midware.data.forbid.db.FlyfrbBaseDbManager.deleteAll(Unknown Source)
	at dji.pilot.flyforbid.c$1.a(Unknown Source)
	at dji.pilot.flyforbid.c$1.onSuccess(Unknown Source)
	at dji.thirdparty.afinal.http.HttpHandler.onProgressUpdate(Unknown Source)
	at dji.thirdparty.afinal.core.AsyncTask$InternalHandler.handleMessage(Unknown Source)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5534)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

**Comment by zoemcateedji** [comment]
What version of the SDK are you seeing this with?

**Comment by Raozhu** [comment]
@zoemcateedji 4.3.2 ，Android

**Comment by zoemcateedji** [comment]
It was fixed with the 4.4 release.

**Comment by Raozhu** [comment]
@zoemcateedji thank you so much !

**Comment by Raozhu** [comment]
我在升级4.4后运行过程中，在SDKManagerCallback的实例化时出现了NoClassDefFoundError的错误，也根据文档与FAQ，并且参考了别人提出的几个issue，都无法解决问题。
奇怪的是，我在build文档中的dependencies中选择导入SDK会出现NoClassDefFoundError，
此时FIle -> Project Structure -> appName -> Dependencies 中并没有我导入的DJI SDK。
而选择在此处手动导入SDKManagerCallback可以成功实例化，但是却在registerApp时出现了java.lang.VerifyError的错误

**Comment by Raozhu** [comment]
java.lang.NoClassDefFoundError: Failed resolution of: Ldji/sdk/sdkmanager/DJISDKManager$SDKManagerCallback;
                      at java.lang.Class.newInstance(Native Method)
                      at android.app.Instrumentation.newApplication(Instrumentation.java:1010)
                      at android.app.Instrumentation.newApplication(Instrumentation.java:995)
                      at android.app.LoadedApk.makeApplication(LoadedApk.java:849)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5686)
                      at android.app.ActivityThread.-wrap2(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637)
                      at android.os.Handler.dispatchMessage(Handler.java:105)
                      at android.os.Looper.loop(Looper.java:156)
                      at android.app.ActivityThread.main(ActivityThread.java:6577)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "dji.sdk.sdkmanager.DJISDKManager$SDKManagerCallback" on path: DexPathList[[zip file "/data/app/com.kenuo.esmart-2/base.apk", zip file "/data/app/com.kenuo.esmart-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.kenuo.esmart-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.kenuo.esmart-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.kenuo.esmart-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.kenuo.esmart-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.kenuo.esmart-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.kenuo.esmart-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.kenuo.esmart-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.kenuo.esmart-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.kenuo.esmart-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.kenuo.esmart-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.kenuo.esmart-2/lib/arm, /system/fake-libs, /data/app/com.kenuo.esmart-2/base.apk!/lib/armeabi-v7a, /data/app/com.kenuo.esmart-2/split_lib_dependencies_apk.apk!/lib/armeabi-v7a, /data/app/com.kenuo.esmart-2/split_lib_slice_0_apk.apk!/lib/armeabi-v7a, /data/app/com.kenuo.esmart-2/split_lib_slice_1_apk.apk!/lib/armeabi-v7a, /data/app/com.kenuo.esmart-2/split_lib_slice_2_apk.apk!/lib/armeabi-v7a, /data/app/com.kenuo.esmart-2/split_lib_slice_3_apk.apk!/lib/armeabi-v7a, /data/app/com.kenuo.esmart-2/split_lib_slice_4_apk.apk!/lib/armeabi-v7a, /data/app/com.kenuo.esmart-2/split_lib_slice_5_apk.apk!/lib/armeabi-v7a, /data/app/com.kenuo.esmart-2/split_lib_slice_6_apk.apk!/lib/armeabi-v7a, /data/app/com.kenuo.esmart-2/split_lib_slice_7_apk.apk!/lib/armeabi-v7a, /data/app/com.kenuo.esmart-2/split_lib_slice_8_apk.apk!/lib/armeabi-v7a, /data/app/com.kenuo.esmart-2/split_lib_slice_9_apk.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/vendor/lib, /product/lib]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                      at java.lang.Class.newInstance(Native Method) 
                      at android.app.Instrumentation.newApplication(Instrumentation.java:1010) 
                      at android.app.Instrumentation.newApplication(Instrumentation.java:995) 
                      at android.app.LoadedApk.makeApplication(LoadedApk.java:849) 
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5686) 
                      at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637) 
                      at android.os.Handler.dispatchMessage(Handler.java:105) 
                      at android.os.Looper.loop(Looper.java:156) 
                      at android.app.ActivityThread.main(ActivityThread.java:6577) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by Raozhu** [comment]
java.lang.VerifyError: Verifier rejected class dji.sdk.sdkmanager.DJISDKManager: void dji.sdk.sdkmanager.DJISDKManager.<init>() failed to verify: void dji.sdk.sdkmanager.DJISDKManager.<init>(): [0x0] Constructor returning without calling superclass constructor (declaration of 'dji.sdk.sdkmanager.DJISDKManager' appears in /data/app/com.kenuo.esmart-1/split_lib_dependencies_apk.apk:classes2.dex)
                      at dji.sdk.sdkmanager.DJISDKManager.getInstance(Unknown Source)
                      at com.kenuo.esmart.application.EsmartApplication.onCreate(EsmartApplication.java:156)
                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1028)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5712)
                      at android.app.ActivityThread.-wrap2(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637)
                      at android.os.Handler.dispatchMessage(Handler.java:105)
                      at android.os.Looper.loop(Looper.java:156)
                      at android.app.ActivityThread.main(ActivityThread.java:6577)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by Michael-DJI** [comment]
Hi, did you resolve your issue with new version?
if not, pls report the issue to dev@dji.com it's the official channel to request DJI SDK support now.
