### ISSUE TITLE
There are NoClassDefFoundError errors when upgrad the 4.4 version

### ISSUE THREAD

**Issue by Raozhu** [dji-sdk/Mobile-SDK-Android#258]
there is an error in upgrading to 4.4,it's  NoClassDefFoundError,according to documeng and FAQ,and refer to some issues that otherone came up with,i can't solve this error.

build 
`
packagingOptions {
        doNotStrip "*/*/libdjivideo.so"
        doNotStrip "*/*/libSDKRelativeJNI.so"
        doNotStrip "*/*/libFlyForbid.so"
        doNotStrip "*/*/libduml_vision_bokeh.so"
        doNotStrip "*/*/libyuv2.so"
        doNotStrip "*/*/libGroudStation.so"
        doNotStrip "*/*/libFRCorkscrew.so"
        doNotStrip "*/*/libUpgradeVerify.so"
        doNotStrip "*/*/libFR.so"

        exclude 'proguard-project.txt'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/LGPL2.1'
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            resources.srcDirs = ['src']
            aidl.srcDirs = ['src']
            renderscript.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
            jniLibs.srcDirs = ['libs']
        }

        // Move the tests to tests/java, tests/res, etc...
        instrumentTest.setRoot('tests')

        // Move the build types to build-types/<type>
        // For instance, build-types/debug/java, build-types/debug/AndroidManifest.xml, ...
        // This moves them out of them default location under src/<type>/... which would
        // conflict with src/ being used by the fragment_gis_app source set.
        // Adding new build types or product flavors should be accompanied
        // by a similar customization.
        debug.setRoot('build-types/debug')
        release.setRoot('build-types/release')
    }

    splits {
        abi {
            enable true
            reset()
            include 'armeabi-v7a'
            universalApk false
        }
    }

    repositories {
        flatDir {
            dirs 'libs' //项目中有.aar文件需要加上
        }
    }

    dependencies {
        compile fileTree(include: '*.jar', dir: 'libs')
        compile 'com.android.support:multidex:1.0.1'
        compile 'com.google.android.gms:play-services-appindexing:8.4.0'
        compile files('libs/android-async-http-1.4.8.jar')
        compile files('libs/org.apache.http.legacy.jar')
        compile 'com.android.support:recyclerview-v7:24.2.0'
        compile "com.android.support:support-v4:24.2.0"
        compile files('libs/com.baidu.tts_2.3.1.20170808_e39ea89.jar')

        compile('com.dji:dji-sdk:4.4.1')
        provided('com.dji:dji-sdk-provided:4.4.1')
    }`

application onCreate code
` 
super.onCreate();
        Logger.initLogger(this);
        mHandler = new Handler(Looper.getMainLooper());
        /**
         * handles SDK Registration using the API_KEY
         */
        DJISDKManager.SDKManagerCallback mSDKManagerCallback = new DJISDKManager.SDKManagerCallback() {
            @Override
            public void  onRegister(DJIError error) {
                if (error == DJISDKError.REGISTRATION_SUCCESS) {
                    Logger.d("mmmm 开始连接");
                    DJISDKManager.getInstance().startConnectionToProduct();
                } else {
                    Handler handler = new Handler(Looper.getMainLooper());
                    handler.post(new Runnable() {
                        @Override
                        public void run() {
                            ToastUtil.show(EsmartApplication.this, R.string.sdk_registration_message);
                        }
                    });
                }
                Log.v(TAG, error.getDescription());
            }

            @Override
            public void onProductChange(BaseProduct oldProduct, BaseProduct newProduct) {
                Logger.d("mmmm " + String.format("onProductChange oldProduct:%s, newProduct:%s", oldProduct, newProduct));
                mProduct = newProduct;
                if (mProduct != null) {
                    mProduct.setBaseProductListener(mBaseProductListener);
                }
                notifyStatusChange();
            }

            private BaseProduct.BaseProductListener mBaseProductListener = new BaseProduct.BaseProductListener() {
                @Override
                public void onComponentChange(BaseProduct.ComponentKey key, BaseComponent oldComponent, BaseComponent newComponent) {
                    if (newComponent != null) {
                        newComponent.setComponentListener(mComponentListener);
                    }
                    Log.v(TAG, String.format("onComponentChange key:%s, oldComponent:%s, newComponent:%s", key, oldComponent, newComponent));
                    notifyStatusChange();
                }

                @Override
                public void  onConnectivityChange(boolean isConnected) {
                    Log.v(TAG, " onConnectivityChange: " + isConnected);
                    notifyStatusChange();
                }
            };

            private BaseComponent.ComponentListener mComponentListener = new BaseComponent.ComponentListener() {
                @Override
                public void  onConnectivityChange(boolean isConnected) {
                    notifyStatusChange();
                }
            };

            private void notifyStatusChange() {
                mHandler.removeCallbacks(updateRunnable);
                mHandler.postDelayed(updateRunnable, 500);
            }

            private Runnable updateRunnable = new Runnable() {
                @Override
                public void run() {
                    Intent intent = new Intent(FLAG_CONNECTION_CHANGE);
                    sendBroadcast(intent);
                }
            };
        };
        DJISDKManager.getInstance().registerApp(this, mSDKManagerCallback);

@Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);

        MultiDex.install(this);
        Helper.install(EsmartApplication.this);
    }

`

and error
`
java.lang.NoClassDefFoundError: Failed resolution of: Ldji/sdk/sdkmanager/DJISDKManager$SDKManagerCallback;
                      at java.lang.Class.newInstance(Native Method)
                      at android.app.Instrumentation.newApplication(Instrumentation.java:1010)
                      at android.app.Instrumentation.newApplication(Instrumentation.java:995)
                      at android.app.LoadedApk.makeApplication(LoadedApk.java:849)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5686)
                      at android.app.ActivityThread.-wrap2(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637)
                      at android.os.Handler.dispatchMessage(Handler.java:105)
                      at android.os.Looper.loop(Looper.java:156)
                      at android.app.ActivityThread.main(ActivityThread.java:6577)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "dji.sdk.sdkmanager.DJISDKManager$SDKManagerCallback" on path: DexPathList[[zip file "/data/app/com.kenuo.esmart-1/base.apk", zip file "/data/app/com.kenuo.esmart-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.kenuo.esmart-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.kenuo.esmart-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.kenuo.esmart-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.kenuo.esmart-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.kenuo.esmart-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.kenuo.esmart-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.kenuo.esmart-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.kenuo.esmart-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.kenuo.esmart-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.kenuo.esmart-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.kenuo.esmart-1/lib/arm, /system/fake-libs, /data/app/com.kenuo.esmart-1/base.apk!/lib/armeabi-v7a, /data/app/com.kenuo.esmart-1/split_lib_dependencies_apk.apk!/lib/armeabi-v7a, /data/app/com.kenuo.esmart-1/split_lib_slice_0_apk.apk!/lib/armeabi-v7a, /data/app/com.kenuo.esmart-1/split_lib_slice_1_apk.apk!/lib/armeabi-v7a, /data/app/com.kenuo.esmart-1/split_lib_slice_2_apk.apk!/lib/armeabi-v7a, /data/app/com.kenuo.esmart-1/split_lib_slice_3_apk.apk!/lib/armeabi-v7a, /data/app/com.kenuo.esmart-1/split_lib_slice_4_apk.apk!/lib/armeabi-v7a, /data/app/com.kenuo.esmart-1/split_lib_slice_5_apk.apk!/lib/armeabi-v7a, /data/app/com.kenuo.esmart-1/split_lib_slice_6_apk.apk!/lib/armeabi-v7a, /data/app/com.kenuo.esmart-1/split_lib_slice_7_apk.apk!/lib/armeabi-v7a, /data/app/com.kenuo.esmart-1/split_lib_slice_8_apk.apk!/lib/armeabi-v7a, /data/app/com.kenuo.esmart-1/split_lib_slice_9_apk.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/vendor/lib, /product/lib]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                      at java.lang.Class.newInstance(Native Method) 
                      at android.app.Instrumentation.newApplication(Instrumentation.java:1010) 
                      at android.app.Instrumentation.newApplication(Instrumentation.java:995) 
                      at android.app.LoadedApk.makeApplication(LoadedApk.java:849) 
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5686) 
                      at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637) 
                      at android.os.Handler.dispatchMessage(Handler.java:105) 
                      at android.os.Looper.loop(Looper.java:156) 
                      at android.app.ActivityThread.main(ActivityThread.java:6577) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) `

**Comment by Michael-DJI** [comment]
did you resolve your issue ?
if not, pls report the issue to dev@dji.com it's the official channel to request DJI SDK support now.
