### ISSUE TITLE
Fatal Exception (NPE): Attempt to read from field 'float dji.ui.internal.LineChartView$a.a' on a null object reference

### ISSUE THREAD

**Issue by martindroneharmony** [dji-sdk/Mobile-SDK-Android#265]
**Description of the issue:**
This NPE crash is happening from time to time and we suspect the cause for this is the DJI Histogram widget (LineChartView). The stack trace should be enough to fix this.

**Steps to reproduce the bug or crash issues(It would be great if you can provide this)**
Have DJI Histogram widget open / shown in application

**Android system version you are using (Like Android 6.0.1, Android 5.1.1, etc)**
Happens on various versions (cause not related to it)

**Android device you are using (Like Samsung Galaxy Note 5, Nexus 5, etc)**
Happens on various devices (cause not related to it)

**DJI Android SDK version you are using (Like Android SDK 3.4, etc)**
SDK 4.4.1

**DJI Product you are using (Like Phantom 4, Mavic Pro, etc)**
Happens with various drones (cause not related to it)

**Stack trace:**
#0. Crashed: main
       at dji.ui.internal.LineChartView.c(Unknown Source)
       at dji.ui.internal.LineChartView.a(Unknown Source)
       at dji.ui.internal.LineChartView.onSizeChanged(Unknown Source)
       at android.view.View.sizeChange(View.java:17790)
       at android.view.View.setFrame(View.java:17752)
       at android.view.View.layout(View.java:17660)
       at dji.ui.c.a.c.a(Unknown Source)
       at dji.ui.base.c.onLayout(Unknown Source)
       at android.view.View.layout(View.java:17663)
       at android.view.ViewGroup.layout(ViewGroup.java:5577)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:17663)
       at android.view.ViewGroup.layout(ViewGroup.java:5577)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:17663)
       at android.view.ViewGroup.layout(ViewGroup.java:5577)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
       at android.view.View.layout(View.java:17663)
       at android.view.ViewGroup.layout(ViewGroup.java:5577)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:17663)
       at android.view.ViewGroup.layout(ViewGroup.java:5577)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
       at android.view.View.layout(View.java:17663)
       at android.view.ViewGroup.layout(ViewGroup.java:5577)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:730)
       at android.view.View.layout(View.java:17663)
       at android.view.ViewGroup.layout(ViewGroup.java:5577)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2388)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2110)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1296)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6401)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:876)
       at android.view.Choreographer.doCallbacks(Choreographer.java:688)
       at android.view.Choreographer.doFrame(Choreographer.java:623)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:862)
       at android.os.Handler.handleCallback(Handler.java:754)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6205)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

--

Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'float dji.ui.internal.LineChartView$a.a' on a null object reference
       at dji.ui.internal.LineChartView.c(Unknown Source)
       at dji.ui.internal.LineChartView.a(Unknown Source)
       at dji.ui.internal.LineChartView.onSizeChanged(Unknown Source)
       at android.view.View.sizeChange(View.java:17790)
       at android.view.View.setFrame(View.java:17752)
       at android.view.View.layout(View.java:17660)
       at dji.ui.c.a.c.a(Unknown Source)
       at dji.ui.base.c.onLayout(Unknown Source)
       at android.view.View.layout(View.java:17663)
       at android.view.ViewGroup.layout(ViewGroup.java:5577)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:17663)
       at android.view.ViewGroup.layout(ViewGroup.java:5577)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:17663)
       at android.view.ViewGroup.layout(ViewGroup.java:5577)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
       at android.view.View.layout(View.java:17663)
       at android.view.ViewGroup.layout(ViewGroup.java:5577)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:17663)
       at android.view.ViewGroup.layout(ViewGroup.java:5577)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
       at android.view.View.layout(View.java:17663)
       at android.view.ViewGroup.layout(ViewGroup.java:5577)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:730)
       at android.view.View.layout(View.java:17663)
       at android.view.ViewGroup.layout(ViewGroup.java:5577)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2388)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2110)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1296)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6401)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:876)
       at android.view.Choreographer.doCallbacks(Choreographer.java:688)
       at android.view.Choreographer.doFrame(Choreographer.java:623)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:862)
       at android.os.Handler.handleCallback(Handler.java:754)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6205)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

**Comment by Michael-DJI** [comment]
Hi @martindroneharmony  did you resolve your issue with new version?
if not, pls report the issue to dev@dji.com it's the official channel to request DJI SDK support now.

**Comment by martindroneharmony** [comment]
@Michael-DJI we have not seen this crash for a while - could be that it was fixed with one of the newer UX SDK versions.

**Comment by Michael-DJI** [comment]
@martindroneharmony ok, IC thanks for the reply!
