### ISSUE TITLE
自拍杆2 调用demo中蓝牙模块，蓝牙连接，断开，再连接，连接时app崩溃，

### ISSUE THREAD

**Issue by shanyaodan** [dji-sdk/Mobile-SDK-Android#268]
java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.lang.Iterable.iterator()' on a null object reference
                                                                  at android.os.Parcel.readException(Parcel.java:1690)
                                                                  at android.os.Parcel.readException(Parcel.java:1637)
                                                                  at android.bluetooth.IBluetoothGatt$Stub$Proxy.writeCharacteristic(IBluetoothGatt.java:920)
                                                                  at android.bluetooth.BluetoothGatt.writeCharacteristic(BluetoothGatt.java:861)
                                                                  at dji.midware.ble.BLE.writeCharacteristic(Unknown Source)
                                                                  at dji.midware.ble.BLE.sendNonBlockingWriteRequest(Unknown Source)
                                                                  at dji.midware.ble.BLE.executeQueue(Unknown Source)
                                                                  at dji.midware.ble.BLE.access$3000(Unknown Source)
                                                                  at dji.midware.ble.BLE$9.run(Unknown Source)

**Comment by Michael-DJI** [comment]
did you resolve your issue with new version?
if not, pls report the issue to dev@dji.com it's the official channel to request DJI SDK support now.
