### ISSUE TITLE
[Android] URGENT, crash app after a few minutes

### ISSUE THREAD

**Issue by Mustafa9391** [dji-sdk/Mobile-SDK-Android#284]
it's urgent,
when I run the application it works, but after 4 min it stops, i get this log : 
04-25 14:29:23.933 4323-4428/com.xx.xxx_project.xxx E/DJISDKCacheHWAbstraction: java.lang.reflect.InvocationTargetException                                                                                                
                               
  at java.lang.reflect.Method.invoke(Native Method)                                                                                   
 at dji.sdksharedlib.hardware.abstractions.b.a(Unknown Source)                                                                
 at dji.sdksharedlib.hardware.a.a(Unknown Source)                                                                                     
 at dji.sdksharedlib.hardware.a.a$b.run(Unknown Source)                                                                          
 at dji.sdksharedlib.hardware.a.b.d(Unknown Source)                                                                                 
 at dji.sdksharedlib.hardware.a.b.a(Unknown Source)                                                                                  
 at dji.sdksharedlib.hardware.a.b$a.handleMessage(Unknown Source)                                                      
 at android.os.Handler.dispatchMessage(Handler.java:102)                                                                        
 at android.os.Looper.loop(Looper.java:148)                                                                                                
 at android.os.HandlerThread.run(HandlerThread.java:61)                                                                  
 Caused by: java.lang.OutOfMemoryError: pthread_create (1040KB stack)

does anyone knows what is the solution ?thank you,
--
-  DJI Product  (Phantom 4, Mavic Pro, Spark)
-  Android system version (Android 6.0.1)
- SDK 4.5

**Comment by Michael-DJI** [comment]
@Mustafa9391 did u test on all three type: Phantom4 Mavic and Spark ?
pls try with 4.5.1 if the 4.5.1 still have the issue pls provide the firmware version of the drone you are using, we will try to reproduce it, thanks.

**Comment by Michael-DJI** [comment]
did you resolve your issue with new version?
if not, pls report the issue to dev@dji.com it's the official channel to request DJI SDK support now.
