### ISSUE TITLE
Sometime Battery State Callback return wrong value

### ISSUE THREAD

**Issue by ltluc253** [dji-sdk/Mobile-SDK-Android#313]
I use this [callback](https://developer.dji.com/api-reference/android-api/Components/Battery/DJIBattery_BatteryState.html#djibattery_stateupdatecallbackinterface_inline) to read Drone battery via method [setStateCallback](https://developer.dji.com/api-reference/android-api/Components/Battery/DJIBattery.html#djibattery_setstateupdatecallback_inline) but sometime the remaining battery percentage alway is 0. I've check on logcat and see this log

> W/System.err: java.lang.NumberFormatException: For input string: "40+"
W/System.err:     at java.lang.Integer.parseInt(Integer.java:521)
        at java.lang.Integer.parseInt(Integer.java:556)
        at dji.fr.a.d.a(Unknown Source)
        at dji.fr.a.d.f(Unknown Source)
        at dji.fr.a.d.handleMessage(Unknown Source)
        at dji.fr.e.b.handleMessage(Unknown Source)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at dji.fr.e.b.dispatchMessage(Unknown Source)
        at android.os.Looper.loop(Looper.java:156)
        at android.os.HandlerThread.run(HandlerThread.java:61)

Please help me check. My test environment is listed as below:

- DJI SDK version 4.5.1

- Drone: M100

- Android device: Tablet Huawei BTV, model BTV-DL09

**Comment by Jim-DJI** [comment]
@ltluc253 Hi, Can you provide the firmware version or battery version which occurs the bug? Thanks.
BTW, you could report the issue to dev@dji.com it's the official channel to request DJI SDK support now.
