### ISSUE TITLE
Not Connect after register app . Some time Sample demo also throw same error

### ISSUE THREAD

**Issue by Dhawan7** [dji-sdk/Mobile-SDK-Android#336]
mobile version:7.0
min sdk:19
buildversion :28.0.0
device:dji mavic pro

6822-6874/com.dji.sdk.sample E/a: bind exception:
    java.net.SocketException: getpeername failed: ENOTSOCK (Socket operation on non-socket)
        at android.net.Network.bindSocket(Network.java:352)
        at dji.midware.f.a.a(Unknown Source)
        at dji.midware.natives.UDT.bindSocketToNetwork(Unknown Source)
        at dji.midware.natives.UDT.SwUdpConnect(Native Method)
        at dji.midware.sockets.pub.i.connect(Unknown Source)
        at dji.midware.sockets.pub.i.checkConneted(Unknown Source)
        at dji.midware.sockets.pub.i.access$000(Unknown Source)
        at dji.midware.sockets.pub.i$1.run(Unknown Source)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
     Caused by: android.system.ErrnoException: getpeername failed: ENOTSOCK (Socket operation on non-socket)
        at libcore.io.Posix.getpeername(Native Method)
        at libcore.io.ForwardingOs.getpeername(ForwardingOs.java:84)
        at android.system.Os.getpeername(Os.java:181)
        at android.net.Network.bindSocket(Network.java:342)
        at dji.midware.f.a.a(Unknown Source) 
        at dji.midware.natives.UDT.bindSocketToNetwork(Unknown Source) 
        at dji.midware.natives.UDT.SwUdpConnect(Native Method) 
        at dji.midware.sockets.pub.i.connect(Unknown Source) 
        at dji.midware.sockets.pub.i.checkConneted(Unknown Source) 
        at dji.midware.sockets.pub.i.access$000(Unknown Source) 
        at dji.midware.sockets.pub.i$1.run(Unknown Source) 
        at java.util.TimerThread.mainLoop(Timer.java:555) 
        at java.util.TimerThread.run(Timer.java:505) 
08-03 19:01:14.159 6822-6874/com.dji.sdk.sample E/getNetworkObject: network type:1

**Comment by mattogodoy** [comment]
Well, 4 months later since I posted it's still happening.

It happens in a Huawei MediaPad M3 with Android 7.0, but it also happens in a DJI Cristal Sky updated to tha latest Android version.

We are using DJI Mobile SDK version 4.7

**Comment by Michael-DJI** [comment]
@mattogodoy the modified Android Rom in Huawei M3 tablet  will lead to abnormal crash, this has been mentioned in our release notes for several versions, it's strongly not a recommended device.

**Comment by Michael-DJI** [comment]
@mattogodoy sorry, we don't provide the prefered tablet.
