### ISSUE TITLE
how can i use sqlcipher library in my project with sdk?

### ISSUE THREAD

**Issue by dannyjiajia** [dji-sdk/Mobile-SDK-Android#344]
hi guys, i have use Mobile-SDK-Android 4.6 in my project,and i should use  [Android-Debug-Database](https://github.com/amitshekhariitbhu/Android-Debug-Database) library to debug my  bussiess database(finally, i will  use `sqlcipher ` to encrypt the database,just like the SDK). and  it crashed:

~~~
 java.lang.UnsatisfiedLinkError: No implementation found for void net.sqlcipher.database.SQLiteDatabase.dbopen(java.lang.String, int) (tried Java_net_sqlcipher_database_SQLiteDatabase_dbopen and Java_net_sqlcipher_database_SQLiteDatabase_dbopen__Ljava_lang_String_2I)
                                                                               at net.sqlcipher.database.SQLiteDatabase.dbopen(Native Method)
                                                                               at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2412)
                                                                               at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1149)
                                                                               at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1116)
                                                                               at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1065)
                                                                               at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1226)
                                                                               at com.amitshekhar.server.RequestHandler.openDatabase(RequestHandler.java:185)
                                                                               at com.amitshekhar.server.RequestHandler.getTableListResponse(RequestHandler.java:304)
                                                                               at com.amitshekhar.server.RequestHandler.handle(RequestHandler.java:113)
                                                                               at com.amitshekhar.server.ClientServer.run(ClientServer.java:76)
                                                                               at java.lang.Thread.run(Thread.java:760)
~~~

**I have use `pickFirst` to use your so file,just like this:**

~~~
   packagingOptions {
        pickFirst  'lib/*/libsqlcipher.so'
}
~~~

**Comment by dannyjiajia** [comment]
any suggestion? which version do you use?

**Comment by Michael-DJI** [comment]
Hi @dannyjiajia , inside sdk, sqlcipher is a special version, and it has the different package name, please use and public version of sqlcipher you want to use.
Notes: you could report the issue in Stackoverflow using "dji-sdk" tag, it will attract more attention of our supporting team.

**Comment by dannyjiajia** [comment]
thanks  @Michael-DJI , i think you should renamed the `libsqlcipher.so`  file  if you have modifed the `sqlcipher` ,we can not add the public version of `sqlcipher` because of the file.

**Comment by Michael-DJI** [comment]
@dannyjiajia yes, that make sense, I will record it into our system. thanks! sorry for the inconvenience!

**Comment by Michael-DJI** [comment]
it will be fixed in 4.8 version.

**Comment by dannyjiajia** [comment]
@Michael-DJI Thanks for your reply, i have to renamed the `libsqlcipher.so` file in public version.
May I ask you another questions?

1. How can i  get the `electromagnetic interference` with this sdk?
2. Which sdk should i  use for the `phantom 4 rtk` aircraft?

**Comment by Michael-DJI** [comment]
@dannyjiajia what do you mean by electromagnetic interference? for p4r sdk there is only internal version right now, public version is still under testing.

**Comment by dannyjiajia** [comment]
@Michael-DJI can i get the  internal version sdk for p4r testing?

**Comment by Michael-DJI** [comment]
@dannyjiajia could you please close this issue? for interval version of p4r pls contact with the sale man you bought the drone from thanks.

**Comment by dannyjiajia** [comment]
@Michael-DJI  thanks
