### ISSUE TITLE
NoClassDefFoundError: Failed resolution of: Lorg/apache/http/params/BasicHttpParams

### ISSUE THREAD

**Issue by lwj814** [dji-sdk/Mobile-SDK-Android#381]
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/params/BasicHttpParams;
                                                                         at dji.thirdparty.afinal.FinalHttp.<init>(Unknown Source:12)
                                                                         at com.dji.frame.util.V_AppUtils.a(Unknown Source:9)
                                                                         at com.dji.service.areacode.c.a(Unknown Source:22)
                                                                         at com.dji.service.areacode.DJIAreaCodeManger.l(Unknown Source:41)
                                                                         at com.dji.service.areacode.DJIAreaCodeManger.s(Unknown Source:60)
                                                                         at com.dji.service.areacode.DJIAreaCodeManger.r(Unknown Source:62)
                                                                         at com.dji.service.areacode.DJIAreaCodeManger.a(Unknown Source:24)
                                                                         at dji.internal.a.c.c(Unknown Source:10)
                                                                         at dji.internal.a.c.a(Unknown Source:32)
                                                                         at dji.sdk.sdkmanager.DJISDKManager.initParams(Unknown Source:31)
                                                                         at dji.sdk.sdkmanager.DJISDKManager.initSDKManager(Unknown Source:129)
                                                                         at dji.sdk.sdkmanager.DJISDKManager.access$1100(Unknown Source:0)
                                                                         at dji.sdk.sdkmanager.DJISDKManager$5.run(Unknown Source:104)
                                                                         at java.lang.Thread.run(Thread.java:784)
                                                                      Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.params.BasicHttpParams" on path: DexPathList[[zip file "/data/app/com.whulabs.djiosmo-Z3jVsBLlrUloe-4rKia6CA==/base.apk", dex file "InMemoryDexFile[cookie=[0, 535214115904]]", dex file "InMemoryDexFile[cookie=[0, 535214116288]]"],nativeLibraryDirectories=[/data/app/com.whulabs.djiosmo-Z3jVsBLlrUloe-4rKia6CA==/lib/arm64, /data/app/com.whulabs.djiosmo-Z3jVsBLlrUloe-4rKia6CA==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
                                                                         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                         at dji.thirdparty.afinal.FinalHttp.<init>(Unknown Source:12) 
                                                                         at com.dji.frame.util.V_AppUtils.a(Unknown Source:9) 
                                                                         at com.dji.service.areacode.c.a(Unknown Source:22) 
                                                                         at com.dji.service.areacode.DJIAreaCodeManger.l(Unknown Source:41) 
                                                                         at com.dji.service.areacode.DJIAreaCodeManger.s(Unknown Source:60) 
                                                                         at com.dji.service.areacode.DJIAreaCodeManger.r(Unknown Source:62) 
                                                                         at com.dji.service.areacode.DJIAreaCodeManger.a(Unknown Source:24) 
                                                                         at dji.internal.a.c.c(Unknown Source:10) 
                                                                         at dji.internal.a.c.a(Unknown Source:32) 
                                                                         at dji.sdk.sdkmanager.DJISDKManager.initParams(Unknown Source:31) 
                                                                         at dji.sdk.sdkmanager.DJISDKManager.initSDKManager(Unknown Source:129) 
                                                                         at dji.sdk.sdkmanager.DJISDKManager.access$1100(Unknown Source:0) 
                                                                         at dji.sdk.sdkmanager.DJISDKManager$5.run(Unknown Source:104) 
                                                                         at java.lang.Thread.run(Thread.java:784)

**Comment by lwj814** [comment]
Android  9.0

**Comment by FimaTaf** [comment]
Having the same issue, I've posted it on stackoverflow:
https://stackoverflow.com/questions/54126327/dji-sdk-failed-resolution-of-lorg-apache-http-params-basichttpparams

**Comment by kenargo** [comment]
The SDK works on Android 9, I am testing with a Samsung Galaxy S8+ running Android 9.  No problems that I have seen so far.

 

Can you be more specific about what issues you are experiencing?

**Comment by kenargo** [comment]
Do you have Proguard enabled?  This looks suspiciously like ProGuard is discarding needed classes.

 

If it’s enabled, try running the app with it disabled and see if the issue goes away

**Comment by lwj814** [comment]
Proguard is disable，the problem is still

**Comment by kenargo** [comment]
Perhaps if you can reproduce the issue using the sample?

I'm using the latest SDK and can confirm that I do not see the same issue. 


⁣Sent from BlueMail ​
