### ISSUE TITLE
Can't start the app in AVD [com.dji.FPVDem: No implementation found for java.lang.Object[] com.secneo.sdk.Helper.makeInMemoryDexElements]

### ISSUE THREAD

**Issue by chenerlich** [dji-sdk/Mobile-SDK-Android#382]
Trying to run the FPVDemo on Samsung S7 virtual device (with API 28).
DJI SDK 4.8.1.
Tried on APIs 22, 28, 25
DJI Mavic AIR
Samsung S7
Android Studio 3.2.1
![image](https://user-images.githubusercontent.com/17673075/51055767-91408a00-15e9-11e9-8f22-ebda2dc7174c.png)

App configuration:
```
    compileSdkVersion 26
    buildToolsVersion '28.0.3'
...
        minSdkVersion 19
        targetSdkVersion 26
```
Error:
```
I/zygote: Background concurrent copying GC freed 53(37KB) AllocSpace objects, 0(0B) LOS objects, 46% free, 6MB/12MB, paused 40.461ms total 62.732ms
V/sdk: DexInstall end
I/InstantRun: starting instant run server: is main process
E/linker: "/data/app/com.dji.FPVDemo-cadEFrFcw-riA0rfxKrxAA==/lib/x86/libffmpeg.so" has text relocations
W/System.err: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.dji.FPVDemo-cadEFrFcw-riA0rfxKrxAA==/lib/x86/libffmpeg.so" has text relocations
W/System.err:     at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1657)
        at dji.midware.natives.SDKRelativeJNI.<clinit>(Unknown Source:2)
        at dji.midware.natives.SDKRelativeJNI.native_getXXXX(Native Method)
        at com.dji.g.a.a.c.b(Unknown Source:22)
        at dji.midware.d.b(Unknown Source:2)
        at dji.sdk.sdkmanager.DJISDKManager.<clinit>(Unknown Source:2)
        at dji.sdk.sdkmanager.DJISDKManager.getInstance(Unknown Source:0)
        at com.dji.FPVDemo.FPVDemoApplication.onCreate(FPVDemoApplication.java:150)
        at com.dji.FPVDemo.MApplication.onCreate(MApplication.java:25)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5791)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
        at android.os.Handler.dispatchMessage(Handler.java:105)
W/System.err:     at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
D/SDKRelativeJNI: Couldn't load lib
E/zygote: No implementation found for byte[] dji.midware.natives.SDKRelativeJNI.native_getXXXX(java.lang.String) (tried Java_dji_midware_natives_SDKRelativeJNI_native_1getXXXX and Java_dji_midware_natives_SDKRelativeJNI_native_1getXXXX__Ljava_lang_String_2)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.dji.FPVDemo, PID: 12282
    java.lang.UnsatisfiedLinkError: No implementation found for byte[] dji.midware.natives.SDKRelativeJNI.native_getXXXX(java.lang.String) (tried Java_dji_midware_natives_SDKRelativeJNI_native_1getXXXX and Java_dji_midware_natives_SDKRelativeJNI_native_1getXXXX__Ljava_lang_String_2)
        at dji.midware.natives.SDKRelativeJNI.native_getXXXX(Native Method)
        at com.dji.g.a.a.c.b(Unknown Source:22)
        at dji.midware.d.b(Unknown Source:2)
        at dji.sdk.sdkmanager.DJISDKManager.<clinit>(Unknown Source:2)
        at dji.sdk.sdkmanager.DJISDKManager.getInstance(Unknown Source:0)
        at com.dji.FPVDemo.FPVDemoApplication.onCreate(FPVDemoApplication.java:150)
        at com.dji.FPVDemo.MApplication.onCreate(MApplication.java:25)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5791)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
I/Process: Sending signal. PID: 12282 SIG: 9
Disconnected from the target VM, address: 'localhost:8677', transport: 'socket'
```
Tried to rerun with sdk 22 as some answer suggested, without any luck (Too many errors with the project)
I would appreciate help.
Thanks.

**Comment by kenargo** [comment]
Virtual machines don't work well I've found.   Honestly,  use a USB or wifi connected device.

⁣Sent from BlueMail ​

**Comment by chenerlich** [comment]
@kenargo What do you mean? I haven't connected the drone during all this operation. It should start and show me that i'm not connected.
Should I connect the drone platform to me PC or something?

**Comment by kenargo** [comment]
I use a real android device,  the emulator in the past didn't work so I stopped trying to use it years ago. 

Trust me and connect am android device to the computer,  you will be much happier

⁣Sent from BlueMail ​

**Comment by chenerlich** [comment]
> I use a real android device,  the emulator in the past didn't work so I stopped trying to use it years ago. Trust me and connect am android device to the computer,  you will be much happier ⁣Sent from BlueMail ​
> […](#)
> On Jan 12, 2019, 4:41 AM, at 4:41 AM, Chen Erlich ***@***.***> wrote: @kenargo What do you mean? I haven't connected the drone during all this operation. It should start and show me that i'm not connected. Should I connect the drone platform to me PC or something? -- You are receiving this because you were mentioned. Reply to this email directly or view it on GitHub: [#382 (comment)](https://github.com/dji-sdk/Mobile-SDK-Android/issues/382#issuecomment-453744419)

You are right. Thanks.
