### ISSUE TITLE
NullPointerException when SDK is attempting to use DJIFeatureFlags

### ISSUE THREAD

**Issue by jtuchek** [dji-sdk/Mobile-SDK-Android#41]
I am unable to reproduce the issue consistently but will get the SDK to crash the host application when attempting to read feature flags.

Android Devices: Nexus 9, Nexus 6P
Android Studio: v2.2
Android Version: 7.0
DJI SDK Version: 3.3
DJI Product: P3 Controller and Phantom 3 Professional
Flight Controller Firmware: 02.04.15.05
Remote Controller Firmware: 1.6.0

10-13 13:30:50.532 13944-13944/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: <REDACTED>, PID: 13944
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Boolean dji.remote.DJIFeatureFlags.isNetworkingEnabled()' on a null object reference
                                                       at dji.remote.h.onResponse(Unknown Source)
                                                       at dji.thirdparty.retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by SilverChangjian** [comment]
Thanks for reporting this bug. We have already recorded it into our bug tracking system. It should be fixed in the upcoming version.

**Comment by tito91** [comment]
@SilverChangjian Could you please confirm whether the issue has been fixed in SDK V3.4?

**Comment by oliverou** [comment]
Hi @jtuchek, we have launched the Android SDK 3.4.1, please try it and check if the issue still exists, thanks!
