### ISSUE TITLE
UnsatisfiedLinkError for version 4.10，StringUtilsJNI exit Existing test methods

### ISSUE THREAD

**Issue by boosan** [dji-sdk/Mobile-SDK-Android#412]
@Michael-DJI  Please you test, and then released
`package com.dji.megatronking.stringfog;

import android.util.Log;
import com.dji.megatronking.stringfog.a.a.b;

@b
public class StringUtilsJNI
{
  public static native byte[] nativeGetXXXX(String paramString)
  {
    return null;
  }

  public static native void test()
  {
  }

  static
  {
    try
    {
      System.loadLibrary("sfjni");
    }
    catch (UnsatisfiedLinkError localUnsatisfiedLinkError)
    {
      localUnsatisfiedLinkError.printStackTrace();
      Log.e("sfjni", "Couldn't load lib");
    }
  }
}`

**Comment by Ray-DJI** [comment]
Hi, @boosan . DJI SDK with 4.10 have updated the secure strategies. Please add following lines in your project build.gradle 
`packagingOptions{
        doNotStrip "*/*/libdjivideo.so"
        doNotStrip "*/*/libSDKRelativeJNI.so"
        doNotStrip "*/*/libFlyForbid.so"
        doNotStrip "*/*/libduml_vision_bokeh.so"
        doNotStrip "*/*/libyuv2.so"
        doNotStrip "*/*/libGroudStation.so"
        doNotStrip "*/*/libFRCorkscrew.so"
        doNotStrip "*/*/libUpgradeVerify.so"
        doNotStrip "*/*/libFR.so"

       // Add the new so
        doNotStrip "*/*/libDJIFlySafeCore.so"
        doNotStrip "*/*/libdjifs_jni.so"
        exclude 'META-INF/rxjava.properties'
    }`

**Comment by boosan** [comment]
> Hi, @boosan . DJI SDK with 4.10 have updated the secure strategies. Please add following lines in your project build.gradle
> packagingOptions {
> 
> ```
>     doNotStrip "*/*/libdjivideo.so"
>     doNotStrip "*/*/libSDKRelativeJNI.so"
>     doNotStrip "*/*/libFlyForbid.so"
>     doNotStrip "*/*/libduml_vision_bokeh.so"
>     doNotStrip "*/*/libyuv2.so"
>     doNotStrip "*/*/libGroudStation.so"
>     doNotStrip "*/*/libFRCorkscrew.so"
>     doNotStrip "*/*/libUpgradeVerify.so"
>     doNotStrip "*/*/libFR.so"
> 
>     // Add the new so
>     doNotStrip "*/*/libDJIFlySafeCore.so"
>     doNotStrip "*/*/libdjifs_jni.so"
>     doNotStrip "*/*/libsfjni.so"
>     exclude 'META-INF/rxjava.properties'
> }
> ```
-------------------------------
Thank you for your reply ;
I try to recompile StringUtilsJNI. Java, at the same time, remove the 'public static native void test ()'.
Also solved the

**Comment by MikeAlvarado** [comment]
Hi, @boosan, @Michael-DJI @Ray-DJI, I'm helping an university team for a robotics competiticon:

when I'm trying to compile the UX sample project, I get the following error stacktrace.


```
2019-06-09 18:56:53.926 5026-5026/com.user.vanttecux E/sfjni: Couldn't load lib
2019-06-09 18:56:53.926 5026-5026/com.user.vanttecux E/fttek.vanttecu: No implementation found for void com.dji.megatronking.stringfog.StringUtilsJNI.test() (tried Java_com_dji_megatronking_stringfog_StringUtilsJNI_test and Java_com_dji_megatronking_stringfog_StringUtilsJNI_test__)
2019-06-09 18:56:53.927 5026-5026/com.user.vanttecux D/AndroidRuntime: Shutting down VM
2019-06-09 18:56:53.928 5026-5026/com.user.vanttecux E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.user.vanttecux, PID: 5026
    java.lang.UnsatisfiedLinkError: No implementation found for void com.dji.megatronking.stringfog.StringUtilsJNI.test() (tried Java_com_dji_megatronking_stringfog_StringUtilsJNI_test and Java_com_dji_megatronking_stringfog_StringUtilsJNI_test__)
        at com.dji.megatronking.stringfog.StringUtilsJNI.test(Native Method)
        at com.dji.megatronking.stringfog.a.c.b(Unknown Source:3)
        at dji.midware.e.b(Unknown Source:2)
        at dji.sdk.sdkmanager.DJISDKManager.<clinit>(Unknown Source:2)
        at dji.sdk.sdkmanager.DJISDKManager.getInstance(Unknown Source:0)
        at com.user.vanttecux.DemoApplication.onCreate(DemoApplication.java:70)
        at com.user.vanttecux.MApplication.onCreate(MApplication.java:24)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1165)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6039)
        at android.app.ActivityThread.access$1300(ActivityThread.java:207)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1748)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-06-09 18:56:53.930 5026-5026/com.user.vanttecux W/OPDiagnose: getService:OPDiagnoseService NULL
2019-06-09 18:56:53.934 5026-5053/com.user.vanttecux D/OSTracker: OS Event: crash
2019-06-09 18:56:53.945 5026-5026/com.user.vanttecux I/Process: Sending signal. PID: 5026 SIG: 9
```


Here is my DemoApp.

```
package com.user.vanttecux;

import android.app.Application;
import android.content.Context;
import android.content.Intent;
import android.os.Build;
import android.os.Handler;
import android.os.Looper;
import android.support.v4.content.ContextCompat;
import android.util.Log;
import android.widget.Toast;

import dji.common.error.DJIError;
import dji.common.error.DJISDKError;
import dji.common.useraccount.UserAccountState;
import dji.common.util.CommonCallbacks;
import dji.sdk.base.BaseComponent;
import dji.sdk.base.BaseProduct;
import dji.sdk.sdkmanager.DJISDKInitEvent;
import dji.sdk.sdkmanager.DJISDKManager;
import dji.sdk.useraccount.UserAccountManager;




public class DemoApplication extends Application {

    public static final String FLAG_CONNECTION_CHANGE = "uxsdk_demo_connection_change";

    private static BaseProduct mProduct;
    private Handler mHandler;
    private DJISDKManager.SDKManagerCallback mDJISDKManagerCallback;

    private Application instance;
    public void setContext(Application application) {
        instance = application;
    }

    @Override
    public Context getApplicationContext() {
        return instance;
    }

    public DemoApplication() {

    }

    /**
     * This function is used to get the instance of DJIBaseProduct.
     * If no product is connected, it returns null.
     */
    public static synchronized BaseProduct getProductInstance() {
        if (null == mProduct) {
            mProduct = DJISDKManager.getInstance().getProduct();
        }
        return mProduct;
    }

    @Override
    public void onCreate() {
        super.onCreate();
        mHandler = new Handler(Looper.getMainLooper());

        //Check the permissions before registering the application for android system 6.0 above.
        int permissionCheck = ContextCompat.checkSelfPermission(getApplicationContext(), android.Manifest.permission.WRITE_EXTERNAL_STORAGE);
        int permissionCheck2 = ContextCompat.checkSelfPermission(getApplicationContext(), android.Manifest.permission.READ_PHONE_STATE);
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.M || (permissionCheck == 0 && permissionCheck2 == 0)) {

            //This is used to start SDK services and initiate SDK.
            DJISDKManager.getInstance().registerApp(getApplicationContext(), mDJISDKManagerCallback);
        } else {
            Toast.makeText(getApplicationContext(), "Please check if the permission is granted.", Toast.LENGTH_LONG).show();
        }

        /**
         * When starting SDK services, an instance of interface DJISDKManager.DJISDKManagerCallback will be used to listen to
         * the SDK Registration result and the product changing.
         */
        mDJISDKManagerCallback = new DJISDKManager.SDKManagerCallback() {

            //Listens to the SDK registration result
            @Override
            public void onRegister(DJIError error) {
                if(error == DJISDKError.REGISTRATION_SUCCESS) {
                    DJISDKManager.getInstance().startConnectionToProduct();
                    Handler handler = new Handler(Looper.getMainLooper());
                    handler.post(new Runnable() {
                        @Override
                        public void run() {
                            Toast.makeText(getApplicationContext(), "Register Success", Toast.LENGTH_LONG).show();
                        }
                    });
                    loginAccount();

                } else {
                    Handler handler = new Handler(Looper.getMainLooper());
                    handler.post(new Runnable() {

                        @Override
                        public void run() {
                            Toast.makeText(getApplicationContext(), "Register Failed, check network is available", Toast.LENGTH_LONG).show();
                        }
                    });

                }
                Log.e("TAG", error.toString());
            }

            @Override
            public void onProductDisconnect() {
                Log.d("TAG", "onProductDisconnect");
                notifyStatusChange();
            }
            @Override
            public void onProductConnect(BaseProduct baseProduct) {
                Log.d("TAG", String.format("onProductConnect newProduct:%s", baseProduct));
                notifyStatusChange();

            }
            @Override
            public void onComponentChange(BaseProduct.ComponentKey componentKey, BaseComponent oldComponent,
                                          BaseComponent newComponent) {
                if (newComponent != null) {
                    newComponent.setComponentListener(new BaseComponent.ComponentListener() {

                        @Override
                        public void onConnectivityChange(boolean isConnected) {
                            Log.d("TAG", "onComponentConnectivityChanged: " + isConnected);
                            notifyStatusChange();
                        }
                    });
                }

                Log.d("TAG",
                        String.format("onComponentChange key:%s, oldComponent:%s, newComponent:%s",
                                componentKey,
                                oldComponent,
                                newComponent));

            }
            @Override
            public void onInitProcess(DJISDKInitEvent djisdkInitEvent, int i) {

            }

        };

    }

    private void loginAccount(){

        UserAccountManager.getInstance().logIntoDJIUserAccount(this,
                new CommonCallbacks.CompletionCallbackWith<UserAccountState>() {
                    @Override
                    public void onSuccess(final UserAccountState userAccountState) {
                        Log.e("TAG", "Login Success");
                    }
                    @Override
                    public void onFailure(DJIError error) {
                        Log.e("TAG", "Login Error:" + error.getDescription());
                    }
                });
    }

    private void notifyStatusChange() {
        mHandler.removeCallbacks(updateRunnable);
        mHandler.postDelayed(updateRunnable, 500);
    }

    private Runnable updateRunnable = new Runnable() {

        @Override
        public void run() {
            Intent intent = new Intent(FLAG_CONNECTION_CHANGE);
            getApplicationContext().sendBroadcast(intent);
        }
    };

}
```

My module app: 
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "com.user.vanttecux"
        minSdkVersion 19
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        // Enabling multidex support.
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }


    packagingOptions {

        doNotStrip "*/*/libdjivideo.so"
        doNotStrip "*/*/libSDKRelativeJNI.so"
        doNotStrip "*/*/libFlyForbid.so"
        doNotStrip "*/*/libduml_vision_bokeh.so"
        doNotStrip "*/*/libyuv2.so"
        doNotStrip "*/*/libGroudStation.so"
        doNotStrip "*/*/libFRCorkscrew.so"
        doNotStrip "*/*/libUpgradeVerify.so"
        doNotStrip "*/*/libFR.so"

        // Add the new so
        doNotStrip "*/*/libDJIFlySafeCore.so"
        doNotStrip "*/*/libdjifs_jni.so"
        doNotStrip "*/*/libsfjni.so"
        exclude 'META-INF/rxjava.properties'
    }


}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:27.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'

    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'

    implementation 'com.android.support:multidex:1.0.3'


    compile ('com.dji:dji-uxsdk:4.10')
    provided ('com.dji:dji-sdk-provided:4.10')
}
```

**Comment by Michael-DJI** [comment]
@MikeAlvarado Hey, thanks for the feedback! did you try to clean the project and rebuild it?

**Comment by MikeAlvarado** [comment]
@Michael-DJI, yes, I did. No luck yet. :(

**Comment by JimmyChenHY** [comment]
@MikeAlvarado I am facing the same problem. 
I try to clean the project and rebuild, but it doesn't work. 
Finally, "Make Project" let the problem disappear.
I am not sure but hope it will help you.

**Comment by MikeAlvarado** [comment]
@JimmyChenHY, sadly it didn't made the trick for me. If you have any more guesses, it will be very appreciated.
Also, maybe if you could run the demo app, if you could upload it to another repo, maybe it will run. 

Thanks in advance.

**Comment by MikeAlvarado** [comment]
> @Michael-DJI, yes, I did. No luck yet. :(

Any guess? I sincerely ran out of options.

**Comment by kenargo** [comment]
OK, I just did a fresh pull from Git for the UX project, compiled and ran it; no problems, no errors.

The one main issue I see is that your packageOptions appear out of date, did you maybe modify the file or started the project using the earlier 4.9 SDK; that's what is looks like to me.   They should read:

```
packagingOptions{
        doNotStrip "*/*/libdjivideo.so"
        doNotStrip "*/*/libSDKRelativeJNI.so"
        doNotStrip "*/*/libFlyForbid.so"
        doNotStrip "*/*/libduml_vision_bokeh.so"
        doNotStrip "*/*/libyuv2.so"
        doNotStrip "*/*/libGroudStation.so"
        doNotStrip "*/*/libFRCorkscrew.so"
        doNotStrip "*/*/libUpgradeVerify.so"
        doNotStrip "*/*/libFR.so"
        doNotStrip "*/*/libDJIFlySafeCore.so"
        doNotStrip "*/*/libdjifs_jni.so"
        doNotStrip "*/*/libsfjni.so"

        pickFirst 'lib/*/libstlport_shared.so'
        pickFirst 'lib/*/libRoadLineRebuildAPI.so'
        pickFirst 'lib/*/libGNaviUtils.so'
        pickFirst 'lib/*/libGNaviMapex.so'
        pickFirst 'lib/*/libGNaviData.so'
        pickFirst 'lib/*/libGNaviMap.so'
        pickFirst 'lib/*/libGNaviSearch.so'
        pickFirst 'lib/*/libDJIFlySafeCore.so'
        pickFirst 'lib/*/libdjifs_jni.so'
        pickFirst 'lib/*/libsfjni.so'
        exclude 'META-INF/rxjava.properties'
    }
```

**Comment by kenargo** [comment]
If the above is your Application class I noticed that you are not installing the SDK libraries.  You should have a call similar to this:

`
    @Override
    protected void attachBaseContext(Context paramContext) {
        super.attachBaseContext(paramContext);
        Helper.install(MApplication.this);
    }`

**Comment by boosan** [comment]
@MikeAlvarado I try to recompile StringUtilsJNI. Java file to remove the 'test' method.To solve the problem.
The compiled class files again:
`package com.dji.megatronking.stringfog;

import com.dji.megatronking.stringfog.a.a.b;

@b
public class StringUtilsJNI {
    public StringUtilsJNI() {
    }

    public static native byte[] nativeGetXXXX(String var0);

    static {
        try {
            System.loadLibrary("sfjni");
        } catch (UnsatisfiedLinkError var1) {
            var1.printStackTrace();
        }

    }
}`

**Comment by kjknair** [comment]
My app crashes whenever I call `DJISDKManager.getInstance()`. It was working in DJI SDK 4.9. I updated to 4.10 it started crashing. 

This is the code I have used.
In the `Application` class:
```
override fun attachBaseContext(base: Context?) {
    super.attachBaseContext(base)
    //DjiSDK
    com.secneo.sdk.Helper.install(this)
  }
```
point of crash:

```
DJISDKManager.getInstance().setCallbackRunInUIThread(true);
```
tried also the following:
```
DJISDKManager.getInstance().hasSDKRegistered()
```
DJISDKManager.getInstance().registerApp(context, callback)
```

the crash log says:
```
java.lang.UnsatisfiedLinkError: No implementation found for void com.dji.megatronking.stringfog.StringUtilsJNI.test() (tried Java_com_dji_megatronking_stringfog_StringUtilsJNI_test and Java_com_dji_megatronking_stringfog_StringUtilsJNI_test__)
        at com.dji.megatronking.stringfog.StringUtilsJNI.test(Native Method)
        at com.dji.megatronking.stringfog.a.c.b(Unknown Source:3)
        at dji.midware.e.b(Unknown Source:2)
        at dji.sdk.sdkmanager.DJISDKManager.<clinit>(Unknown Source:2)
        at dji.sdk.sdkmanager.DJISDKManager.getInstance(Unknown Source:0)
        at com.app.dji.data.dji.DjiSdkWrapperImpl.<init>(DjiSdkWrapperImpl.java:309)
        at com.app.dji.data.dji.DjiSdkWrapperImpl_Factory.get(DjiSdkWrapperImpl_Factory.java:22)
        at com.app.dji.data.dji.DjiSdkWrapperImpl_Factory.get(DjiSdkWrapperImpl_Factory.java:9)
```

I have changed the app package name. ( the actual package name is registered with developer.dji.com) which I was using for a long time. 
**Drone**: No drone connected yes. crash at start.
**mobile**: Samsumg J7 Prime
** SDK**: Dji sdk version 4.10

**Comment by kenargo** [comment]
Look at the sample; there are additional packagingOptions:

packagingOptions {
        doNotStrip "*/*/libdjivideo.so"
        doNotStrip "*/*/libSDKRelativeJNI.so"
        doNotStrip "*/*/libFlyForbid.so"
        doNotStrip "*/*/libduml_vision_bokeh.so"
        doNotStrip "*/*/libyuv2.so"
        doNotStrip "*/*/libGroudStation.so"
        doNotStrip "*/*/libFRCorkscrew.so"
        doNotStrip "*/*/libUpgradeVerify.so"
        doNotStrip "*/*/libFR.so"
        doNotStrip "*/*/libDJIFlySafeCore.so"
        doNotStrip "*/*/libdjifs_jni.so"
        doNotStrip "*/*/libsfjni.so"

        pickFirst 'lib/*/libstlport_shared.so'
        pickFirst 'lib/*/libRoadLineRebuildAPI.so'
        pickFirst 'lib/*/libGNaviUtils.so'
        pickFirst 'lib/*/libGNaviMapex.so'
        pickFirst 'lib/*/libGNaviData.so'
        pickFirst 'lib/*/libGNaviMap.so'
        pickFirst 'lib/*/libGNaviSearch.so'
        pickFirst 'lib/*/libDJIFlySafeCore.so'
        pickFirst 'lib/*/libdjifs_jni.so'
        pickFirst 'lib/*/libsfjni.so'
        exclude 'META-INF/rxjava.properties'
    }

**Comment by lining301** [comment]
> > Hi, @boosan . DJI SDK with 4.10 have updated the secure strategies. Please add following lines in your project build.gradle
> > packagingOptions {
> > ```
> >     doNotStrip "*/*/libdjivideo.so"
> >     doNotStrip "*/*/libSDKRelativeJNI.so"
> >     doNotStrip "*/*/libFlyForbid.so"
> >     doNotStrip "*/*/libduml_vision_bokeh.so"
> >     doNotStrip "*/*/libyuv2.so"
> >     doNotStrip "*/*/libGroudStation.so"
> >     doNotStrip "*/*/libFRCorkscrew.so"
> >     doNotStrip "*/*/libUpgradeVerify.so"
> >     doNotStrip "*/*/libFR.so"
> > 
> >     // Add the new so
> >     doNotStrip "*/*/libDJIFlySafeCore.so"
> >     doNotStrip "*/*/libdjifs_jni.so"
> >     doNotStrip "*/*/libsfjni.so"
> >     exclude 'META-INF/rxjava.properties'
> > }
> > ```
> 
> Thank you for your reply ;
> I try to recompile StringUtilsJNI. Java, at the same time, remove the 'public static native void test ()'.
> Also solved the

How to recompile?

**Comment by kvlee** [comment]
I try build android  project with this sdk ,if compileSdkVersion <29 ,it works ok,if compileSdkVersion>=29 ,it will be run error

**Comment by Cormor** [comment]
My SDK version is 4.13.1, and I also have this problem.
And the above methods are not effective.
