### ISSUE TITLE
DJI SDK 4.10 Crash... 

### ISSUE THREAD

**Issue by UnsignedUSB** [dji-sdk/Mobile-SDK-Android#438]
I am using AndroidX. But this problem occurs. There was someone with the same problem in the following Link comment. I need a solution for this.

**- Crash logs**
A/zygote64: java_vm_ext.cc:504] 
A/zygote64: runtime.cc:516] Runtime aborting...
A/zygote64: runtime.cc:516] 
A/zygote64: runtime.cc:524] JNI DETECTED ERROR IN APPLICATION: buf == null
A/zygote64: runtime.cc:524]     in call to SetPrimitiveArrayRegion
A/zygote64: runtime.cc:524]     from java.lang.Object[] com.secneo.sdk.Helper.makeInMemoryDexElements(java.lang.Object, java.util.List, java.lang.String)
A/zygote64: runtime.cc:524] "main" prio=5 tid=1 Runnable
A/zygote64: runtime.cc:524]   | group="main" sCount=0 dsCount=0 flags=0 obj=0x73274f50 self=0x7d7c8c0a00
A/zygote64: runtime.cc:524]   | sysTid=8254 nice=-10 cgrp=default sched=0/0 handle=0x7d81f1f9c8
A/zygote64: runtime.cc:524]   | state=R schedstat=( 1701521875 1865962 248 ) utm=148 stm=22 core=7 HZ=100
A/zygote64: runtime.cc:524]   | stack=0x7ff4721000-0x7ff4723000 stackSize=8MB
A/zygote64: runtime.cc:524]   | held mutexes= "mutator lock"(shared held)
A/zygote64: runtime.cc:524]   native: #00 pc 00000000003aeb84  /system/lib64/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+212)
A/zygote64: runtime.cc:524]   native: #01 pc 000000000008deac  /system/lib64/libart.so (???)
A/zygote64: runtime.cc:524]   native: #02 pc 00000000002e6280  /system/lib64/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+1040)
A/zygote64: runtime.cc:524]   native: #03 pc 00000000002e683c  /system/lib64/libart.so (_ZN3art9JavaVMExt9JniAbortFEPKcS2_z+204)
A/zygote64: runtime.cc:524]   native: #04 pc 0000000000379c3c  /system/lib64/libart.so (_ZN3art3JNI23SetPrimitiveArrayRegionIP11_jbyteArrayaNS_6mirror14PrimitiveArrayIaEEEEvP7_JNIEnvT_iiPKT0_+1692)
A/zygote64: runtime.cc:524]   native: #05 pc 0000000000116ffc  /system/lib64/libart.so (_ZN3art8CheckJNI23SetPrimitiveArrayRegionEPKcNS_9Primitive4TypeEP7_JNIEnvP7_jarrayiiPKv+940)
A/zygote64: runtime.cc:524]   native: #06 pc 0000000000014718  /data/app/com.prism.live-k9koKPkHRGEigHy641-1cA==/lib/arm64/libDexHelper_sdk.so (nativeGetByteArray+136)
A/zygote64: runtime.cc:524]   native: #07 pc 0000000000014bec  /data/app/com.prism.live-k9koKPkHRGEigHy641-1cA==/lib/arm64/libDexHelper_sdk.so (makeInMemoryDexElements+1212)
A/zygote64: runtime.cc:524]   native: #08 pc 0000000000147500  /system/lib64/libart.so (Java_com_secneo_sdk_Helper_makeInMemoryDexElements__Ljava_lang_Object_2Ljava_util_List_2Ljava_lang_String_2+144)
A/zygote64: runtime.cc:524]   native: #09 pc 000000000013e438  /system/lib64/libart.so (???)
A/zygote64: runtime.cc:524]   native: #10 pc 00000000000d86e4  /system/lib64/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+260)
A/zygote64: runtime.cc:524]   native: #11 pc 00000000002917e0  /system/lib64/libart.so (_ZN3art11interpreter34ArtInterpreterToCompiledCodeBridgeEPNS_6ThreadEPNS_9ArtMethodEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+352)
A/zygote64: runtime.cc:524]   native: #12 pc 000000000028bdf0  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+672)
A/zygote64: runtime.cc:524]   native: #13 pc 0000000000126e44  /system/lib64/libart.so (???)
A/zygote64: runtime.cc:524]   native: #14 pc 000000000012fd14  /system/lib64/libart.so (???)
A/zygote64: runtime.cc:524]   native: #15 pc 000000000026bf90  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+448)
A/zygote64: runtime.cc:524]   native: #16 pc 0000000000272854  /system/lib64/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+212)
A/zygote64: runtime.cc:524]   native: #17 pc 000000000028bdd0  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+640)
A/zygote64: runtime.cc:524]   native: #18 pc 0000000000126e44  /system/lib64/libart.so (???)
A/zygote64: runtime.cc:524]   native: #19 pc 000000000012fd14  /system/lib64/libart.so (???)
A/zygote64: runtime.cc:524]   native: #20 pc 000000000026bf90  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+448)
A/zygote64: runtime.cc:524]   native: #21 pc 0000000000272854  /system/lib64/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+212)
A/zygote64: runtime.cc:524]   native: #22 pc 000000000028bdd0  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+640)
A/zygote64: runtime.cc:524]   native: #23 pc 0000000000126e44  /system/lib64/libart.so (???)
A/zygote64: runtime.cc:524]   native: #24 pc 000000000012fd14  /system/lib64/libart.so (???)
A/zygote64: runtime.cc:524]   native: #25 pc 000000000026bf90  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+448)
A/zygote64: runtime.cc:524]   native: #26 pc 0000000000272854  /system/lib64/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+212)
A/zygote64: runtime.cc:524]   native: #27 pc 000000000028bdd0  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+640)
A/zygote64: runtime.cc:524]   native: #28 pc 0000000000126e44  /system/lib64/libart.so (???)
A/zygote64: runtime.cc:524]   native: #29 pc 000000000012fd14  /system/lib64/libart.so (???)
A/zygote64: runtime.cc:524]   native: #30 pc 000000000026bf90  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+448)
A/zygote64: runtime.cc:524]   native: #31 pc 0000000000272854  /system/lib64/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+212)
A/zygote64: runtime.cc:524]   native: #32 pc 000000000028bdd0  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+640)
A/zygote64: runtime.cc:524]   native: #33 pc 0000000000126e44  /system/lib64/libart.so (???)
A/zygote64: runtime.cc:524]   native: #34 pc 000000000012fd14  /system/lib64/libart.so (???)
A/zygote64: runtime.cc:524]   native: #35 pc 000000000026bf90  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+448)
A/zygote64: runtime.cc:524]   native: #36 pc 0000000000272854  /system/lib64/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+212)
A/zygote64: runtime.cc:524]   native: #37 pc 000000000028c568  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb1EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+1528)
A/zygote64: runtime.cc:524]   native: #38 pc 00000000002a5d2c  /system/lib64/libart.so (_ZN3art11interpreterL8DoInvokeILNS_10InvokeTypeE4ELb0ELb1EEEbPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+2060)
A/zygote64: runtime.cc:524]   native: #39 pc 000000000029d334  /system/lib64/libart.so (_ZN3art11interpreter17ExecuteSwitchImplILb1ELb0EEENS_6JValueEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameES2_b+41508)
A/zygote64: runtime.cc:524]   native: #40 pc 000000000026c06c  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+668)
A/zygote64: runtime.cc:524]   native: #41 pc 0000000000272854  /system/lib64/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+212)
A/zygote64: runtime.cc:524]   native: #42 pc 000000000028bdd0  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+640)
A/zygote64: runtime.cc:524]   native: #43 pc 00000000001257f4  /system/lib64/libart.so (???)
A/zygote64: runtime.cc:524]   native: #44 pc 000000000012fb94  /system/lib64/libart.so (???)
A/zygote64: runtime.cc:524]   native: #45 pc 000000000026bf90  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+448)
A/zygote64: runtime.cc:524]   native: #46 pc 0000000000272854  /system/lib64/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+212)
A/zygote64: runtime.cc:524]   native: #47 pc 000000000028bdd0  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+640)
A/zygote64: runtime.cc:524]   native: #48 pc 0000000000126e44  /system/lib64/libart.so (???)
A/zygote64: runtime.cc:524]   native: #49 pc 000000000012fd14  /system/lib64/libart.so (???)
A/zygote64: runtime.cc:524]   native: #50 pc 000000000026bf90  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+448)
A/zygote64: runtime.cc:524]   native: #51 pc 0000000000272854  /system/lib64/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+212)
A/zygote64: runtime.cc:524]   native: #52 pc 000000000028bdd0  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+640)
A/zygote64: runtime.cc:524]   native: #53 pc 00000000001257f4  /system/lib64/libart.so (???)
A/zygote64: runtime.cc:524]   native: #54 pc 000000000012fb94  /system/lib64/libart.so (???)
A/zygote64: runtime.cc:524]   native: #55 pc 000000000026bf90  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+448)
A/zygote64: runtime.cc:524]   native: #56 pc 0000000000272854  /system/lib64/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+212)
A/zygote64: runtime.cc:524]   native: #57 pc 000000000028bdd0  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+640)
A/zygote64: runtime.cc:524]   native: #58 pc 00000000001257f4  /system/lib64/libart.so (???)
A/zygote64: runtime.cc:524]   native: #59 pc 000000000012fb94  /system/lib64/libart.so (???)
A/zygote64: runtime.cc:524]   native: #60 pc 000000000026bf90  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+448)
A/zygote64: runtime.cc:524]   native: #61 pc 0000000000272854  /system/lib64/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+212)
A/zygote64: runtime.cc:524]   native: #62 pc 000000000028bdd0  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+640)
A/zygote64: runtime.cc:524]   native: #63 pc 0000000000126e44  /system/lib64/libart.so (???)
A/zygote64: runtime.cc:524]   at com.secneo.sdk.Helper.makeInMemoryDexElements(Native method)
A/zygote64: runtime.cc:524]   at com.secneo.sdk.DexInstall.V26install(DexInstall.java:139)
A/zygote64: runtime.cc:524]   at com.secneo.sdk.DexInstall.installSecondaryDexes(DexInstall.java:71)
A/zygote64: runtime.cc:524]   at com.secneo.sdk.DexInstall.install(DexInstall.java:40)
A/zygote64: runtime.cc:524]   at com.secneo.sdk.Helper.install(Helper.java:43)
A/zygote64: runtime.cc:524]   at apps.unsignedusb.song.djiosmomobile.OsmoConnectorImpl$Provider.install(OsmoConnectorImpl.kt:32)
A/zygote64: runtime.cc:524]   at com.prism.live.common.dynamicfeatures.OsmoConnectorManager$Companion.install(OsmoConnectorManager.kt:29)
A/zygote64: runtime.cc:524]   at com.prism.live.common.dynamicfeatures.OsmoConnectorManager.install(OsmoConnectorManager.kt:-1)
A/zygote64: runtime.cc:524]   at com.prism.live.GLiveApplication.attachBaseContext(GLiveApplication.java:117)
A/zygote64: runtime.cc:524]   at android.app.Application.attach(Application.java:213)
A/zygote64: runtime.cc:524]   at android.app.Instrumentation.newApplication(Instrumentation.java:1109)
A/zygote64: runtime.cc:524]   at android.app.Instrumentation.newApplication(Instrumentation.java:1093)
A/zygote64: runtime.cc:524]   at android.app.LoadedApk.makeApplication(LoadedApk.java:971)
A/zygote64: runtime.cc:524]   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6030)
A/zygote64: runtime.cc:524]   at android.app.ActivityThread.-wrap1(ActivityThread.java:-1)
A/zygote64: runtime.cc:524]   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
A/zygote64: runtime.cc:524]   at android.os.Handler.dispatchMessage(Handler.java:105)
A/zygote64: runtime.cc:524]   at android.os.Looper.loop(Looper.java:164)
A/zygote64: runtime.cc:524]   at android.app.ActivityThread.main(ActivityThread.java:6938)
A/zygote64: runtime.cc:524]   at java.lang.reflect.Method.invoke(Native method)
A/zygote64: runtime.cc:524]   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
A/zygote64: runtime.cc:524]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
A/zygote64: runtime.cc:524] 
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 8254 (com.prism.live)

**Comment by accuware** [comment]
There are various threads dealing with Android X. Most are "doesn't work". They are aware, but I'm not sure if they care. This is not the platform to get help on any topic. But I don't know any other either. Tried various ways. Very poor support, to say it nicely.

**Comment by Michael-DJI** [comment]
@accuware AndroidX will be supported in next release (End of Sep)

**Comment by sumanhaque** [comment]
Thanks @accuware
