### ISSUE TITLE
Unable to extract the trust manager

### ISSUE THREAD

**Issue by jim-mcandrew** [dji-sdk/Mobile-SDK-Android#446]
Getting this error on first launch after install and upgrading to AndroidX / DJI SDK 4.11:

E/AndroidRuntime(15033): java.lang.IllegalStateException: Unable to extract the trust manager on dji.thirdparty.okhttp3.internal.platform.AndroidPlatform@2317d52, sslSocketFactory is class dji.thirdparty.afinal.utils.HttpsHelper$DJISSLSocketFactoryJavaX
E/AndroidRuntime(15033): 	at dji.thirdparty.okhttp3.internal.platform.Platform.buildCertificateChainCleaner(Unknown Source:46)
E/AndroidRuntime(15033): 	at dji.thirdparty.okhttp3.OkHttpClient$Builder.sslSocketFactory(Unknown Source:8)
E/AndroidRuntime(15033): 	at dji.csdkcommon.adapter.network.HttpUtil.a(Unknown Source:38)
E/AndroidRuntime(15033): 	at dji.csdkcommon.adapter.network.NetworkAdapter.sendCommonNetworkRequest(Unknown Source:126)
E/AndroidRuntime(15033): 	at dji.upgrade.internal.csdk.upgradeadapter.UpgradeAdapterManager.initialize(Native Method)
E/AndroidRuntime(15033): 	at dji.upgrade.internal.csdk.upgradeadapter.UpgradeAdapterManager.e(Unknown Source:40)
E/AndroidRuntime(15033): 	at dji.upgrade.internal.csdk.upgradeadapter.UpgradeAdapterManager.b(Unknown Source:2)
E/AndroidRuntime(15033): 	at dji.upgrade.internal.csdk.CSDKManager.a(Unknown Source:15)
E/AndroidRuntime(15033): 	at dji.upgrade.internal.UpgradeManagerImpl.a(Unknown Source:27)
E/AndroidRuntime(15033): 	at dji.sdk.sdkmanager.DJISDKManager.initParams(Unknown Source:24)
E/AndroidRuntime(15033): 	at dji.sdk.sdkmanager.DJISDKManager.initSDKManager(Unknown Source:253)
E/AndroidRuntime(15033): 	at dji.sdk.sdkmanager.DJISDKManager.registerApp(Unknown Source:45)
E/AndroidRuntime(15033): 	at dji.sdk.sdkmanager.DJISDKManager.access$600(Unknown Source:0)
E/AndroidRuntime(15033): 	at dji.sdk.sdkmanager.DJISDKManager$5$1.onDownloadSuccess(Unknown Source:6)
E/AndroidRuntime(15033): 	at dji.internal.flysafe.DJIFlySafeDBLoader.a(Unknown Source:19)
E/AndroidRuntime(15033): 	at dji.sdk.sdkmanager.DJISDKManager$5.run(Unknown Source:33)
E/AndroidRuntime(15033): 	at dji.sdksharedlib.util.DJISDKCacheThreadManager$1.run(Unknown Source:5)
E/AndroidRuntime(15033): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(15033): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(15033): 	at java.lang.Thread.run(Thread.java:764)

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/28768'>Zendesk ticket #28768</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
To help us collect questions in detail, please fill in the form below and we will handle this ticket once we have received it.
https://formcrafts.com/a/dji-developer-feedback-en

Thanks,

Luce Luo
DJI Dev Team

**Comment by matsjoe** [comment]
Having the same issue. Did you find any solution?
