### ISSUE TITLE
App crash after a successfully running it once

### ISSUE THREAD

**Issue by Marcello09** [dji-sdk/Mobile-SDK-Android#449]
Something strange is happening. My app runs the first time as expected, I can connect to the aircraft, see live video feed and everything. After I close my app and reopen it again, it crashes when it calls DJISDKManager.registerApp. Here is the following crashlog and configuration.

Mavic 2 Pro
Samsung Galaxy Tab A 10.1" (Wi-fi)
Android 9 - API 28
DJI MSDK 4.11

```
2019-11-06 15:22:54.886 9259-9286/? E/AndroidRuntime: FATAL EXCEPTION: DJIExecutor Urgent #1
    Process: br.com.aeroscan.aerolink, PID: 9259
    java.lang.ExceptionInInitializerError
        at dji.sdk.realname.aircraftbinding.CacheObjectManager$SingletonHolder.a(Unknown Source:0)
        at dji.sdk.realname.aircraftbinding.CacheObjectManager.getInstance(Unknown Source:0)
        at dji.sdk.realname.aircraftbinding.ServerHandler.b(Unknown Source:26)
        at dji.sdk.realname.AppActivationManager.init(Unknown Source:25)
        at dji.sdk.sdkmanager.DJISDKManager.initParams(Unknown Source:124)
        at dji.sdk.sdkmanager.DJISDKManager.initSDKManager(Unknown Source:253)
        at dji.sdk.sdkmanager.DJISDKManager.registerApp(Unknown Source:45)
        at dji.sdk.sdkmanager.DJISDKManager.access$600(Unknown Source:0)
        at dji.sdk.sdkmanager.DJISDKManager$5$1.onDownloadSuccess(Unknown Source:6)
        at dji.internal.flysafe.DJIFlySafeDBLoader.a(Unknown Source:19)
        at dji.sdk.sdkmanager.DJISDKManager$5.run(Unknown Source:33)
        at dji.sdksharedlib.util.DJISDKCacheThreadManager$1.run(Unknown Source:5)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.RuntimeException: Missing type parameter.
        at com.google.gson.reflect.TypeToken.getSuperclassTypeParameter(Unknown Source:26)
        at com.google.gson.reflect.TypeToken.<init>(Unknown Source:5)
        at dji.sdk.realname.aircraftbinding.CacheObjectManager$1.<init>(Unknown Source:2)
        at dji.sdk.realname.aircraftbinding.CacheObjectManager.d(Unknown Source:33)
        at dji.sdk.realname.aircraftbinding.CacheObjectManager.<init>(Unknown Source:21)
        at dji.sdk.realname.aircraftbinding.CacheObjectManager.<init>(Unknown Source:0)
        at dji.sdk.realname.aircraftbinding.CacheObjectManager$SingletonHolder.<clinit>(Unknown Source:3)
        at dji.sdk.realname.aircraftbinding.CacheObjectManager$SingletonHolder.a(Unknown Source:0) 
        at dji.sdk.realname.aircraftbinding.CacheObjectManager.getInstance(Unknown Source:0) 
        at dji.sdk.realname.aircraftbinding.ServerHandler.b(Unknown Source:26) 
        at dji.sdk.realname.AppActivationManager.init(Unknown Source:25) 
        at dji.sdk.sdkmanager.DJISDKManager.initParams(Unknown Source:124) 
        at dji.sdk.sdkmanager.DJISDKManager.initSDKManager(Unknown Source:253) 
        at dji.sdk.sdkmanager.DJISDKManager.registerApp(Unknown Source:45) 
        at dji.sdk.sdkmanager.DJISDKManager.access$600(Unknown Source:0) 
        at dji.sdk.sdkmanager.DJISDKManager$5$1.onDownloadSuccess(Unknown Source:6) 
        at dji.internal.flysafe.DJIFlySafeDBLoader.a(Unknown Source:19) 
        at dji.sdk.sdkmanager.DJISDKManager$5.run(Unknown Source:33) 
        at dji.sdksharedlib.util.DJISDKCacheThreadManager$1.run(Unknown Source:5) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
2019-11-06 15:22:54.939 9259-9286/? E/UsbAccessoryService: final destroy() 71
```

**Comment by dji-dev** [comment]
Public comment from Lisa Fedane in <a href='https://djisdksupport.zendesk.com/agent/tickets/29623'>Zendesk ticket #29623</a>:<br><br>Can you run an unmodified version of the 4.11 Android Sample App in the same environment with the same steps and tell me if you get the crash?

Lisa Fedane
DJI Developer Support

**Comment by Marcello09** [comment]
Will do tomorrow and get back to you.

I've find a way to run the app by disabling pro-guard.

My pro-guard file is the following. 

```
# Add project specific ProGuard rules here.
# You can control the set of applied configuration files using the
# proguardFiles setting in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
#-keepclassmembers class fqcn.of.javascript.interface.for.webview {
#   public *;
#}

# Uncomment this to preserve the line number information for
# debugging stack traces.
#-keepattributes SourceFile,LineNumberTable

# If you keep the line number information, uncomment this to
# hide the original source file name.
#-renamesourcefileattribute SourceFile
-keepattributes Exceptions,InnerClasses,*Annotation*,Signature,EnclosingMethod

-dontoptimize
-dontpreverify
-dontwarn okio.**
-dontwarn org.bouncycastle.**
-dontwarn dji.**
-dontwarn com.dji.**
-dontwarn sun.**
-dontwarn java.**
-dontwarn com.amap.api.**
-dontwarn com.here.**
-dontwarn com.mapbox.**
-dontwarn okhttp3.**
-dontwarn retrofit2.**

-keepclassmembers enum * {
    public static <methods>;
}

-keepnames class * implements java.io.Serializable
-keepclassmembers class * implements java.io.Serializable {
    static final long serialVersionUID;
    private static final java.io.ObjectStreamField[] serialPersistentFields;
    !static !transient <fields>;
    private void writeObject(java.io.ObjectOutputStream);
    private void readObject(java.io.ObjectInputStream);
    java.lang.Object writeReplace();
    java.lang.Object readResolve();
}
-keep class * extends android.os.Parcelable {
    public static final android.os.Parcelable$Creator *;
}

-keep,allowshrinking class * extends dji.publics.DJIUI.** {
    public <methods>;
}

-keep class net.sqlcipher.** { *; }

-keep class net.sqlcipher.database.* { *; }

-keep class dji.** { *; }

-keep class com.dji.** { *; }

-keep class com.google.** { *; }

-keep class org.bouncycastle.** { *; }

-keep,allowshrinking class org.** { *; }

-keep class com.squareup.wire.** { *; }

-keep class sun.misc.Unsafe { *; }

-keep class com.secneo.** { *; }

-keep class org.greenrobot.eventbus.**{*;}

-keepclasseswithmembers,allowshrinking class * {
    native <methods>;
}

-keep class * implements com.google.gson.TypeAdapterFactory
-keep class * implements com.google.gson.JsonSerializer
-keep class * implements com.google.gson.JsonDeserializer

-keep class androidx.appcompat.widget.SearchView { *; }

-keepclassmembers class * extends android.app.Service
-keepclassmembers public class * extends android.view.View {
    void set*(***);
    *** get*();
}
-keepclassmembers class * extends android.app.Activity {
    public void *(android.view.View);
}
-keep class androidx.** { *; }
-keep class android.media.** { *; }
-keep class okio.** { *; }
-keep class com.lmax.disruptor.** {
    *;
}

-dontwarn com.mapbox.services.android.location.LostLocationEngine
-dontwarn com.mapbox.services.android.location.MockLocationEngine
-keepclassmembers class * implements android.arch.lifecycle.LifecycleObserver {
    <init>(...);
}
# ViewModel's empty constructor is considered to be unused by proguard
-keepclassmembers class * extends android.arch.lifecycle.ViewModel {
    <init>(...);
}
# keep Lifecycle State and Event enums values
-keepclassmembers class android.arch.lifecycle.Lifecycle$State { *; }
-keepclassmembers class android.arch.lifecycle.Lifecycle$Event { *; }
# keep methods annotated with @OnLifecycleEvent even if they seem to be unused
# (Mostly for LiveData.LifecycleBoundObserver.onStateChange(), but who knows)
-keepclassmembers class * {
    @android.arch.lifecycle.OnLifecycleEvent *;
}

-keepclassmembers class * implements android.arch.lifecycle.LifecycleObserver {
    <init>(...);
}

-keep class * implements android.arch.lifecycle.LifecycleObserver {
    <init>(...);
}
-keepclassmembers class android.arch.** { *; }
-keep class android.arch.** { *; }
-dontwarn android.arch.**

-keepattributes Exceptions,InnerClasses,*Annotation*,Signature,EnclosingMethod

-dontwarn okio.**
-dontwarn org.bouncycastle.**
-dontwarn dji.**
-dontwarn com.dji.**
-dontwarn sun.**
-dontwarn java.**

-keepclassmembers enum * {
    public static <methods>;
}

-keepnames class * implements java.io.Serializable
-keepclassmembers class * implements java.io.Serializable {
    static final long serialVersionUID;
    private static final java.io.ObjectStreamField[] serialPersistentFields;
    !static !transient <fields>;
    private void writeObject(java.io.ObjectOutputStream);
    private void readObject(java.io.ObjectInputStream);
    java.lang.Object writeReplace();
    java.lang.Object readResolve();
}
-keep class * extends android.os.Parcelable {
    public static final android.os.Parcelable$Creator *;
}

-keep,allowshrinking class * extends dji.publics.DJIUI.** {
    public <methods>;
}

-keep class net.sqlcipher.** { *; }

-keep class net.sqlcipher.database.* { *; }

-keep class dji.** { *; }

-keep class com.dji.** { *; }

-keep class com.google.** { *; }

-keep class org.bouncycastle.** { *; }

-keep,allowshrinking class org.** { *; }

-keep class com.squareup.wire.** { *; }

-keep class sun.misc.Unsafe { *; }

-keep class com.secneo.** { *; }

-keepclasseswithmembers,allowshrinking class * {
    native <methods>;
}

-keep class * implements com.google.gson.TypeAdapterFactory
-keep class * implements com.google.gson.JsonSerializer
-keep class * implements com.google.gson.JsonDeserializer

-keep class android.support.v7.widget.SearchView { *; }

-keepclassmembers class * extends android.app.Service
-keepclassmembers public class * extends android.view.View {
    void set*(***);
    *** get*();
}
-keepclassmembers class * extends android.app.Activity {
    public void *(android.view.View);
}
-keep class android.support.** { *; }
-keep class android.media.** { *; }
-keep class okio.** { *; }
-keep class com.lmax.disruptor.** {
    *;
}
```

**Comment by Hoker-** [comment]
@Marcello09 you mean when you disable pro-guard, it works well?
maybe you can try this one. https://github.com/dji-sdk/Mobile-SDK-Android/blob/master/Sample%20Code/app/proguard-rules.pro

**Comment by straule** [comment]
Did you solve this problem? I am running into exactly the same exception that the app will crash after starting it the second time.
Mavic 2 Pro
Sony Xperia XZ Premium
Android 9 - API 28
DJI MSDK 4.11
None of the above mentioned proguard files help. Disabling pro guard completely makes the problem disappear.

**Comment by Marcello09** [comment]
It worked for me to disable pro-guard for now... I´ve tried to use the pro-guard file @Hoker- suggested but did not resolve the issue. 
I intend to give another try using pro-guard in the folowing weeks since I'm rewoking the hole app.

**Comment by Hoker-** [comment]
@Marcello09 what is your gradle plugin version ,i try on  'com.android.tools.build:gradle:3.2.1' and i can not reproduce it . and do you have the same problem on 4.11 sample?

**Comment by Marcello09** [comment]
@Hoker- Currently using Grande 3.4.0.

**Comment by Hoker-** [comment]
@Marcello09 do you have the same problem on 4.11 sample？

**Comment by Marcello09** [comment]
Haven't tried with 4.11 sample
