### ISSUE TITLE
app crash after upgrading sdk 4.10 to 4.11

### ISSUE THREAD

**Issue by pelosi** [dji-sdk/Mobile-SDK-Android#450]
I upgraded mobile sdk v 4.10 to v 4.11 (android)

After upgraing,

dji mobile sdk for android will throw exception at runtime as belows:

> 2019-11-11 15:07:15.759 29836-29948 E/AndroidRuntime: FATAL EXCEPTION: DJIExecutor Urgent #1
>     java.lang.UnsatisfiedLinkError: No implementation found for void dji.upgrade.internal.csdk.upgradeadapter.UpgradeAdapterManager.setFirmwareStoreDirectory(java.lang.String) (tried Java_dji_upgrade_internal_csdk_upgradeadapter_UpgradeAdapterManager_setFirmwareStoreDirectory and Java_dji_upgrade_internal_csdk_upgradeadapter_UpgradeAdapterManager_setFirmwareStoreDirectory__Ljava_lang_String_2)
>         at dji.upgrade.internal.csdk.upgradeadapter.UpgradeAdapterManager.setFirmwareStoreDirectory(Native Method)
>         at dji.upgrade.internal.csdk.upgradeadapter.UpgradeAdapterManager.e(Unknown Source:12)
>         at dji.upgrade.internal.csdk.upgradeadapter.UpgradeAdapterManager.b(Unknown Source:2)
>         at dji.upgrade.internal.csdk.CSDKManager.a(Unknown Source:15)
>         at dji.upgrade.internal.UpgradeManagerImpl.a(Unknown Source:27)
>         at dji.sdk.sdkmanager.DJISDKManager.initParams(Unknown Source:24)
>         at dji.sdk.sdkmanager.DJISDKManager.initSDKManager(Unknown Source:253)
>         at dji.sdk.sdkmanager.DJISDKManager.registerApp(Unknown Source:45)
>         at dji.sdk.sdkmanager.DJISDKManager.access$600(Unknown Source:0)
>         at dji.sdk.sdkmanager.DJISDKManager$5$1.onDownloadSuccess(Unknown Source:6)
>         at dji.internal.flysafe.DJIFlySafeDBLoader.a(Unknown Source:19)
>         at dji.sdk.sdkmanager.DJISDKManager$5.run(Unknown Source:33)
>         at dji.sdksharedlib.util.DJISDKCacheThreadManager$1.run(Unknown Source:5)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>         at java.lang.Thread.run(Thread.java:764)
> 2019-11-11 15:07:17.306 29836-29836/com.jchyun.dronerts D/AndroidRuntime: Shutting down VM
> 2019-11-11 15:07:17.311 29836-29836/com.jchyun.dronerts E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.jchyun.dronerts, PID: 29836
>     java.lang.UnsatisfiedLinkError: No implementation found for void dji.csdkcommon.CommonNative.updateSystemState(int) (tried Java_dji_csdkcommon_CommonNative_updateSystemState and Java_dji_csdkcommon_CommonNative_updateSystemState__I)
>         at dji.csdkcommon.CommonNative.updateSystemState(Native Method)
>         at dji.csdkcommon.adapter.event.SystemEventAdapter.onPhoneLocationChanged(Unknown Source:1)
>         at dji.csdkcommon.adapter.event.SystemEventAdapter.access$000(Unknown Source:0)
>         at dji.csdkcommon.adapter.event.SystemEventAdapter$1.onLocationChanged(Unknown Source:2)
>         at dji.internal.util.location.PhoneLocationProvider$LocationListener.onLocationChanged(Unknown Source:112)
>         at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:388)
>         at android.location.LocationManager$ListenerTransport.access$000(LocationManager.java:300)
>         at android.location.LocationManager$ListenerTransport$2.handleMessage(LocationManager.java:323)
>         at android.os.Handler.dispatchMessage(Handler.java:106)
>         at android.os.Looper.loop(Looper.java:214)
>         at android.app.ActivityThread.main(ActivityThread.java:7080)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
>

**Comment by kenargo** [comment]
What is your gradle version? You cannot use the latest gradle,  you need to use one minor version lower. 

⁣Get BlueMail for Android ​

**Comment by MRwangqi** [comment]
@kenargo 
classpath 'com.android.tools.build:gradle:3.4.1' 

Still so

**Comment by kenargo** [comment]
Try 3.5.1

⁣Get BlueMail for Android ​

**Comment by Michael-DJI** [comment]
Hi, 4.11 add some new so files needed to be kept in build.gradle, please check
https://github.com/dji-sdk/Mobile-SDK-Android/blob/master/Sample%20Code/app/build.gradle
It is better to check the sample app when upgrade the sdk version.

packagingOptions {

    doNotStrip "*/*/libdjivideo.so"
    doNotStrip "*/*/libSDKRelativeJNI.so"
    doNotStrip "*/*/libFlyForbid.so"
    doNotStrip "*/*/libduml_vision_bokeh.so"
    doNotStrip "*/*/libyuv2.so"
    doNotStrip "*/*/libGroudStation.so"
    doNotStrip "*/*/libFRCorkscrew.so"
    doNotStrip "*/*/libUpgradeVerify.so"
    doNotStrip "*/*/libFR.so"
    doNotStrip "*/*/libDJIFlySafeCore.so"
    doNotStrip "*/*/libdjifs_jni.so"
    doNotStrip "*/*/libsfjni.so"
    doNotStrip "*/*/libDJICommonJNI.so"
    doNotStrip "*/*/libDJICSDKCommon.so"
    doNotStrip "*/*/libDJIUpgradeCore.so"
    doNotStrip "*/*/libDJIUpgradeJNI.so"
    exclude 'META-INF/rxjava.properties'
}
