### ISSUE TITLE
Mobile SDK 4.11升级问题

### ISSUE THREAD

**Issue by johnchenn** [dji-sdk/Mobile-SDK-Android#459]
大疆的工作人员，您好：
    问题描述：更新 Mobile SDK 4.11 版本后，程序运行一段时间后闪退，查看日志发现奔溃日志如下，由于提示crash在dji_background_thread线程，无法定位问题，该crash只在编译release包时采用混淆后发生，不混淆时不会crash。希望贵团队帮忙分析原因，感谢。PS：该crash在调用getSmartReturnToHomeEnabled 接口后必现
使用机型：Phantom4 Pro
Android 设备：小米Pad4 
android version：android 8

11-26 14:46:59.393 8168 8347 E AndroidRuntime: FATAL EXCEPTION: dji_background_thread
--
15311-26 14:46:59.393 8168 8347 E AndroidRuntime: Process:  PID: 8168
15411-26 14:46:59.393 8168 8347 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'java.lang.Number dji.midware.data.params.P3.ParamInfo.value' on a null object reference
15511-26 14:46:59.393 8168 8347 E AndroidRuntime: at dji.internal.logics.FPVTipLogic.updateParamStatus(Unknown Source:18)
15611-26 14:46:59.393 8168 8347 E AndroidRuntime: at dji.internal.logics.FPVTipLogic.access$700(Unknown Source:0)
15711-26 14:46:59.393 8168 8347 E AndroidRuntime: at dji.internal.logics.FPVTipLogic$TipHandler.handleMessage(Unknown Source:32)
15811-26 14:46:59.393 8168 8347 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:106)
15911-26 14:46:59.393 8168 8347 E AndroidRuntime: at android.os.Looper.loop(Looper.java:173)
16011-26 14:46:59.393 8168 8347 E AndroidRuntime: at android.os.HandlerThread.run(HandlerThread.java:65)
16111-26 14:46:59.478 8168 8347 E UsbAccessoryService: final destroy() 71
16211-26 14:46:59.578 8168 8347 E UsbAccessoryService: final destroy() 72
16311-26 14:46:59.579 8168 8347 E wm220 : ****resetSwitchFromWifiFlag
16411-26 14:46:59.581 8168 8347 E DJIUsbAccessoryReceiver: receiver destroySession
16511-26 14:46:59.581 8168 8347 E UsbAccessoryService: final destroy() 73
16611-26 14:46:59.581 8168 8347 E UsbAccessoryService: final destroy() 75
16711-26 14:46:59.582 8168 8347 E UsbAccessoryService: final destroy() 76
16811-26 14:46:59.582 8168 8347 E DJICrashHandler: uncaughtException 3

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/30204'>Zendesk ticket #30204</a>:<br><br>尊敬的用户，

您好！感谢您联系DJI 大疆创新。
为了快速收集问题细节，麻烦您详细填写如下表格。
https://formcrafts.com/a/dji-developer-feedback-cn

在收到您的详细细节信息后，我们将会进行快速处理。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持

**Comment by johnchenn** [comment]
@dji-dev 问题已解决，是由于gradle 版本升级到3.5.1导致在混淆情况下调用getSmartReturnToHomeEnabled 接口，必现crash。降低gradle版本3.2.1，问题不在出现。但不知道原因，如果有分析原因，请告知

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/30204'>Zendesk ticket #30204</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
抱歉，客服这边为您将问题反馈给技术人员做进一步确认，如果有任何进展，我们将会再次联系您。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/30204'>Zendesk ticket #30204</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
十分抱歉，工程师回复后续会安排人力调查，建议您关注后续版本。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持

**Comment by Jai-GAY** [comment]
[change targetSdkVersion 29 build.gradle](https://github.com/dji-sdk/Mobile-SDK-Android/blob/v4.11.1/Sample%20Code/app/build.gradle) will crash on App run.

[4.11.1](https://github.com/dji-sdk/Mobile-SDK-Android/releases/tag/v4.11.1)
