### ISSUE TITLE
Calling goHome on FlightController throws internal Rx exception.

### ISSUE THREAD

**Issue by jtuchek** [dji-sdk/Mobile-SDK-Android#46]
SDK Version: 3.4
Android Devices

Nexus 9: API 24
Nexus 6P: API 25
DJI Devices
Phantom 3 Professional
--Remote Controller Firmware: 1.6.0
--Flight Controller Firmware: 2.04.14.05
--Gimbal Firmware: 01.44.00.00
--Camera Firmware: 01.30.50.36
Inspire 1 Pro
--Remote Controller Firmware: 1.7.4.0
--Flight Controller Firmware: 2.0.4.20.18
--Gimbal Firmware: 1.29.00.92
--Camera Firmware: 1.9.1.10

When a mission is playing, calling goHome on the flight controller will sometimes cause an exception to be thrown. for `rx.exceptions.OnErrorNotImplementedException` and says to contact for developer support.

11-08 09:55:45.592 15892-16003/com.botlink.app E/UncaughtException: rx.exceptions.OnErrorNotImplementedException: Server error, please contact <dev@dji.com> for help.
                                                                        at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
                                                                        at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
                                                                        at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
                                                                        at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:152)
                                                                        at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
                                                                        at rx.internal.operators.OnSubscribeFromEmitter$BaseAsyncEmitter.onError(OnSubscribeFromEmitter.java:143)
                                                                        at rx.internal.operators.OnSubscribeFromEmitter$BufferAsyncEmitter.drain(OnSubscribeFromEmitter.java:392)
                                                                        at rx.internal.operators.OnSubscribeFromEmitter$BufferAsyncEmitter.onError(OnSubscribeFromEmitter.java:343)
                                                                        at com.botlink.app.data.connection.dji.function.DJIFunction$1.onResult(DJIFunction.java:23)
                                                                        at dji.internal.a.b.run(Unknown Source)
                                                                        at android.os.Handler.handleCallback(Handler.java:751)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                     Caused by: com.botlink.app.data.connection.dji.extras.DJIException: Server error, please contact <dev@dji.com> for help.
                                                                        at com.botlink.app.data.connection.dji.function.DJIFunction$1.onResult(DJIFunction.java:23) 
                                                                        at dji.internal.a.b.run(Unknown Source) 
                                                                        at android.os.Handler.handleCallback(Handler.java:751) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                        at android.os.Looper.loop(Looper.java:154) 
                                                                        at android.os.HandlerThread.run(HandlerThread.java:61) 
11-08 09:55:45.804 15892-16003/com.botlink.app D/FirebaseCrashApiImpl: throwable rx.exceptions.OnErrorNotImplementedException: Server error, please contact <dev@dji.com> for help.
11-08 09:55:45.898 15892-16003/com.botlink.app E/AndroidRuntime: FATAL EXCEPTION: dji_background_thread
                                                                 Process: com.botlink.app, PID: 15892
                                                                 rx.exceptions.OnErrorNotImplementedException: Server error, please contact <dev@dji.com> for help.
                                                                     at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
                                                                     at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
                                                                     at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
                                                                     at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:152)
                                                                     at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
                                                                     at rx.internal.operators.OnSubscribeFromEmitter$BaseAsyncEmitter.onError(OnSubscribeFromEmitter.java:143)
                                                                     at rx.internal.operators.OnSubscribeFromEmitter$BufferAsyncEmitter.drain(OnSubscribeFromEmitter.java:392)
                                                                     at rx.internal.operators.OnSubscribeFromEmitter$BufferAsyncEmitter.onError(OnSubscribeFromEmitter.java:343)
                                                                     at com.botlink.app.data.connection.dji.function.DJIFunction$1.onResult(DJIFunction.java:23)
                                                                     at dji.internal.a.b.run(Unknown Source)
                                                                     at android.os.Handler.handleCallback(Handler.java:751)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                  Caused by: com.botlink.app.data.connection.dji.extras.DJIException: Server error, please contact <dev@dji.com> for help.
                                                                     at com.botlink.app.data.connection.dji.function.DJIFunction$1.onResult(DJIFunction.java:23) 
                                                                     at dji.internal.a.b.run(Unknown Source) 
                                                                     at android.os.Handler.handleCallback(Handler.java:751) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                     at android.os.Looper.loop(Looper.java:154) 
                                                                     at android.os.HandlerThread.run(HandlerThread.java:61) 
11-08 09:55:46.460 582-633/? E/ConnectivityService: RemoteException caught trying to send a callback msg for NetworkRequest [ id=39, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]

**Comment by jtuchek** [comment]
I have tried stopping the mission before telling the flight controller to return home, and now it is yielding the same exception as above.

**Comment by oliverou** [comment]
Hi @jtuchek , after testing, we cannot reproduce the issue. We will launch a new version of Android SDK very soon. You can try if it's fixed then. Thanks!

**Comment by oliverou** [comment]
Hi @jtuchek, we have launched the Android SDK 3.4.1, please try this new version and check if the issue still exist. Thanks!
