### ISSUE TITLE
Attempt to read from field 'java.lang.String dji.log.DJILogFileConfig.LOG_PATH_ROOT' on a null object reference

### ISSUE THREAD

**Issue by chinobot-zj** [dji-sdk/Mobile-SDK-Android#464]
集成mobile sdk，每次第一次安装app就崩溃，之后打开是好的
java.lang.NullPointerException: Attempt to read from field 'java.lang.String dji.log.DJILogFileConfig.LOG_PATH_ROOT' on a null object reference
        at dji.log.DJILogFileManager.getCachePath(DJILogFileManager.java:51)
        at dji.log.DJILogFileManager.getCachePath(DJILogFileManager.java:55)
        at dji.log.DJILogHelper.getCachePath(DJILogHelper.java:186)
        at dji.log.DJILogHelper.saveLog(DJILogHelper.java:321)
        at dji.log.DJILogHelper.saveLog(DJILogHelper.java:317)
        at dji.log.DJILogHelper.saveLog(DJILogHelper.java:313)
        at dji.log.DJILog.saveLog(DJILog.java:251)
        at dji.midware.media.SaveLogHelper$1.handleMessage()
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/30650'>Zendesk ticket #30650</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
这个错误一般常见于registerApp没有返回成功，却调用了其他MSDK接口导致。
建议您确保registerApp成功后再去调用MSDK其他接口。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持

**Comment by kin0201** [comment]
你好，我也遇到相同的問題，請問如何解決？

**Comment by mayurpatil307** [comment]
Hi,
I am facing the same crash, although I have ensured to call MSDK interfaces only after SDK is successfully registered.

**Comment by jeryini** [comment]
I can confirm this, crash is happening even though I make sure 100% taht call to `registerApp` was successful. Something else is in play here. cc. @dji-dev

**Comment by DJI-William** [comment]
@jeryini The crash is cannot find a file I think, we will look at this. Can you reproduce this on 4.15.1 version? I have never met this crash before.
