### ISSUE TITLE
SDK 4.11 waypoint mission crash

### ISSUE THREAD

**Issue by SerjTech** [dji-sdk/Mobile-SDK-Android#465]
Using the new SDK (v4.11), I am not capable of launching waypoint missions. 

Every time the method checkParameters() from the Waypoint class is executed, a null pointer exception is launched and the app stops working. 

I had a previously fully functional version of the app (SDK version 4.10) where all missions worked fine and the only changes I implemented between both versions was updating to this SDK v4.11.

Here is a extract of the error log:

```
E/AndroidRuntime(12935): java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
E/AndroidRuntime(12935):     at dji.common.mission.waypoint.Waypoint.checkParameters()
E/AndroidRuntime(12935):     at dji.common.mission.MissionUtils.checkEachWaypointValid()
E/AndroidRuntime(12935):     at dji.common.mission.MissionUtils.checkWaypointMissionParameters()
E/AndroidRuntime(12935):     at dji.common.mission.waypoint.WaypointMission$Builder.checkParameters()
E/AndroidRuntime(12935):     at dji.internal.mission.abstraction.waypoint.WaypointMissionAbstraction.a()
E/AndroidRuntime(12935):     at dji.sdk.mission.waypoint.WaypointMissionOperator.loadMission()
```

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/30825'>Zendesk ticket #30825</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Sorry, this issue has been fixed in the latest v4.11.1.
Please update to it.

Thanks,

Luce Luo
DJI Dev Team
