### ISSUE TITLE
SDK 4.11.1 DJIVersionDM368Component crash 

### ISSUE THREAD

**Issue by 0xm1nam0** [dji-sdk/Mobile-SDK-Android#467]
HuaWei MatePad Android 10
log:
E/DJIVersionDM368Component: org.xmlpull.v1.XmlPullParserException: Unexpected EOF (position:START_TAG <module id='0801' version='10.00.10.04' type='' group='ac' order='2' wait='0' size='187068576' md5='b067b51a832808ce����������������Ի��,����������������������ܻ��p~o�?��J#o������������������軨���������������������軤� o�����������������������������������������������������������������������������t�t�����������������'>@18:261 in java.io.InputStreamReader@4fcece1) 
        at com.android.org.kxml2.io.KXmlParser.checkRelaxed(KXmlParser.java:305)
        at com.android.org.kxml2.io.KXmlParser.parseStartTag(KXmlParser.java:1066)
        at com.android.org.kxml2.io.KXmlParser.next(KXmlParser.java:372)
        at com.android.org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
        at dji.internal.version.component.DJIVersionDM368Component.a(Unknown Source:157)
        at dji.internal.version.component.DJIVersionDM368Component.a(Unknown Source:0)
        at dji.internal.version.component.DJIVersionDM368Component$1.onSuccess(Unknown Source:156)
        at dji.midware.data.manager.P3.DataBase.callbackSuccess(Unknown Source:4)
        at dji.midware.data.manager.P3.DataBase.access$100(Unknown Source:0)
        at dji.midware.data.manager.P3.DataBase$3.call(Unknown Source:92)
        at dji.midware.data.manager.P3.DataBase$3.call(Unknown Source:0)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/31372'>Zendesk ticket #31372</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
To help us collect questions in detail, please fill in the form below and we will handle this ticket once we have received it.
https://formcrafts.com/a/dji-developer-feedback-en

Thanks,

Luce Luo
DJI Dev Team
