### ISSUE TITLE
Crash before granting permissions SDK v3.4 on Android 6.0

### ISSUE THREAD

**Issue by biskazz** [dji-sdk/Mobile-SDK-Android#47]
Hi guys, 
There is an issue with the latest version of the SDK on Android 6.0 (tested on Note 4 but probably present on other devices too). I have tested on 3 different applications and getting the same crash. I have tested on the FPV Demo, SDK Sample Code Demo and my own application. Compiling on latest current version of Android Studio.
As far as I understand the SDK uses something before permissions are granted. The issue is only present when permissions are not granted. e.g. on first start after install.
This is the error
```
E/DJICrashHandler: uncaughtException 4
E/AndroidRuntime: FATAL EXCEPTION: Thread-6770
                  Process: com.dji.sdk.sample, PID: 24895
                  java.lang.SecurityException: getDeviceId: Neither user 10225 nor current process has android.permission.READ_PHONE_STATE.
                      at android.os.Parcel.readException(Parcel.java:1620)
                      at android.os.Parcel.readException(Parcel.java:1573)
                      at com.android.internal.telephony.ITelephony$Stub$Proxy.getDeviceId(ITelephony.java:5371)
                      at android.telephony.TelephonyManager.getDeviceId(TelephonyManager.java:812)
                      at dji.internal.e.b.i(Unknown Source)
                      at dji.internal.e.b.c(Unknown Source)
                      at dji.internal.e.b.a(Unknown Source)
                      at dji.internal.e.c.run(Unknown Source)
```

**Comment by biskazz** [comment]
Issue still seems to be present on 3.4.1. Same error:

`11-14 14:33:36.575 9184-9438/com.dji.FPVDemo E/DJICrashHandler: uncaughtException 2
11-14 14:33:36.580 9184-9438/com.dji.FPVDemo E/UsbAccessoryService: final destroy() 71
11-14 14:33:36.610 9184-9445/com.dji.FPVDemo I/System.out: FinalHttp #2 calls detatch()
11-14 14:33:36.680 9184-9438/com.dji.FPVDemo E/UsbAccessoryService: final destroy() 72
11-14 14:33:36.680 9184-9438/com.dji.FPVDemo E/wm220: ****resetSwitchFromWifiFlag
11-14 14:33:36.680 9184-9438/com.dji.FPVDemo E/DJIUsbAccessoryReceiver: receiver destroySession
11-14 14:33:36.680 9184-9438/com.dji.FPVDemo E/UsbAccessoryService: final destroy() 73
11-14 14:33:36.680 9184-9438/com.dji.FPVDemo E/UsbAccessoryService: final destroy() 75
11-14 14:33:36.680 9184-9438/com.dji.FPVDemo E/UsbAccessoryService: final destroy() 76
11-14 14:33:36.680 9184-9438/com.dji.FPVDemo E/DJICrashHandler: uncaughtException 3
11-14 14:33:36.880 9184-9438/com.dji.FPVDemo E/DJICrashHandler: uncaughtException 4
11-14 14:33:36.880 9184-9438/com.dji.FPVDemo E/AndroidRuntime: FATAL EXCEPTION: Thread-11517
                                                               Process: com.dji.FPVDemo, PID: 9184
                                                               java.lang.SecurityException: getDeviceId: Neither user 10239 nor current process has android.permission.READ_PHONE_STATE.
                                                                   at android.os.Parcel.readException(Parcel.java:1620)
                                                                   at android.os.Parcel.readException(Parcel.java:1573)
                                                                   at com.android.internal.telephony.ITelephony$Stub$Proxy.getDeviceId(ITelephony.java:5371)
                                                                   at android.telephony.TelephonyManager.getDeviceId(TelephonyManager.java:812)
                                                                   at dji.internal.e.b.i(Unknown Source)
                                                                   at dji.internal.e.b.c(Unknown Source)
                                                                   at dji.internal.e.b.a(Unknown Source)
                                                                   at dji.internal.e.c.run(Unknown Source)`

**Comment by SilverChangjian** [comment]
Hi thank you for you reporting this issue. This bug is relative to the run time permission grant, developers should initialize the SDK only after the permission is granted in 6.0 version. Our developer will update the sample code and provide a precise life cycle of DJI SDK in android 6.0 in the coming future.

**Comment by biskazz** [comment]
Thanks.
