### ISSUE TITLE
Not found Base64Fog

### ISSUE THREAD

**Issue by luoyexk** [dji-sdk/Mobile-SDK-Android#485]
```

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/dji/megatronking/stringfog/lib/Base64Fog;
--
7002-22 14:23:38.017 20137 20167 E AndroidRuntime: at dji.sdk.sdkmanager.DJISDKManager.<clinit>(Unknown Source:2)
7102-22 14:23:38.017 20137 20167 E AndroidRuntime: at dji.sdk.sdkmanager.DJISDKManager.getInstance(Unknown Source:0)
7202-22 14:23:38.017 20137 20167 E AndroidRuntime: at b.com.module_drone.dji.DjiManage$register$1.run(DjiManage.kt:52)
7302-22 14:23:38.017 20137 20167 E AndroidRuntime: at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
7402-22 14:23:38.017 20137 20167 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
7502-22 14:23:38.017 20137 20167 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
7602-22 14:23:38.017 20137 20167 E AndroidRuntime: at java.lang.Thread.run(Thread.java:764)

```

Class Base64Fog in library  ``'com.dji:dji-sdk-provided:4.11.1'``
My build.gradle has added compileOnly 'com.dji:dji-sdk-provided:4.11.1', but crashed when tablet of samsung SM T860 run my app. App works fine on other phones.

**Comment by luoyexk** [comment]
my build.gradle

```
if (isModule.toBoolean()) {
    apply plugin: 'com.android.application'
} else {
    apply plugin: 'com.android.library'
}
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'
//apply plugin: 'cn.leo.plugin.magic'
android {
    compileSdkVersion rootProject.ext.android.compileSdkVersion

    defaultConfig {
        minSdkVersion rootProject.ext.android.minSdkVersion
        targetSdkVersion rootProject.ext.android.targetSdkVersion
        versionCode rootProject.ext.android.versionCode
        versionName rootProject.ext.android.versionName

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true

        kapt {
            arguments {
                arg("moduleName", project.getName())
            }
        }

        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a'
        }
    }


    buildTypes {
        release {
            postprocessing {
                removeUnusedCode false
                removeUnusedResources false
                obfuscate false
                optimizeCode false
                proguardFile 'proguard-rules.pro'
            }
        }
    }
    sourceSets {
        main {
            if (isModule.toBoolean()) {
                manifest.srcFile 'src/main/module/AndroidManifest.xml'
            } else {
                manifest.srcFile 'src/main/AndroidManifest.xml'
                java {
                    exclude 'debug/**'
                }
            }
        }
    }
    lintOptions {
        abortOnError false
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    packagingOptions {
        doNotStrip "*/*/libdjivideo.so"
        doNotStrip "*/*/libSDKRelativeJNI.so"
        doNotStrip "*/*/libFlyForbid.so"
        doNotStrip "*/*/libduml_vision_bokeh.so"
        doNotStrip "*/*/libyuv2.so"
        doNotStrip "*/*/libGroudStation.so"
        doNotStrip "*/*/libFRCorkscrew.so"
        doNotStrip "*/*/libUpgradeVerify.so"
        doNotStrip "*/*/libFR.so"
        doNotStrip "*/*/libDJIFlySafeCore.so"
        doNotStrip "*/*/libdjifs_jni.so"
        doNotStrip "*/*/libsfjni.so"

        pickFirst 'lib/*/libstlport_shared.so'
        pickFirst 'lib/*/libRoadLineRebuildAPI.so'
        pickFirst 'lib/*/libGNaviUtils.so'
        pickFirst 'lib/*/libGNaviMapex.so'
        pickFirst 'lib/*/libGNaviData.so'
        pickFirst 'lib/*/libGNaviMap.so'
        pickFirst 'lib/*/libGNaviSearch.so'

        exclude 'META-INF/proguard/okhttp3.pro'
        exclude 'META-INF/rxjava.properties'
        exclude 'META-INF/rxjava-computation-expressions.properties'
    }

}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.0.0'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.0.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'

    testImplementation 'junit:junit:4.12'
    testImplementation "org.mockito:mockito-core:$dependVersion.mockitoVersion"
    testImplementation "org.mockito:mockito-inline:$dependVersion.mockitoVersion"
    testImplementation "com.nhaarman.mockitokotlin2:mockito-kotlin:$dependVersion.mockitoKotlinVersion"
    androidTestImplementation "org.mockito:mockito-android:$dependVersion.mockitoVersion"
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'

    api project(':lib_common')
    testImplementation 'junit:junit:4.12'
    kapt "com.alibaba:arouter-compiler:$dependVersion.arouterProcessorVersion"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    api("com.dji:dji-sdk:$dependVersion.djiSdkVersion", {
//             Uncomment the following line if your app does not need Anti Distortion for
//             Mavic 2 Pro and Mavic 2 Zoom. It will greatly reducing the size of the APK:
        exclude module: 'library-anti-distortion'
    })
    api("com.dji:dji-uxsdk:$dependVersion.djiSdkVersion", {
        exclude group: 'com.amap.api'
    })
    compileOnly "com.dji:dji-sdk-provided:$dependVersion.djiSdkVersion"
    implementation 'com.squareup:otto:1.3.8'
    implementation 'androidx.test:rules:1.2.0'
}

```

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/32384'>Zendesk ticket #32384</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
I'm not sure the root cause for the being time. You can try to change it to confirm first.
And here is an official sample, can you please run it in your Samsung SM T860 to check if the same problem still?
https://github.com/dji-sdk/Mobile-SDK-Android

Thanks,

Luce Luo
DJI Dev Team
