### ISSUE TITLE
Regular fatal exception due to missing resource

### ISSUE THREAD

**Issue by JamesMastermanDev** [dji-sdk/Mobile-SDK-Android#49]
Hi, I am seeing a regular fatal exception that crashes my app. It appears to be due to a missing resource within the SDK or at least passing 0 as a resource ID. I can't seem to nail down the exact steps to reproduce, it happens randomly but sometimes 3 or 4 times in a single flight. 

I've seen it most often when plugging in the USB cable, but also when downloading images while on the ground, or even during normal flight while simply ready telemetry. 

It happens regardless of the drone (Phantom 3, 4, inspire 1 and Mavic pro all seem to see it). I don't think it is drone related. 

This is with SDK 3.4 on Android. I've tested on Samsung Tab S2 8" and Samsung Galaxy S7 phones, same result on both (both running Android 6.0.1)

The stack trace is as follows

E/AndroidRuntime: FATAL EXCEPTION: Thread-3703                                             
                                                   android.content.res.Resources$NotFoundException: String resource ID #0x0
                                                       at android.content.res.Resources.getText(Resources.java:1468)
                                                       at android.content.res.Resources.getString(Resources.java:1564)
                                                       at dji.midware.g.a.a(Unknown Source)
                                                       at dji.midware.g.a.b(Unknown Source)
                                                       at dji.sdk.util.Util.getString(Unknown Source)
                                                       at dji.internal.c.j.a(Unknown Source)
                                                       at dji.internal.c.g.a(Unknown Source)
                                                       at dji.sdk.base.DJIBaseProduct$1.onDiagnosisUpdate(Unknown Source)
                                                       at dji.internal.c.f.c(Unknown Source)
                                                       at dji.internal.c.m.onSuccess(Unknown Source)
                                                       at dji.midware.data.manager.P3.u.callbackSuccess(Unknown Source)
                                                       at dji.midware.data.manager.P3.u.access$200(Unknown Source)
                                                       at dji.midware.data.manager.P3.w.run(Unknown Source)
                                                       at java.lang.Thread.run(Thread.java:818)

**Comment by oliverou** [comment]
Hi @JamesMastermanDev, thanks for reporting this bug. We have already recorded it into our bug tracking system. It should be fixed in the future version.

**Comment by jtuchek** [comment]
@oliverou I'm experiencing the same type of exception, although from a different component, including stack traces below

```
11-16 10:52:25.527 18354-21495/com.botlink.app E/UncaughtException: android.content.res.Resources$NotFoundException: String resource ID #0x0
                                                                        at android.content.res.Resources.getText(Resources.java:331)
                                                                        at android.content.res.Resources.getString(Resources.java:377)
                                                                        at dji.midware.g.a.a(Unknown Source)
                                                                        at dji.midware.g.a.b(Unknown Source)
                                                                        at dji.sdk.util.Util.getString(Unknown Source)
                                                                        at dji.internal.c.d.a(Unknown Source)
                                                                        at dji.internal.c.g.a(Unknown Source)
                                                                        at dji.sdk.base.DJIBaseProduct$1.onDiagnosisUpdate(Unknown Source)
                                                                        at dji.internal.c.f.c(Unknown Source)
                                                                        at dji.internal.c.m.onSuccess(Unknown Source)
                                                                        at dji.midware.data.manager.P3.u.callbackSuccess(Unknown Source)
                                                                        at dji.midware.data.manager.P3.u.access$200(Unknown Source)
                                                                        at dji.midware.data.manager.P3.w.run(Unknown Source)
                                                                        at java.lang.Thread.run(Thread.java:761)
```

```
11-16 10:52:25.832 18354-21495/com.botlink.app E/AndroidRuntime: FATAL EXCEPTION: Thread-2471
                                                                 Process: com.botlink.app, PID: 18354
                                                                 android.content.res.Resources$NotFoundException: String resource ID #0x0
                                                                     at android.content.res.Resources.getText(Resources.java:331)
                                                                     at android.content.res.Resources.getString(Resources.java:377)
                                                                     at dji.midware.g.a.a(Unknown Source)
                                                                     at dji.midware.g.a.b(Unknown Source)
                                                                     at dji.sdk.util.Util.getString(Unknown Source)
                                                                     at dji.internal.c.d.a(Unknown Source)
                                                                     at dji.internal.c.g.a(Unknown Source)
                                                                     at dji.sdk.base.DJIBaseProduct$1.onDiagnosisUpdate(Unknown Source)
                                                                     at dji.internal.c.f.c(Unknown Source)
                                                                     at dji.internal.c.m.onSuccess(Unknown Source)
                                                                     at dji.midware.data.manager.P3.u.callbackSuccess(Unknown Source)
                                                                     at dji.midware.data.manager.P3.u.access$200(Unknown Source)
                                                                     at dji.midware.data.manager.P3.w.run(Unknown Source)
                                                                     at java.lang.Thread.run(Thread.java:761)
```

**Comment by biskazz** [comment]
I also get similar type of error as I submitted an issue earlier. Seems like fixing broken sample code isn't one of the top priorities of DJI's Dev Team :)

**Comment by kenargo** [comment]
I get this error in my app randomly,  I don't think it's sample specific.

**Comment by jtuchek** [comment]
@biskazz these exceptions are sourced from the DJI SDK directly, their sample is failing as a consequence - it's not the actual problem.

We have exception records in production w/ SDK v3.4.0.

**Comment by talobin** [comment]
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!
