### ISSUE TITLE
SDK 4.11.1 RegistrationController crash

### ISSUE THREAD

**Issue by 0xm1nam0** [dji-sdk/Mobile-SDK-Android#491]
2020-03-18 21:16:38.669 5261-5261/? E/libc: Access denied finding property "runtime.mmitest.isrunning"
2020-03-18 21:16:39.198 5261-5261/? E/sdk: install begin
2020-03-18 21:16:39.206 5261-5261/? E/sdk: install begin
2020-03-18 21:16:39.323 5261-5332/? E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@a588430
2020-03-18 21:16:39.543 5261-5363/? E/Parcel: Reading a NULL string not supported here.
2020-03-18 21:16:41.355 5261-5412/? E/NativeRcController: Couldn't load libusbdec.so
2020-03-18 21:16:41.361 5261-5398/? E/DJIUsbAccessoryReceiver: start accessory receiver
2020-03-18 21:16:41.366 5261-5411/? E/DJIUsbAccessoryReceiver: android.hardware.usb.action.USB_STATE
2020-03-18 21:16:41.367 5261-5411/? E/DJIUsbAccessoryReceiver: android.hardware.usb.action.USB_STATE: is connected
2020-03-18 21:16:41.448 5261-5425/? E/Lightbridge: Failed to obtain JNIEnv
2020-03-18 21:16:41.448 5261-5424/? E/Lightbridge: Failed to obtain JNIEnv
2020-03-18 21:16:41.454 5261-5398/? E/RM500 RCType: Service Not Connected
2020-03-18 21:16:41.637 5261-5261/? E/ResMng NATIVE_MSG_FILTER: endActivityTransaction: margin state not match
2020-03-18 21:16:42.132 5261-5398/? E/FR_JNI: JNI_OnLoad
2020-03-18 21:16:42.150 5261-5398/? E/DJIMultiNetworkMgr: isWifiLink:false isWifiConnected:true isMobileDataEnabled:false
2020-03-18 21:16:42.184 5261-5398/? E/DJIMultiNetworkMgr: start checkForDisable
2020-03-18 21:16:42.185 5261-5398/? E/DJIMultiNetworkMgr: disabled, return
2020-03-18 21:16:42.187 5261-5261/? E/DJIMultiNetworkMgr: start checkForDisable
2020-03-18 21:16:42.188 5261-5261/? E/DJIMultiNetworkMgr: disabled, return
2020-03-18 21:16:42.189 5261-5398/? E/DJIUsbAccessoryReceiver: getModel: T600
2020-03-18 21:16:42.190 5261-5398/? E/DJIUsbAccessoryReceiver: currentModel saved: NORMAL
2020-03-18 21:16:42.191 5261-5398/? E/DJIUsbAccessoryReceiver: getManufacturer: DJI
2020-03-18 21:16:42.191 5261-5398/? E/DJIUsbAccessoryReceiver: hasPermission 
2020-03-18 21:16:42.191 5261-5398/? E/DJIUsbAccessoryReceiver: openAccessory: UsbAccessory[mManufacturer=DJI, mModel=T600, mDescription=DJI Inspire 1, mVersion=v0.0.0.0, mUri=www.dji.com, mSerialNumberReader=android.hardware.usb.IUsbSerialReader$Stub$Proxy@c5bc9df]
2020-03-18 21:16:42.192 5261-5398/? E/DJIUsbAccessoryReceiver: mFileDescriptor: mInputStream=java.io.FileInputStream@a1008f5
2020-03-18 21:16:42.192 5261-5398/? E/DJIUsbAccessoryReceiver: mFileDescriptor: FileDescriptor=true
2020-03-18 21:16:42.193 5261-5398/? E/linkDeamon: stopDaemon AOA
2020-03-18 21:16:42.212 5261-5416/? E/DJIPackManager: pack senderType=13 cmdSet=0
2020-03-18 21:16:42.214 5261-5416/? E/DJIPackManager: post DataCameraEvent.ConnectOK RC
2020-03-18 21:16:43.463 5261-5398/? E/DJIMultiNetworkMgr: event:ConnectOK
2020-03-18 21:16:43.463 5261-5398/? E/DJIMultiNetworkMgr: send MSG_RETRY_DETECT_ENABLE
2020-03-18 21:16:43.482 5261-5398/? E/AndroidRuntime: FATAL EXCEPTION: DJIExecutor Urgent #1
    Process: aerialar.hiscene.com, PID: 5261
    java.lang.SecurityException: getUniqueDeviceId: The user 10159 does not meet the requirements to access device identifiers.
        at android.os.Parcel.createException(Parcel.java:2071)
        at android.os.Parcel.readException(Parcel.java:2039)
        at android.os.Parcel.readException(Parcel.java:1987)
        at com.android.internal.telephony.IHwTelephony$Stub$Proxy.getUniqueDeviceId(IHwTelephony.java:3062)
        at android.telephony.HwTelephonyManagerInner.getUniqueDeviceId(HwTelephonyManagerInner.java:1189)
        at android.telephony.HwInnerTelephonyManagerImpl.getUniqueDeviceId(HwInnerTelephonyManagerImpl.java:377)
        at android.telephony.TelephonyManager.getDeviceId(TelephonyManager.java:1653)
        at dji.internal.registration.RegistrationController.e(Unknown Source:32)
        at dji.internal.registration.RegistrationController.c(Unknown Source:16)
        at dji.internal.registration.RegistrationController.b(Unknown Source:7)
        at dji.sdk.sdkmanager.DJISDKManager.registerApp(Unknown Source:50)
        at dji.sdk.sdkmanager.DJISDKManager.access$600(Unknown Source:0)
        at dji.sdk.sdkmanager.DJISDKManager$5$1.onDownloadSuccess(Unknown Source:6)
        at dji.internal.flysafe.DJIFlySafeDBLoader.a(Unknown Source:19)
        at dji.sdk.sdkmanager.DJISDKManager$5.run(Unknown Source:33)
        at dji.sdksharedlib.util.DJISDKCacheThreadManager$1.run(Unknown Source:5)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)
2020-03-18 21:16:43.497 5261-5411/? E/wm220: ****resetSwitchFromWifiFlag
2020-03-18 21:16:43.510 5261-5411/? E/DJIMultiNetworkMgr: receive msg MSG_RETRY_DETECT_ENABLE
2020-03-18 21:16:43.511 5261-5411/? E/DJIMultiNetworkMgr: isWifiLink:false isWifiConnected:true isMobileDataEnabled:false
2020-03-18 21:16:43.519 5261-5398/? E/UsbAccessoryService: final destroy() 71
2020-03-18 21:16:43.620 5261-5398/? E/UsbAccessoryService: final destroy() 72
2020-03-18 21:16:43.620 5261-5398/? E/wm220: ****resetSwitchFromWifiFlag
2020-03-18 21:16:43.622 5261-5398/? E/DJIUsbAccessoryReceiver: receiver destroySession
2020-03-18 21:16:43.623 5261-5398/? E/UsbAccessoryService: final destroy() 73
2020-03-18 21:16:43.623 5261-5398/? E/UsbAccessoryService: final destroy() 75
2020-03-18 21:16:43.624 5261-5398/? E/UsbAccessoryService: final destroy() 76
2020-03-18 21:16:43.625 5261-5398/? E/DJICrashHandler: uncaughtException 3
2020-03-18 21:16:44.479 5261-5261/? E/ResMng NATIVE_MSG_FILTER: endActivityTransaction: margin state not match
2020-03-18 21:16:44.480 5261-5411/? E/RM500 RCType: Service Not Connected
2020-03-18 21:16:44.547 5261-5261/? E/ResMng NATIVE_MSG_FILTER: endActivityTransaction: margin state not match
2020-03-18 21:16:44.555 5261-5261/? E/ResMng NATIVE_MSG_FILTER: endActivityTransaction: margin state not match
2020-03-18 21:16:44.569 5261-5261/? E/ConnectionActivity: onDestroy

**Comment by johnchenn** [comment]
```java
java.lang.SecurityException: getUniqueDeviceId: The user 10159 does not meet the requirements to access device identifiers.
at android.os.Parcel.createException(Parcel.java:2071)
at android.os.Parcel.readException(Parcel.java:2039)
at android.os.Parcel.readException(Parcel.java:1987)
at com.android.internal.telephony.IHwTelephony$Stub$Proxy.getUniqueDeviceId(IHwTelephony.java:3062)
at android.telephony.HwTelephonyManagerInner.getUniqueDeviceId(HwTelephonyManagerInner.java:1189)
at android.telephony.HwInnerTelephonyManagerImpl.getUniqueDeviceId(HwInnerTelephonyManagerImpl.java:377)
at android.telephony.TelephonyManager.getDeviceId(TelephonyManager.java:1653)
```
resolve this bug.

**Comment by kenargo** [comment]
It looks like you are missing permissions.

 

Depending on the Android version; have you checked your manifest permission set and/or the app’s permission settings?

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/32916'>Zendesk ticket #32916</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
To help us collect questions in detail, please fill in the form below and we will handle this ticket once we have received it.
https://formcrafts.com/a/dji-developer-feedback-en

Thanks,

Luce Luo
DJI Dev Team

**Comment by 0xm1nam0** [comment]
MSDK4.11.1 与android 10有一定兼容性问题，使用targetSdkVersion 28即可。
