### ISSUE TITLE
Nonfatal EventBus failures

### ISSUE THREAD

**Issue by jtuchek** [dji-sdk/Mobile-SDK-Android#51]
SDK Version: 3.3
Android Devices
-Nexus 9: API 24
DJI Devices
-Phantom 4
--RC Firmware: 1.8.0
--Flight Controller Firmware: 3..1.10.93
--gimbal firmware: 01.50.12.56
--camera firmware: 1.19.52.66

Keep seeing these in our logs, they aren't fatal but assuming any data not being delivered by EventBus isn't the desired behavior.

```
11-16 10:52:20.022 18354-18862/com.botlink.app E/Event: Could not dispatch event: class dji.midware.data.model.P3.DataOsdGetPushCommon to subscribing class class dji.internal.c.j
                                                        android.content.res.Resources$NotFoundException: String resource ID #0x0
                                                            at android.content.res.Resources.getText(Resources.java:331)
                                                            at android.content.res.Resources.getString(Resources.java:377)
                                                            at dji.midware.g.a.a(Unknown Source)
                                                            at dji.midware.g.a.b(Unknown Source)
                                                            at dji.sdk.util.Util.getString(Unknown Source)
                                                            at dji.internal.c.d.a(Unknown Source)
                                                            at dji.internal.c.g.a(Unknown Source)
                                                            at dji.sdk.base.DJIBaseProduct$1.onDiagnosisUpdate(Unknown Source)
                                                            at dji.internal.c.f.c(Unknown Source)
                                                            at dji.internal.c.j.onEventBackgroundThread(Unknown Source)
                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                            at dji.thirdparty.eventbus.EventBus.invokeSubscriber(EventBus.java:569)
                                                            at dji.thirdparty.eventbus.EventBus.postToSubscription(EventBus.java:513)
                                                            at dji.thirdparty.eventbus.EventBus.postSingleEvent(EventBus.java:475)
                                                            at dji.thirdparty.eventbus.EventBus.post(EventBus.java:365)
                                                            at dji.midware.data.manager.P3.u.post(Unknown Source)
                                                            at dji.midware.data.manager.P3.u.setPushRecData(Unknown Source)
                                                            at dji.midware.data.model.P3.DataOsdGetPushCommon.setPushRecData(Unknown Source)
                                                            at dji.midware.data.manager.P3.u.setPushRecPack(Unknown Source)
                                                            at dji.midware.data.manager.P3.l.b(Unknown Source)
                                                            at dji.midware.data.manager.P3.l.a(Unknown Source)
                                                            at dji.midware.data.manager.P3.l.a(Unknown Source)
                                                            at dji.midware.usb.P3.UsbAccessoryService$1.onGetBody(Unknown Source)
                                                            at dji.midware.f.a.f.c(Unknown Source)
                                                            at dji.midware.f.a.f.a(Unknown Source)
                                                            at dji.midware.usb.P3.UsbAccessoryService$RecvBufferRunnable.run(Unknown Source)
                                                            at java.lang.Thread.run(Thread.java:761)
```

**Comment by oliverou** [comment]
Hi @jtuchek, we have published the Android SDK 3.4.1 recently, could you try it and check if the issue still exists? Thanks!
