### ISSUE TITLE
4.12升级找不到MissionOperate实现

### ISSUE THREAD

**Issue by johnchenn** [dji-sdk/Mobile-SDK-Android#528]
升级MSDK到4.12 初始化任务类报错，未更改任何代码，仅将sdk版本升级到4.12，原先代码中获取MissionOperate处报错。
使用手机：小米Pad4
MSDK：4.12
出错代码：operator = MissionControl.getInstance().getWaypointMissionOperator();
错误信息：
TinkerUncaughtHandler catch exception:java.lang.UnsatisfiedLinkError: No implementation found for void dji.waypointv2.natives.WaypointV2Core.setIsWaypointV1AdaptorSupported(boolean) (tried Java_dji_waypointv2_natives_WaypointV2Core_setIsWaypointV1AdaptorSupported and Java_dji_waypointv2_natives_WaypointV2Core_setIsWaypointV1AdaptorSupported__Z)
        at dji.waypointv2.natives.WaypointV2Core.setIsWaypointV1AdaptorSupported(Native Method)
        at dji.sdk.mission.timeline.utils.WaypointActionControl.getWaypointMissionOperator(Unknown Source:17)
        at dji.sdk.mission.MissionControl.getWaypointMissionOperator(Unknown Source:4)
        at com.xxxx.xxxx.mission.WaypointMissionHelper.init(WaypointMissionHelper.java:61)

ps:参考app gradle配置文件，尝试增加donotstrip未修复问题
     doNotStrip "*/*/libDJIWaypointV2Core.so"
        doNotStrip "*/*/libAMapSDK_MAP_v6_9_2.so"
        doNotStrip "*/*/libDJIMOP.so"

        exclude 'assets/location_map_gps_locked.png'
        exclude 'assets/location_map_gps_3d.png'

**Comment by johnchenn** [comment]
补充错误信息：
2020-05-14 17:33:01.184 24814-24814/com.airdwing.hawkeye E/linker: "/data/app/com.airdwing.hawkeye-5IRXODEXOtAX3CUO-qCIrg==/lib/arm64/libDJIWaypointV2Core.so" .dynamic section has invalid offset: 0xfc820, expected to match PT_DYNAMIC offset: 0x0
2020-05-14 17:33:01.185 24814-24814/com.airdwing.hawkeye W/System.err: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.airdwing.hawkeye-5IRXODEXOtAX3CUO-qCIrg==/lib/arm64/libDJIWaypointV2Core.so" .dynamic section has invalid offset: 0xfc820, expected to match PT_DYNAMIC offset: 0x0
2020-05-14 17:33:01.185 24814-24814/com.airdwing.hawkeye W/System.err:     at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
2020-05-14 17:33:01.185 24814-24814/com.airdwing.hawkeye W/System.err:     at java.lang.System.loadLibrary(System.java:1657)
2020-05-14 17:33:01.185 24814-24814/com.airdwing.hawkeye W/System.err:     at dji.waypointv2.natives.WaypointV2Core.<clinit>(Unknown Source:6)
2020-05-14 17:33:01.185 24814-24814/com.airdwing.hawkeye W/System.err:     at dji.waypointv2.natives.WaypointV2Core.setIsWaypointV1AdaptorSupported(Native Method)
2020-05-14 17:33:01.185 24814-24814/com.airdwing.hawkeye W/System.err:     at dji.sdk.mission.timeline.utils.WaypointActionControl.getWaypointMissionOperator(Unknown Source:17)
2020-05-14 17:33:01.185 24814-24814/com.airdwing.hawkeye W/System.err:     at dji.sdk.mission.MissionControl.getWaypointMissionOperator(Unknown Source:4)
2020-05-14 17:33:01.185 24814-24814/com.airdwing.hawkeye W/System.err:     at com.airdwing.hawkeye.page.home.view.HomeActivity.onCreate(HomeActivity.java:142)
2020-05-14 17:33:01.185 24814-24814/com.airdwing.hawkeye W/System.err:     at android.app.Activity.performCreate(Activity.java:7088)
2020-05-14 17:33:01.185 24814-24814/com.airdwing.hawkeye W/System.err:     at android.app.Activity.performCreate(Activity.java:7079)
2020-05-14 17:33:01.185 24814-24814/com.airdwing.hawkeye W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
2020-05-14 17:33:01.185 24814-24814/com.airdwing.hawkeye W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
2020-05-14 17:33:01.185 24814-24814/com.airdwing.hawkeye W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895)
2020-05-14 17:33:01.186 24814-24814/com.airdwing.hawkeye W/System.err:     at android.app.ActivityThread.-wrap11(Unknown Source:0)
2020-05-14 17:33:01.186 24814-24814/com.airdwing.hawkeye W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616)
2020-05-14 17:33:01.186 24814-24814/com.airdwing.hawkeye W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2020-05-14 17:33:01.186 24814-24814/com.airdwing.hawkeye W/System.err:     at android.os.Looper.loop(Looper.java:173)
2020-05-14 17:33:01.186 24814-24814/com.airdwing.hawkeye W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6651)
2020-05-14 17:33:01.186 24814-24814/com.airdwing.hawkeye W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-05-14 17:33:01.186 24814-24814/com.airdwing.hawkeye W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
2020-05-14 17:33:01.186 24814-24814/com.airdwing.hawkeye W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:822)

**Comment by dji-dev** [comment]
尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

4.12版本里的航点任务重构了，还增加了航点任务V2。根据DEMO修改您的航点任务相关代码，我们的开发者论坛也有帖子介绍了航点任务2.0.

论坛链接：https://bbs.dji.com/thread-244276-1-1.html
GITHUB: https://github.com/DJI-Mobile-SDK-Tutorials/Android-GSDemo-Gaode-Map

**Comment by PanGuangwei** [comment]
更新gradle packagingOptions 增加项  doNotStrip "*/*/libDJIWaypointV2Core.so" 后，clean项目然后rebuild，我这边出现的相同问题得到解决。
