### ISSUE TITLE
ProcessLifecycleOwner

### ISSUE THREAD

**Issue by luoyexk** [dji-sdk/Mobile-SDK-Android#541]
```
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/ProcessLifecycleOwner;
        at dji.sdk.sdkmanager.DJISDKManager.initParams(Unknown Source:191)
        at dji.sdk.sdkmanager.DJISDKManager.initSDKManager(Unknown Source:23)
        at dji.sdk.sdkmanager.DJISDKManager.registerApp(Unknown Source:42)
        at dji.sdk.sdkmanager.DJISDKManager.access$600(Unknown Source:0)
        at dji.sdk.sdkmanager.DJISDKManager$5$1.onDownloadSuccess(Unknown Source:6)
        at dji.internal.flysafe.DJIFlySafeDBLoader.a(Unknown Source:19)
        at dji.sdk.sdkmanager.DJISDKManager$5.run(Unknown Source:33)
        at dji.sdksharedlib.util.DJISDKCacheThreadManager$1.run(Unknown Source:5)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

https://developer.dji.com/cn/mobile-sdk/documentation/application-development-workflow/workflow-integrate.html

流程里只需要导入以下包，为什么运行时奔溃，有未导入的包么
```
dependencies {
   ...
    compile ('com.dji:dji-sdk:4.12')
    provided ('com.dji:dji-sdk-provided:4.12')
}
```

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/35801'>Zendesk ticket #35801</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
参考一下这个官方sample gradle配置，对比检查下确实的依赖和so文件等。
https://github.com/dji-sdk/Mobile-SDK-Android/blob/master/Sample%20Code/app/build.gradle

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持

**Comment by AsahiEast** [comment]
出现相同的问题。Android 10  DJI SDK4.12

**Comment by luoyexk** [comment]
`
implementation 'androidx.lifecycle:lifecycle-extensions:2.0.0-rc01'
`

**Comment by hugangyongxiangsha** [comment]
> `implementation 'androidx.lifecycle:lifecycle-extensions:2.0.0-rc01'
按你的成功
