### ISSUE TITLE
Sample crashes sometimes on startup

### ISSUE THREAD

**Issue by epsmae** [dji-sdk/Mobile-SDK-Android#558]
I use the sample mobile sdk version 4.10.

The startup of the application is not reliable.
I don't even added the api key, I just added the following line. 

`
String version = DJISDKManager.getInstance().getSDKVersion();
`

To the attach to base context:

`    @Override
    protected void attachBaseContext(Context paramContext) {
        super.attachBaseContext(paramContext);
        MultiDex.install(this);
        com.secneo.sdk.Helper.install(this);
        String version = DJISDKManager.getInstance().getSDKVersion();
        app = this;
    }`

Out of 10 times the app crashes one time on the dji crystal Sky with Android 5.1:

`I/MultiDex: VM with version 2.1.0 has multidex support
I/MultiDex: Installing application
    VM has multidex support, MultiDex support library is disabled.
E/sdk: install begin
V/sdk: DexInstall beging
    installSecondarDexs
E/sdk: v19 install
V/sdk: DexInstall end
E/sdk: install begin
V/sdk: DexInstall beging
    installSecondarDexs
E/sdk: v19 install
V/sdk: DexInstall end
W/linker: libsfjni.so: unused DT entry: type 0x6ffffffe arg 0x29d0
    libsfjni.so: unused DT entry: type 0x6fffffff arg 0x1
D/SDKRelativeJNI: load lib suc
W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
W/linker: libwaes.so: unused DT entry: type 0x6ffffffe arg 0xc9c
    libwaes.so: unused DT entry: type 0x6fffffff arg 0x1
V/com.dji.sdk.sample.internal.view.MainContent: initUI
D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
D/Atlas: Validating map...
W/Atlas: Pointer 0x0, not in getPreloadedDrawables?
    Pointer 0x0, not in getPreloadedDrawables?
    Pointer 0x0, not in getPreloadedDrawables?
    Pointer 0x0, not in getPreloadedDrawables?
    Pointer 0x0, not in getPreloadedDrawables?
W/Atlas: Pointer 0x0, not in getPreloadedDrawables?
    Pointer 0x0, not in getPreloadedDrawables?
    Pointer 0x0, not in getPreloadedDrawables?
    Pointer 0x0, not in getPreloadedDrawables?
D/com.dji.sdk.sample.internal.view.MainContent: Comes into the onAttachedToWindow
D/com.dji.sdk.sample.internal.view.MainContent: mProduct: null
D/ViewRootImpl: onAttachToWindow register content observer attrs=WM.LayoutParams{(0,0)(fillxfill)mPosX=0mPosY=0mHScale=1.0mVScale=1.0 align=UNDEFINE taskId=53 sim=#100 ty=1 fl=#81810100 wanim=0x1030469 or=0 surfaceInsets=Rect(0, 0 - 0, 0) needsMenuKey=2packageName=com.dji.sdk.sampletoken=android.os.BinderProxy@56d69d4}
D/ViewRootImpl: 2048<<<<<< BACK FROM relayoutWM.LayoutParams{(0,0)(fillxfill)mPosX=0mPosY=0mHScale=1.0mVScale=1.0 align=UNDEFINE taskId=53 sim=#120 ty=1 fl=#81810100 wanim=0x1030469 or=0 surfaceInsets=Rect(0, 0 - 0, 0) needsMenuKey=2packageName=com.dji.sdk.sampletoken=android.os.BinderProxy@56d69d4}
I/libEGL: to search mali_so in soc specific path : /vendor/lib/egl/rk3288
D/libEGL: loaded /vendor/lib/egl/rk3288/libGLES_mali.so
I/mali_so: [File] : hardware/arm/maliT760/driver/product/base/src/mali_base_kbase.c; [Line] : 780; [Func] : base_context_deal_with_version_affairs_rk_ext;
    arm_release_ver of this mali_so is 'r6p0-02rel0', rk_so_ver is '12@0', built at '19:28:37', on 'Nov  8 2016'.
    [File] : hardware/arm/maliT760/driver/product/base/src/mali_base_kbase.c; [Line] : 807; [Func] : base_context_deal_with_version_affairs_rk_ext;
    mali_ver_property has been set to 'r6p0-02rel0-13-12@0', to return.
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Enabling debug mode 0
W/art: Verification of void com.dji.h.a.<clinit>() took 185.664ms
D/FPVController: try to load libdjivideo.so
D/ViewRootImpl: onAttachToWindow register content observer attrs=WM.LayoutParams{(0,128)(wrapxwrap)mPosX=0mPosY=0mHScale=1.0mVScale=1.0 align=UNDEFINE taskId=-1 gr=#51 ty=2005 fl=#1000098 fmt=-3 wanim=0x1030004 or=0 surfaceInsets=Rect(0, 0 - 0, 0)packageName=com.dji.sdk.sampletoken=null}
D/ViewRootImpl: 376<<<<<< BACK FROM relayoutWM.LayoutParams{(0,128)(wrapxwrap)mPosX=0mPosY=0mHScale=1.0mVScale=1.0 align=UNDEFINE taskId=-1 gr=#51 sim=#20 ty=2005 fl=#1000098 fmt=-3 wanim=0x1030004 or=0 surfaceInsets=Rect(0, 0 - 0, 0)packageName=com.dji.sdk.sampletoken=null}
E/BluetoothAdapter: Bluetooth binder is null
E/DJIBLE: DJIBLE ERROR::mothod : setContext -> mBluetoothAdapter == null
V/RenderScript: 0xb8869300 Launching thread(s), CPUs 4
D/NativeRcController: x try to load libusbdec.so
D/remotectrl.c: load interface in register_DJICamController()
    jniRegisterCBMethods: jniRegisterCBMethods
D/remotectrl.c: JNI_OnLoad() go to endXX
E/DJIUsbAccessoryReceiver: start accessory receiver
E/DJIUsbAccessoryReceiver: android.hardware.usb.action.USB_STATE
E/DJIUsbAccessoryReceiver: android.hardware.usb.action.USB_STATE: is connected
I/onLoad: loaded onLoad.cpp :JNI_OnLoad() go to end
D/GroudStation: load lib suc
D/DJIFlycParamInfoManager: readToMemory size = 678
D/UsbAccessoryService: accessory startStream
D/logWrite.cpp: UDT JNI_OnLoad---------------->
    UDP jniRegisterNativeMethods: jniRegisterNativeMethods
    loaded UDT :JNI_OnLoad() go to end
E/Lightbridge: Failed to obtain JNIEnv
E/Lightbridge: Failed to obtain JNIEnv
E/RM500 RCType: Service Not Connected
W/System.err: javax.crypto.IllegalBlockSizeException: last block incomplete in decryption
        at com.android.org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(BaseBlockCipher.java:850)
        at javax.crypto.Cipher.doFinal(Cipher.java:1340)
        at dji.midware.a.a.a.b(Unknown Source)
        at dji.internal.useraccount.a.a(Unknown Source)
        at dji.internal.useraccount.a.g(Unknown Source)
        at dji.internal.useraccount.a.a(Unknown Source)
        at dji.sdk.sdkmanager.DJISDKManager.initParams(Unknown Source)
        at dji.sdk.sdkmanager.DJISDKManager.initSDKManager(Unknown Source)
        at dji.sdk.sdkmanager.DJISDKManager.access$1300(Unknown Source)
        at dji.sdk.sdkmanager.DJISDKManager$5.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:818)
W/linker: libdjifs_jni.so: unused DT entry: type 0x6ffffffe arg 0x2058c
    libdjifs_jni.so: unused DT entry: type 0x6fffffff arg 0x3
    libDJIFlySafeCore.so: unused DT entry: type 0x6ffffffe arg 0x162014
    libDJIFlySafeCore.so: unused DT entry: type 0x6fffffff arg 0x3
D/HttpsHelper: verified, return
D/HttpsHelper: verified, return
D/NFZ JNI: FS SDK JNI_OnLoad---------------->
D/NFZ JNI: FS SDK JNI_OnLoad----------------> finished
D/NFZ JNI: jni_sdk_initialize
D/NFZ JNI: jni_sdk_initialize----> finished
W/linker: libFR.so: unused DT entry: type 0x6ffffffe arg 0x1f6880
    libFR.so: unused DT entry: type 0x6fffffff arg 0x2
E/FR_JNI: JNI_OnLoad
V/MainActivity: The app key submitted is invalid. Please check the app key you provided.
D/ViewRootImpl: onDetachedFromWindow ungister contentObserver
D/ViewRootImpl: onAttachToWindow register content observer attrs=WM.LayoutParams{(0,128)(wrapxwrap)mPosX=0mPosY=0mHScale=1.0mVScale=1.0 align=UNDEFINE taskId=-1 gr=#51 ty=2005 fl=#1000098 fmt=-3 wanim=0x1030004 or=0 surfaceInsets=Rect(0, 0 - 0, 0)packageName=com.dji.sdk.sampletoken=null}
D/ViewRootImpl: 1160<<<<<< BACK FROM relayoutWM.LayoutParams{(0,128)(wrapxwrap)mPosX=0mPosY=0mHScale=1.0mVScale=1.0 align=UNDEFINE taskId=-1 gr=#51 sim=#20 ty=2005 fl=#1000098 fmt=-3 wanim=0x1030004 or=0 surfaceInsets=Rect(0, 0 - 0, 0)packageName=com.dji.sdk.sampletoken=null}
D/HttpsHelper: verified, return
D/HttpsHelper: verified, return
D/ViewRootImpl: onDetachedFromWindow ungister contentObserver
E/step: step UDT.startup() start 1594020235964
E/step: step UDT.startup() end 1594020235965
I/DJILocationManager: Configuration requires not to use LOST Services, so skipping that step to Default Location Providers
    Attempting to get location from default providers...
I/DJILocationManager: GPS is already enabled, getting location...
I/DJILocationManager: LastKnownLocation is not usable.
    Ask for location update...
I/PhoneWindow: 206Key down: repeat=0 flags=0x8
I/PhoneWindow: 206Key up: repeat=0 flags=0x28
E/swudp-jni: SW_Pro_Gnd_Entry already stop
E/a: getNetworkObject return null for null cm
D/ViewRootImpl: 2048<<<<<< BACK FROM relayoutnull
D/ViewRootImpl: 2048<<<<<< BACK FROM relayoutnull
Disconnected from the target VM, address: 'localhost:8604', transport: 'socket'`

Any suggestions?

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/36585'>Zendesk ticket #36585</a>:<br><br>Dear Client
Thank you for contacting DJI.

We are up to 4.12 now. Please using our lastest sample.
Github：https://github.com/dji-sdk/Mobile-SDK-Android

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support
