### ISSUE TITLE
登录弹窗（login-dialog）

### ISSUE THREAD

**Issue by pwc1993** [dji-sdk/Mobile-SDK-Android#571]
背景：使用mobile SDK Android开发应用程序，装在大疆精灵4RTK（带屏幕）上<br>
现象：崩溃，Android Studio抓到信息如下:<br>
···
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources$Theme android.content.Context.getTheme()' on a null object reference
        at android.content.ContextWrapper.getTheme(ContextWrapper.java:122)
        at android.app.Dialog.<init>(Dialog.java:155)
        at android.app.Dialog.<init>(Dialog.java:132)
        at dji.internal.useraccount.view.LoginVerifyDialog.<init>()
        at dji.internal.useraccount.LoginVerifyController$4.run()
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5280)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:966)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)
····
出现弹窗不兼容问题，当前应用装在手机上，连接精灵4pro无问题

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/37222'>Zendesk ticket #37222</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

非常抱歉，P4R只有不带屏的遥控器才支持SDK。带屏遥控器是不支持SDK的，所以你装MSDK开发的APP会报错。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持
