### ISSUE TITLE
Log Auto Print "ErrnoException: Binding socket to network 530 failed: EPERM"

### ISSUE THREAD

**Issue by luoyexk** [dji-sdk/Mobile-SDK-Android#631]
```
2020-10-15 09:03:43.326 17242-17896 E/UDT-JNI: stopped udp
2020-10-15 09:03:43.329 17242-17896 E/getNetworkObject: network type:13
2020-10-15 09:03:43.335 17242-17896 E/getNetworkObject: network type:1
2020-10-15 09:03:43.339 17242-17896 E/gfd: bind exception:
    java.net.SocketException: Binding socket to network 530 failed: EPERM (Operation not permitted)
        at android.net.Network.bindSocket(Network.java:354)
        at dji.midware.uio.gfd.fdd(Unknown Source:39)
        at dji.midware.natives.UDT.bindSocketToNetwork(Unknown Source:4)
        at dji.midware.natives.UDT.SwUdpConnect(Native Method)
        at dji.midware.sockets.pub.ghj.connect(Unknown Source:42)
        at dji.midware.sockets.pub.ghj.checkConneted(Unknown Source:23)
        at dji.midware.sockets.pub.ghj.access$000(Unknown Source:0)
        at dji.midware.sockets.pub.okn.run(Unknown Source:2)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
     Caused by: android.system.ErrnoException: Binding socket to network 530 failed: EPERM (Operation not permitted)
        at android.net.Network.bindSocket(Network.java:354) 
        at dji.midware.uio.gfd.fdd(Unknown Source:39) 
        at dji.midware.natives.UDT.bindSocketToNetwork(Unknown Source:4) 
        at dji.midware.natives.UDT.SwUdpConnect(Native Method) 
        at dji.midware.sockets.pub.ghj.connect(Unknown Source:42) 
        at dji.midware.sockets.pub.ghj.checkConneted(Unknown Source:23) 
        at dji.midware.sockets.pub.ghj.access$000(Unknown Source:0) 
        at dji.midware.sockets.pub.okn.run(Unknown Source:2) 
        at java.util.TimerThread.mainLoop(Timer.java:555) 
        at java.util.TimerThread.run(Timer.java:505) 
2020-10-15 09:03:45.344 17242-17896 E/UDT-JNI: stopped udp
2020-10-15 09:03:45.347 17242-17896 E/getNetworkObject: network type:13
2020-10-15 09:03:45.353 17242-17896 E/getNetworkObject: network type:1
2020-10-15 09:03:45.357 17242-17896 E/gfd: bind exception:
    java.net.SocketException: Binding socket to network 530 failed: EPERM (Operation not permitted)
        at android.net.Network.bindSocket(Network.java:354)
        at dji.midware.uio.gfd.fdd(Unknown Source:39)
        at dji.midware.natives.UDT.bindSocketToNetwork(Unknown Source:4)
        at dji.midware.natives.UDT.SwUdpConnect(Native Method)
        at dji.midware.sockets.pub.ghj.connect(Unknown Source:42)
        at dji.midware.sockets.pub.ghj.checkConneted(Unknown Source:23)
        at dji.midware.sockets.pub.ghj.access$000(Unknown Source:0)
        at dji.midware.sockets.pub.okn.run(Unknown Source:2)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
     Caused by: android.system.ErrnoException: Binding socket to network 530 failed: EPERM (Operation not permitted)
        at android.net.Network.bindSocket(Network.java:354) 
        at dji.midware.uio.gfd.fdd(Unknown Source:39) 
        at dji.midware.natives.UDT.bindSocketToNetwork(Unknown Source:4) 
        at dji.midware.natives.UDT.SwUdpConnect(Native Method) 
        at dji.midware.sockets.pub.ghj.connect(Unknown Source:42) 
        at dji.midware.sockets.pub.ghj.checkConneted(Unknown Source:23) 
        at dji.midware.sockets.pub.ghj.access$000(Unknown Source:0) 
        at dji.midware.sockets.pub.okn.run(Unknown Source:2) 
        at java.util.TimerThread.mainLoop(Timer.java:555) 
        at java.util.TimerThread.run(Timer.java:505) 

```

When open the app only，logcat was always printed the above information. Does it mean the DJI SDK was trying to connect the drone?
In my code, I invoke `DJISDKManager.getInstance().registerApp(context, listener)` in the `MainActivity` and never call any method which in the DJI SDK.

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/40031'>Zendesk ticket #40031</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
To help us collect questions in detail, please fill in the form below and we will handle this ticket once we have received it.
https://formcrafts.com/a/dji-developer-feedback-en

Thanks,

Luce Luo
DJI Dev Team
