### ISSUE TITLE
p4p SDK崩溃 .固件 SDK都是最新版

### ISSUE THREAD

**Issue by SJJ-dot** [dji-sdk/Mobile-SDK-Android#647]
```
 thread：Thread[main,5,main] : java.lang.NullPointerException: Attempt to invoke virtual method 'dji.common.mission.tapfly.TapFlyMode dji.internal.ddf.fdd.koy.ddd.uio()' on a null object reference
        at dji.sdk.mission.tapfly.TapFlyMissionOperator.getTapFlyMode(Unknown Source:2)
        at dji.ux.widget.VisionWidget.isVisionSystemEnabled(Unknown Source:14)
        at dji.ux.widget.VisionWidget.getSingleVisionSystemStatus(Unknown Source:4)
        at dji.ux.widget.VisionWidget.transformValue(Unknown Source:16)
        at dji.ux.base.n.a(Unknown Source:6)
        at dji.ux.base.n.call(Unknown Source:2)
        at dji.thirdparty.rx.internal.util.ScalarSynchronousObservable$4.call(ScalarSynchronousObservable.java:223)
        at dji.thirdparty.rx.internal.util.ScalarSynchronousObservable$4.call(ScalarSynchronousObservable.java:220)
```

**Comment by SJJ-dot** [comment]
```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'dji.common.mission.tapfly.TapFlyMode dji.internal.ddf.fdd.koy.ddd.uio()' on a null object reference
        at dji.sdk.mission.tapfly.TapFlyMissionOperator.getTapFlyMode(Unknown Source:2)
        at dji.ux.widget.VisionWidget.isVisionSystemEnabled(Unknown Source:14)
        at dji.ux.widget.VisionWidget.getSingleVisionSystemStatus(Unknown Source:4)
        at dji.ux.widget.VisionWidget.transformValue(Unknown Source:16)
        at dji.ux.base.n.a(Unknown Source:6)
        at dji.ux.base.n.call(Unknown Source:2)
        at dji.thirdparty.rx.internal.util.ScalarSynchronousObservable$4.call(ScalarSynchronousObservable.java:223)
        at dji.thirdparty.rx.internal.util.ScalarSynchronousObservable$4.call(ScalarSynchronousObservable.java:220)
        at dji.thirdparty.rx.Observable$2.call(Observable.java:233)
        at dji.thirdparty.rx.Observable$2.call(Observable.java:225)
        at dji.thirdparty.rx.Observable.unsafeSubscribe(Observable.java:8741)
```

**Comment by luoyexk** [comment]
🤝  The same problem.
[https://github.com/dji-sdk/Mobile-UXSDK-Android/issues/90](url)  

You can try to use [dji-sdk/Mobile-UXSDK-Beta-Android](https://github.com/dji-sdk/Mobile-UXSDK-Beta-Android/wiki/UX-SDK-5.0-Overview) .

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/40564'>Zendesk ticket #40564</a>:<br><br>Dear Client
Thank you for contacting DJI.

The visionWidget has been used in UXDEMO and it works, please have a look the demo.
Link：https://github.com/dji-sdk/Mobile-UXSDK-Android

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support

**Comment by SJJ-dot** [comment]
我只希望你们能修复这个bug。

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/40564'>Zendesk ticket #40564</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

我们已经看到您在UXSDK Issue上提的问题，UXSDK的技术支持会在那里回复您。这个问题我会通知UXSDK的研发团队。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持
