### ISSUE TITLE
崩溃问题

### ISSUE THREAD

**Issue by joylhn** [dji-sdk/Mobile-SDK-Android#665]
刚打开软件崩溃，sdk版本 4.13.1，报错如下：

小米 MI PAD 4
Android 8.1.0,level 27
arm64-v8a

# dji_sdk_callback_thread(582)
java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.Object dji.keysdk.KeyManager.getValue(dji.keysdk.DJIKey)' on a null object reference

1 dji.internal.analytics.helper.DJIAnalyticsFlightStatusManager.updateRemoteControllerInfo(Unknown Source:57)
--
2 dji.internal.analytics.helper.DJIAnalyticsFlightStatusManager.refreshProductInformation(Unknown Source:10)
3 dji.internal.analytics.DJIAnalyticsEngine.trackRefreshProductConnectionStatus(Unknown Source:61)
4 dji.internal.analytics.listener.ProductLifecycleListener$1.run(Unknown Source:6)
5 android.os.Handler.handleCallback(Handler.java:794)
6 android.os.Handler.dispatchMessage(Handler.java:99)
7 android.os.Looper.loop(Looper.java:173)
8 android.os.HandlerThread.run(HandlerThread.java:65)

11-09 11:03:28.923  9613  9709 E AndroidRuntime: FATAL EXCEPTION: dji_sdk_callback_thread
--
18811-09 11:03:28.923  9613  9709 E AndroidRuntime: Process, PID: 9613
18911-09  11:03:28.923  9613  9709 E AndroidRuntime:  java.lang.NullPointerException: Attempt to invoke virtual method  'java.lang.Object dji.keysdk.KeyManager.getValue(dji.keysdk.DJIKey)' on a  null object reference
19011-09  11:03:28.923  9613  9709 E AndroidRuntime: 	at  dji.internal.analytics.helper.DJIAnalyticsFlightStatusManager.updateRemoteControllerInfo(Unknown  Source:57)
19111-09  11:03:28.923  9613  9709 E AndroidRuntime: 	at  dji.internal.analytics.helper.DJIAnalyticsFlightStatusManager.refreshProductInformation(Unknown  Source:10)
19211-09  11:03:28.923  9613  9709 E AndroidRuntime: 	at  dji.internal.analytics.DJIAnalyticsEngine.trackRefreshProductConnectionStatus(Unknown  Source:61)
19311-09  11:03:28.923  9613  9709 E AndroidRuntime: 	at  dji.internal.analytics.listener.ProductLifecycleListener$1.run(Unknown  Source:6)
19411-09 11:03:28.923  9613  9709 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:794)
19511-09 11:03:28.923  9613  9709 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
19611-09 11:03:28.923  9613  9709 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:173)
19711-09 11:03:28.923  9613  9709 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:65)
19811-09 11:03:28.963  9613  9870 W cr_ChildProcessConn: onServiceDisconnected (crash or killed by oom): pid=9872
19911-09 11:03:29.016  9613  9709 E UsbAccessoryService: final destroy() 71
20011-09 11:03:29.116  9613  9709 E UsbAccessoryService: final destroy() 72
20111-09 11:03:29.116  9613  9709 E wm220   : ****resetSwitchFromWifiFlag
20211-09 11:03:29.119  9613  9709 E DJIUsbAccessoryReceiver: receiver destroySession
20311-09 11:03:29.120  9613  9709 E UsbAccessoryService: final destroy() 73
20411-09 11:03:29.120  9613  9709 E UsbAccessoryService: final destroy() 75
20511-09 11:03:29.121  9613  9709 E UsbAccessoryService: final destroy() 76
20611-09 11:03:29.121  9613  9709 E DJICrashHandler: uncaughtException 3
20711-09 11:03:29.324  9613  9709 E CrashReport: Java Crash Happen cause by dji_sdk_callback_thread(582)

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/40863'>Zendesk ticket #40863</a>:<br><br>尊敬的用户，

您好！感谢您联系DJI 大疆创新。
为了快速收集问题细节，麻烦您详细填写如下表格。
https://formcrafts.com/a/dji-developer-feedback-cn

在收到您的详细细节信息后，我们将会进行快速处理。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
