### ISSUE TITLE
报错崩溃

### ISSUE THREAD

**Issue by joylhn** [dji-sdk/Mobile-SDK-Android#666]
软件运行10s，注册登录dji账号报错崩溃，sdk 版本4.13.2，问题如下：

软件正在后台运行(bug捕获)
华为 VRD AL10
Android 10,level 29
arm64-v8a

#1 main
java.lang.NullPointerException
Attempt to invoke virtual method 'android.content.res.Resources$Theme android.content.Context.getTheme()' on a null object reference

1 android.app.Dialog.<init>(Dialog.java:273)
--
2 android.app.Dialog.<init>(Dialog.java:247)
3 dji.internal.useraccount.view.koy.<init>(Unknown Source:11)
4 dji.internal.useraccount.uio.run(Unknown Source:12)
5 android.os.Handler.handleCallback(Handler.java:900)
6 android.os.Handler.dispatchMessage(Handler.java:103)
7 android.os.Looper.loop(Looper.java:219)
8 android.app.ActivityThread.main(ActivityThread.java:8347)
9 java.lang.reflect.Method.invoke(Native Method)
10 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
11 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:226)
--
111-05  16:18:14.700 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.connection.RealConnection.connectTls(Unknown  Source:65)
211-05  16:18:14.700 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.connection.RealConnection.establishProtocol(Unknown  Source:54)
311-05  16:18:14.700 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.connection.RealConnection.connect(Unknown  Source:187)
411-05  16:18:14.700 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.connection.StreamAllocation.findConnection(Unknown  Source:206)
511-05  16:18:14.700 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.connection.StreamAllocation.findHealthyConnection(Unknown  Source:0)
611-05  16:18:14.700 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.connection.StreamAllocation.newStream(Unknown  Source:22)
711-05  16:18:14.700 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.connection.ConnectInterceptor.intercept(Unknown  Source:25)
811-05  16:18:14.700 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown  Source:77)
911-05  16:18:14.700 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown  Source:6)
1011-05  16:18:14.700 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.cache.CacheInterceptor.intercept(Unknown  Source:132)
1111-05  16:18:14.700 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown  Source:77)
1211-05  16:18:14.700 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown  Source:6)
1311-05  16:18:14.700 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.http.BridgeInterceptor.intercept(Unknown  Source:160)
1411-05  16:18:14.700 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown  Source:77)
1511-05  16:18:14.700 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(Unknown  Source:49)
1611-05  16:18:14.700 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown  Source:77)
1711-05  16:18:14.700 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown  Source:6)
1811-05  16:18:14.700 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.RealCall.getResponseWithInterceptorChain(Unknown  Source:114)
1911-05  16:18:14.700 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.RealCall$AsyncCall.execute(Unknown Source:4)
2011-05  16:18:14.700 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.NamedRunnable.run(Unknown Source:17)
2111-05  16:18:14.700 18706 19060 W AndroidSecurityKeyStore: 	at  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2211-05  16:18:14.700 18706 19060 W AndroidSecurityKeyStore: 	at  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2311-05 16:18:14.700 18706 19060 W AndroidSecurityKeyStore: 	at java.lang.Thread.run(Thread.java:929)
2411-05 16:18:14.703 18706 19060 W AndroidSecurityKeyStore: KeyStore exception
2511-05 16:18:14.703 18706 19060 W AndroidSecurityKeyStore: android.os.ServiceSpecificException:  (code 7)
2611-05 16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at android.os.Parcel.createException(Parcel.java:2085)
2711-05 16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at android.os.Parcel.readException(Parcel.java:2039)
2811-05 16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at android.os.Parcel.readException(Parcel.java:1987)
2911-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  android.security.keystore.IKeystoreService$Stub$Proxy.get(IKeystoreService.java:978)
3011-05 16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at android.security.KeyStore.get(KeyStore.java:254)
3111-05 16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at android.security.KeyStore.get(KeyStore.java:243)
3211-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  android.security.keystore.AndroidKeyStoreSpi.engineGetCertificate(AndroidKeyStoreSpi.java:160)
3311-05 16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at java.security.KeyStore.getCertificate(KeyStore.java:1120)
3411-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  android.security.net.config.KeyStoreCertificateSource.ensureInitialized(KeyStoreCertificateSource.java:61)
3511-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  android.security.net.config.KeyStoreCertificateSource.findBySubjectAndPublicKey(KeyStoreCertificateSource.java:77)
3611-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  android.security.net.config.CertificatesEntryRef.findBySubjectAndPublicKey(CertificatesEntryRef.java:47)
3711-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  android.security.net.config.NetworkSecurityConfig.findTrustAnchorBySubjectAndPublicKey(NetworkSecurityConfig.java:123)
3811-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  android.security.net.config.TrustedCertificateStoreAdapter.getTrustAnchor(TrustedCertificateStoreAdapter.java:51)
3911-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  com.android.org.conscrypt.TrustManagerImpl.findTrustAnchorBySubjectAndPublicKey(TrustManagerImpl.java:964)
4011-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:499)
4111-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:426)
4211-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:354)
4311-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
4411-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:89)
4511-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:224)
4611-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:407)
4711-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
4811-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:387)
4911-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:226)
5011-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.connection.RealConnection.connectTls(Unknown  Source:65)
5111-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.connection.RealConnection.establishProtocol(Unknown  Source:54)
5211-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.connection.RealConnection.connect(Unknown  Source:187)
5311-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.connection.StreamAllocation.findConnection(Unknown  Source:206)
5411-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.connection.StreamAllocation.findHealthyConnection(Unknown  Source:0)
5511-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.connection.StreamAllocation.newStream(Unknown  Source:22)
5611-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.connection.ConnectInterceptor.intercept(Unknown  Source:25)
5711-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown  Source:77)
5811-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown  Source:6)
5911-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.cache.CacheInterceptor.intercept(Unknown  Source:132)
6011-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown  Source:77)
6111-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown  Source:6)
6211-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.http.BridgeInterceptor.intercept(Unknown  Source:160)
6311-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown  Source:77)
6411-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(Unknown  Source:49)
6511-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown  Source:77)
6611-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown  Source:6)
6711-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.RealCall.getResponseWithInterceptorChain(Unknown  Source:114)
6811-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.RealCall$AsyncCall.execute(Unknown Source:4)
6911-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.NamedRunnable.run(Unknown Source:17)
7011-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
7111-05  16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
7211-05 16:18:14.703 18706 19060 W AndroidSecurityKeyStore: 	at java.lang.Thread.run(Thread.java:929)
7311-05 16:18:14.706 18706 19060 W AndroidSecurityKeyStore: KeyStore exception
7411-05 16:18:14.706 18706 19060 W AndroidSecurityKeyStore: android.os.ServiceSpecificException:  (code 7)
7511-05 16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at android.os.Parcel.createException(Parcel.java:2085)
7611-05 16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at android.os.Parcel.readException(Parcel.java:2039)
7711-05 16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at android.os.Parcel.readException(Parcel.java:1987)
7811-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  android.security.keystore.IKeystoreService$Stub$Proxy.get(IKeystoreService.java:978)
7911-05 16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at android.security.KeyStore.get(KeyStore.java:254)
8011-05 16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at android.security.KeyStore.get(KeyStore.java:243)
8111-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  android.security.keystore.AndroidKeyStoreSpi.engineGetCertificate(AndroidKeyStoreSpi.java:160)
8211-05 16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at java.security.KeyStore.getCertificate(KeyStore.java:1120)
8311-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  android.security.net.config.KeyStoreCertificateSource.ensureInitialized(KeyStoreCertificateSource.java:61)
8411-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  android.security.net.config.KeyStoreCertificateSource.findBySubjectAndPublicKey(KeyStoreCertificateSource.java:77)
8511-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  android.security.net.config.CertificatesEntryRef.findBySubjectAndPublicKey(CertificatesEntryRef.java:47)
8611-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  android.security.net.config.NetworkSecurityConfig.findTrustAnchorBySubjectAndPublicKey(NetworkSecurityConfig.java:123)
8711-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  android.security.net.config.TrustedCertificateStoreAdapter.getTrustAnchor(TrustedCertificateStoreAdapter.java:51)
8811-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  com.android.org.conscrypt.TrustManagerImpl.findTrustAnchorBySubjectAndPublicKey(TrustManagerImpl.java:964)
8911-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:499)
9011-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:426)
9111-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:354)
9211-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
9311-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:89)
9411-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:224)
9511-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:407)
9611-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
9711-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:387)
9811-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:226)
9911-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.connection.RealConnection.connectTls(Unknown  Source:65)
10011-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.connection.RealConnection.establishProtocol(Unknown  Source:54)
10111-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.connection.RealConnection.connect(Unknown  Source:187)
10211-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.connection.StreamAllocation.findConnection(Unknown  Source:206)
10311-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.connection.StreamAllocation.findHealthyConnection(Unknown  Source:0)
10411-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.connection.StreamAllocation.newStream(Unknown  Source:22)
10511-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.connection.ConnectInterceptor.intercept(Unknown  Source:25)
10611-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown  Source:77)
10711-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown  Source:6)
10811-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.cache.CacheInterceptor.intercept(Unknown  Source:132)
10911-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown  Source:77)
11011-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown  Source:6)
11111-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.http.BridgeInterceptor.intercept(Unknown  Source:160)
11211-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown  Source:77)
11311-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(Unknown  Source:49)
11411-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown  Source:77)
11511-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(Unknown  Source:6)
11611-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.RealCall.getResponseWithInterceptorChain(Unknown  Source:114)
11711-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.RealCall$AsyncCall.execute(Unknown Source:4)
11811-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  dji.thirdparty.okhttp3.internal.NamedRunnable.run(Unknown Source:17)
11911-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12011-05  16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12111-05 16:18:14.706 18706 19060 W AndroidSecurityKeyStore: 	at java.lang.Thread.run(Thread.java:929)
122--------- beginning of crash
12311-05 16:18:14.855 18706 18706 E AndroidRuntime: FATAL EXCEPTION: main
12411-05 16:18:14.855 18706 18706 E AndroidRuntime: Process: PID: 18706
12511-05  16:18:14.855 18706 18706 E AndroidRuntime:  java.lang.NullPointerException: Attempt to invoke virtual method  'android.content.res.Resources$Theme android.content.Context.getTheme()'  on a null object reference
12611-05 16:18:14.855 18706 18706 E AndroidRuntime: 	at android.app.Dialog.<init>(Dialog.java:273)
12711-05 16:18:14.855 18706 18706 E AndroidRuntime: 	at android.app.Dialog.<init>(Dialog.java:247)
12811-05 16:18:14.855 18706 18706 E AndroidRuntime: 	at dji.internal.useraccount.view.koy.<init>(Unknown Source:11)
12911-05 16:18:14.855 18706 18706 E AndroidRuntime: 	at dji.internal.useraccount.uio.run(Unknown Source:12)
13011-05 16:18:14.855 18706 18706 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:900)
13111-05 16:18:14.855 18706 18706 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:103)
13211-05 16:18:14.855 18706 18706 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:219)
13311-05 16:18:14.855 18706 18706 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8347)
13411-05 16:18:14.855 18706 18706 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
13511-05  16:18:14.855 18706 18706 E AndroidRuntime: 	at  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
13611-05 16:18:14.855 18706 18706 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
13711-05 16:18:15.017 18706 19057 E UsbAccessoryService: final destroy() 72
13811-05 16:18:15.018 18706 19057 E wm220   : ****resetSwitchFromWifiFlag
13911-05 16:18:15.018 18706 19057 E DJIUsbAccessoryReceiver: receiver destroySession
14011-05 16:18:15.020 18706 19057 E UsbAccessoryService: final destroy() 73
14111-05 16:18:15.022 18706 19057 E UsbAccessoryService: final destroy() 75
14211-05 16:18:15.022 18706 19057 E UsbAccessoryService: final destroy() 76
14311-05 16:18:15.117 18706 18706 E CrashReport: Java Crash Happen cause by main(1)
14411-05  16:18:15.121 18706 18706 I HwApiCacheMangerEx: apicache  path=/storage/emulated/0 state=mounted  key=#10144#256
14511-05 16:18:15.121 18706 18706 I HwApiCacheMangerEx: need clear apicache,because volumes changed,oldCnt=1 newCnt=1
14611-05  16:18:15.122 18706 18706 I HwApiCacheMangerEx: apicache  path=/storage/emulated/0 state=mounted  key=#10144#0
14711-05 16:18:15.122 18706 18706 I HwApiCacheMangerEx: need clear apicache,because volumes changed,oldCnt=1 newCnt=1
14811-05  16:18:15.123 18706 18706 I HwApiCacheMangerEx: apicache  path=/storage/emulated/0 state=mounted  key=c#10144#256
14911-05 16:18:15.123 18706 18706 I HwApiCacheMangerEx: need clear apicache,because volumes changed,oldCnt=1 newCnt=1

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/40864'>Zendesk ticket #40864</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

没有4.13.2，只有4.13.1版本。你跑Sample也会报错崩溃吗? Sample的build.gradle的compileSdkVersion和targetSdkVersion需要调整成29。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持

**Comment by joylhn** [comment]
是4.13.1版本，这个是偶发现象，在这个设备上，属于隐藏bug

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/40864'>Zendesk ticket #40864</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

可能是华为系统和sdk兼容问题，我们会后续在测试当中加入这个型号的平板。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持
