### ISSUE TITLE
ArrayIndexOutOfBoundsException running waypoint mission, SDK v3.1

### ISSUE THREAD

**Issue by haogodent2** [dji-sdk/Mobile-SDK-Android#69]
Setup:
Android DJI Mobile SDK v3.1
Tablet: LG G8, android v7
Drone: Phantom 4
Android Studio 2.2.2

Just had an ArrayIndexOutOfBoundsException with a deployed Phantom 4 asset in field running waypoint mission. Here is the error logged, please address if not already done so with higher SDK releases:

java.lang.ArrayIndexOutOfBoundsException: length=11; index=11
	at android.util.ContainerHelpers.binarySearch(ContainerHelpers.java:28) ~[na:0.0]
	at android.util.SparseArray.indexOfKey(SparseArray.java:331) ~[na:0.0]
	at dji.midware.data.c.a.b.a(Unknown Source) ~[na:0.0]
	at dji.midware.data.manager.P3.a.synSendCmd(Unknown Source) ~[na:0.0]
	at dji.midware.data.manager.P3.v.run(Unknown Source) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:761) ~[na:0.0]

**Comment by oliverou** [comment]
Hi @haogodent2, I saw you are still using Android SDK v3.1, we have released Android SDK v3.5.1, please download it on DJI Developer Website: <https://developer.dji.com/mobile-sdk/downloads/> and try again. Thanks!

**Comment by haogodent2** [comment]
I will reopen ticket if it happens again in higher sdk version.
