### ISSUE TITLE
打印的日志太多了有没有开关

### ISSUE THREAD

**Issue by SJJ-dot** [dji-sdk/Mobile-SDK-Android#705]
```
Caused by: android.system.ErrnoException: Binding socket to network 111 failed: EPERM (Operation not permitted)
        at android.net.Network.bindSocket(Network.java:403)
        at dji.midware.uio.gfd.fdd(Unknown Source:39) 
        at dji.midware.natives.UDT.bindSocketToNetwork(Unknown Source:4) 
        at dji.midware.natives.UDT.SwUdpConnect(Native Method) 
        at dji.midware.sockets.pub.ghj.connect(Unknown Source:42) 
        at dji.midware.sockets.pub.ghj.checkConneted(Unknown Source:23) 
        at dji.midware.sockets.pub.ghj.access$000(Unknown Source:0) 
        at dji.midware.sockets.pub.okn.run(Unknown Source:2) 
        at java.util.TimerThread.processTask(Timer.java:569) 
        at java.util.TimerThread.mainLoop(Timer.java:527) 
        at java.util.TimerThread.run(Timer.java:512) 
```

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/41934'>Zendesk ticket #41934</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

十分抱歉，目前没有控制日志的开关。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持
