### ISSUE TITLE
app连接p4p,p4r工作正常，连接m300崩溃。method 'int dji.common.airlink.PhysicalSource.value()' on a null object

### ISSUE THREAD

**Issue by SJJ-dot** [dji-sdk/Mobile-SDK-Android#715]
abiFilters  配置
```
abiFilters 'armeabi-v7a'//, 'x86', 'arm64-v8a'
```
改为崩溃修复。
```
abiFilters 'armeabi-v7a', 'x86', 'arm64-v8a'
```
crash:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int dji.common.airlink.PhysicalSource.value()' on a null object reference
at dji.internal.camera.Sa$fdd.fdd(Unknown Source:6)
at dji.internal.camera.Sa.ddd(Unknown Source:39)
at dji.internal.camera.Sa.nhf(Unknown Source:0)
at dji.internal.camera.Ha.onValueChange(Unknown Source:19)
at dji.internal.dgh.ssf.run(Unknown Source:6)
at android.os.Handler.handleCallback(Handler.java:900)
at android.os.Handler.dispatchMessage(Handler.java:103)
at android.os.Looper.loop(Looper.java:219)
at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/42348'>Zendesk ticket #42348</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
抱歉，不支持x86设备，参考如下官方示例：
https://github.com/dji-sdk/Mobile-SDK-Android/blob/master/Sample%20Code/app/build.gradle#L23
 ![](https://djisdksupport.zendesk.com/attachments/token/99k3mReJWPvEvuteQ7MmJIoNX/?name=inline-1370271607.png)​

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持<br><a href='https://djisdksupport.zendesk.com/attachments/token/99k3mReJWPvEvuteQ7MmJIoNX' target='zd_attach'>inline-1370271607.png</a>

**Comment by SJJ-dot** [comment]
不是x86的问题。你去试试只保留'armeabi-v7a' 连接m300。必现崩溃



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "DJI"<notifications@github.com&gt;; 
发送时间: 2020年12月23日(星期三) 下午2:15
收件人: "dji-sdk/Mobile-SDK-Android"<Mobile-SDK-Android@noreply.github.com&gt;; 
抄送: "978622005"<978622005@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [dji-sdk/Mobile-SDK-Android] app连接p4p,p4r工作正常，连接m300崩溃。method &#39;int dji.common.airlink.PhysicalSource.value()&#39; on a null object (#715)





 
Agent comment from Luce Luo in Zendesk ticket #42348:

尊敬的用户，
 
您好！感谢您联系DJI 大疆创新。
 抱歉，不支持x86设备，参考如下官方示例：
 https://github.com/dji-sdk/Mobile-SDK-Android/blob/master/Sample%20Code/app/build.gradle#L23
 ​
 
非常感谢您的理解与配合，祝您生活愉快！
 
Best Regards,
 
DJI 大疆创新SDK技术支持
inline-1370271607.png
