### ISSUE TITLE
我又来了 dlopen failed: library "libdjivideo.so" not found

### ISSUE THREAD

**Issue by SJJ-dot** [dji-sdk/Mobile-SDK-Android#746]
```
 java.lang.UnsatisfiedLinkError: dlopen failed: library "libdjivideo.so" not found
     at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
     at java.lang.System.loadLibrary(System.java:1672)
     at dji.midware.natives.SDKRelativeJNI.<clinit>(Unknown Source:6)
     at dji.midware.natives.SDKRelativeJNI.native_getUsbAccessoryAttachedString(Native Method)
     at dji.sdk.sdkmanager.DJISDKManager.<clinit>(Unknown Source:40)
     at dji.sdk.sdkmanager.DJISDKManager.getInstance(Unknown Source:0)
     at com.holosense.dji.utils.RegisterAppService$register$1$1.run(RegisterAppService.kt:42)
     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
     at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
     at java.lang.Thread.run(Thread.java:784)

```

**Comment by SJJ-dot** [comment]
这个错误的时候报的 https://github.com/dji-sdk/Mobile-SDK-Android/issues/741

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/43081'>Zendesk ticket #43081</a>:<br><br>尊敬的用户，

您好！感谢您联系DJI 大疆创新。
为了快速收集问题细节，麻烦您详细填写如下表格。
https://formcrafts.com/a/dji-developer-feedback-cn

在收到您的详细细节信息后，我们将会进行快速处理。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
