### ISSUE TITLE
Crash with Gradle 7.0.0-alpha09

### ISSUE THREAD

**Issue by tkocik92** [dji-sdk/Mobile-SDK-Android#806]
I am attempting to run a project using `classpath "com.android.tools.build:gradle:7.0.0-alpha09"` to support newer Android features in conjunction with DJI SDK 4.14. The app compiles and runs fine until I connect the phone/tablet to a drone. The app then crashes with the following:

    java.lang.UnsatisfiedLinkError: No implementation found for void com.dji.megatronking.stringfog.StringUtilsJNI.test() (tried Java_com_dji_megatronking_stringfog_StringUtilsJNI_test and Java_com_dji_megatronking_stringfog_StringUtilsJNI_test__)
        at com.dji.megatronking.stringfog.StringUtilsJNI.test(Native Method)
        at com.dji.megatronking.stringfog.fdd.dgh.fdd(Unknown Source:3)
        at com.dji.megatronking.stringfog.fdd.dgh.fdd(Unknown Source:5)
        at dji.sdk.appbundle.AppBundleHelper.init(Unknown Source:2)
        at com.myapp.dji_air.view.RegistrationActivity.attachBaseContext(RegistrationActivity.kt:25)
        at android.app.Activity.attach(Activity.java:7857)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3554)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3775)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8107)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

RegistrationActivity Line 25 points to `AppBundleHelper.init()`

When downgrading the gradle plugin (see above) to the latest stable version (4.1.2 as of this writing) the app functions as expected (drone connects) without any additional code changes.

Packaging options:

    packagingOptions {
        doNotStrip "*/*/libdjivideo.so"
        doNotStrip "*/*/libSDKRelativeJNI.so"
        doNotStrip "*/*/libFlyForbid.so"
        doNotStrip "*/*/libduml_vision_bokeh.so"
        doNotStrip "*/*/libyuv2.so"
        doNotStrip "*/*/libGroudStation.so"
        doNotStrip "*/*/libFRCorkscrew.so"
        doNotStrip "*/*/libUpgradeVerify.so"
        doNotStrip "*/*/libFR.so"
        doNotStrip "*/*/libDJIFlySafeCore.so"
        doNotStrip "*/*/libdjifs_jni.so"
        doNotStrip "*/*/libsfjni.so"
        doNotStrip "*/*/libDJICommonJNI.so"
        doNotStrip "*/*/libDJICSDKCommon.so"
        doNotStrip "*/*/libDJIUpgradeCore.so"
        doNotStrip "*/*/libDJIUpgradeJNI.so"
        doNotStrip "*/*/libDJIWaypointV2Core.so"
        doNotStrip "*/*/libDJIMOP.so"

        pickFirst 'lib/*/libstlport_shared.so'
        pickFirst 'lib/*/libRoadLineRebuildAPI.so'
        pickFirst 'lib/*/libGNaviUtils.so'
        pickFirst 'lib/*/libGNaviMapex.so'
        pickFirst 'lib/*/libGNaviData.so'
        pickFirst 'lib/*/libGNaviMap.so'
        pickFirst 'lib/*/libGNaviSearch.so'
        pickFirst 'lib/*/libDJIFlySafeCore.so'
        pickFirst 'lib/*/libdjifs_jni.so'
        pickFirst 'lib/*/libsfjni.so'
        exclude 'META-INF/proguard/okhttp3.pro'
        exclude 'META-INF/rxjava.properties'
    }

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/45143'>Zendesk ticket #45143</a>:<br><br>Dear Client
Thank you for contacting DJI.

I will report this issue to the dev team. Meanwhile, just stick to the old gradle file in order to make the project compilable.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support

**Comment by nickdonnelly** [comment]
Is there any update regarding this, as the new Jetpack Compose features are hitting 1.0 in the near future and require newer gradle plugins.

**Comment by tkocik92** [comment]
With Gradle 7.0.2 (stable) and DJI Mobile SDK 4.15.1, this is no longer an issue
