### ISSUE TITLE
集成大疆sdk 4.11.1和4.14.1并在build.gradle设置shrinkResources为true后启动崩溃，日志如下，求解

### ISSUE THREAD

**Issue by tianoNao** [dji-sdk/Mobile-SDK-Android#819]
java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at dji.thirdparty.rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:784)
Caused by: dji.thirdparty.rx.exceptions.OnErrorNotImplementedException: Attempt to read from field 'java.lang.Number dji.midware.data.params.P3.ParamInfo.value' on a null object reference
	at dji.thirdparty.rx.Observable$27.onError(Observable.java:8566)
	at dji.thirdparty.rx.observers.SafeSubscriber._onError(SafeSubscriber.java:157)
	at dji.thirdparty.rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
	at dji.thirdparty.rx.exceptions.Exceptions.throwOrReport(Exceptions.java:201)
	at dji.thirdparty.rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:144)
	at dji.thirdparty.rx.internal.operators.OperatorSubscribeOn$1$1.onNext(OperatorSubscribeOn.java:53)
	at dji.thirdparty.rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:378)
	at dji.thirdparty.rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:340)
	at dji.thirdparty.rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:825)
	at dji.thirdparty.rx.observers.SerializedObserver.onNext(SerializedObserver.java:95)
	at dji.thirdparty.rx.observers.SerializedSubscriber.onNext(SerializedSubscriber.java:95)
	at dji.thirdparty.rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.innerNext(OnSubscribeConcatMap.java:182)
	at dji.thirdparty.rx.internal.operators.OnSubscribeConcatMap$ConcatMapInnerScalarProducer.request(OnSubscribeConcatMap.java:366)
	at dji.thirdparty.rx.internal.producers.ProducerArbiter.setProducer(ProducerArbiter.java:126)
	at dji.thirdparty.rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.drain(OnSubscribeConcatMap.java:278)
	at dji.thirdparty.rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.onNext(OnSubscribeConcatMap.java:144)
	at dji.thirdparty.rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.slowPath(OnSubscribeFromArray.java:100)
	at dji.thirdparty.rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.request(OnSubscribeFromArray.java:63)
	at dji.thirdparty.rx.Subscriber.setProducer(Subscriber.java:211)
	at dji.thirdparty.rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:32)
	at dji.thirdparty.rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:24)
	at dji.thirdparty.rx.Observable.unsafeSubscribe(Observable.java:8741)
	at dji.thirdparty.rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:94)
	at dji.thirdparty.rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:42)
	at dji.thirdparty.rx.Observable.unsafeSubscribe(Observable.java:8741)
	at dji.thirdparty.rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:245)
	at dji.thirdparty.rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:145)
	at dji.thirdparty.rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.fastPath(OnSubscribeFromArray.java:76)
	at dji.thirdparty.rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.request(OnSubscribeFromArray.java:58)
	at dji.thirdparty.rx.Subscriber.setProducer(Subscriber.java:211)
	at dji.thirdparty.rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:32)
	at dji.thirdparty.rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:24)
	at dji.thirdparty.rx.Observable$2.call(Observable.java:233)
	at dji.thirdparty.rx.Observable$2.call(Observable.java:225)
	at dji.thirdparty.rx.Observable.unsafeSubscribe(Observable.java:8741)
	at dji.thirdparty.rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
	at dji.thirdparty.rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	... 6 more
Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.Number dji.midware.data.params.P3.ParamInfo.value' on a null object reference
	at dji.internal.logics.IMULogic.updateSensor(Unknown Source:13)
	at dji.internal.logics.IMULogic.fdd(Unknown Source:0)
	at dji.internal.logics.IMULogic.access$lambda$0(Unknown Source:0)
	at dji.internal.logics.IMULogic$$Lambda$1.call(Unknown Source:2)
	at dji.thirdparty.rx.Observable$27.onNext(Observable.java:8571)
	at dji.thirdparty.rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
	... 38 more
dji.thirdparty.rx.exceptions.OnErrorNotImplementedException: Attempt to read from field 'java.lang.Number dji.midware.data.params.P3.ParamInfo.value' on a null object reference
	at dji.thirdparty.rx.Observable$27.onError(Observable.java:8566)
	at dji.thirdparty.rx.observers.SafeSubscriber._onError(SafeSubscriber.java:157)
	at dji.thirdparty.rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
	at dji.thirdparty.rx.exceptions.Exceptions.throwOrReport(Exceptions.java:201)
	at dji.thirdparty.rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:144)
	at dji.thirdparty.rx.internal.operators.OperatorSubscribeOn$1$1.onNext(OperatorSubscribeOn.java:53)
	at dji.thirdparty.rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:378)
	at dji.thirdparty.rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:340)
	at dji.thirdparty.rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:825)
	at dji.thirdparty.rx.observers.SerializedObserver.onNext(SerializedObserver.java:95)
	at dji.thirdparty.rx.observers.SerializedSubscriber.onNext(SerializedSubscriber.java:95)
	at dji.thirdparty.rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.innerNext(OnSubscribeConcatMap.java:182)
	at dji.thirdparty.rx.internal.operators.OnSubscribeConcatMap$ConcatMapInnerScalarProducer.request(OnSubscribeConcatMap.java:366)
	at dji.thirdparty.rx.internal.producers.ProducerArbiter.setProducer(ProducerArbiter.java:126)
	at dji.thirdparty.rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.drain(OnSubscribeConcatMap.java:278)
	at dji.thirdparty.rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.onNext(OnSubscribeConcatMap.java:144)
	at dji.thirdparty.rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.slowPath(OnSubscribeFromArray.java:100)
	at dji.thirdparty.rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.request(OnSubscribeFromArray.java:63)
	at dji.thirdparty.rx.Subscriber.setProducer(Subscriber.java:211)
	at dji.thirdparty.rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:32)
	at dji.thirdparty.rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:24)
	at dji.thirdparty.rx.Observable.unsafeSubscribe(Observable.java:8741)
	at dji.thirdparty.rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:94)
	at dji.thirdparty.rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:42)
	at dji.thirdparty.rx.Observable.unsafeSubscribe(Observable.java:8741)
	at dji.thirdparty.rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:245)
	at dji.thirdparty.rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:145)
	at dji.thirdparty.rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.fastPath(OnSubscribeFromArray.java:76)
	at dji.thirdparty.rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.request(OnSubscribeFromArray.java:58)
	at dji.thirdparty.rx.Subscriber.setProducer(Subscriber.java:211)
	at dji.thirdparty.rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:32)
	at dji.thirdparty.rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:24)
	at dji.thirdparty.rx.Observable$2.call(Observable.java:233)
	at dji.thirdparty.rx.Observable$2.call(Observable.java:225)
	at dji.thirdparty.rx.Observable.unsafeSubscribe(Observable.java:8741)
	at dji.thirdparty.rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
	at dji.thirdparty.rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:784)
Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.Number dji.midware.data.params.P3.ParamInfo.value' on a null object reference
	at dji.internal.logics.IMULogic.updateSensor(Unknown Source:13)
	at dji.internal.logics.IMULogic.fdd(Unknown Source:0)
	at dji.internal.logics.IMULogic.access$lambda$0(Unknown Source:0)
	at dji.internal.logics.IMULogic$$Lambda$1.call(Unknown Source:2)
	at dji.thirdparty.rx.Observable$27.onNext(Observable.java:8571)
	at dji.thirdparty.rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
	... 38 more
java.lang.NullPointerException: Attempt to read from field 'java.lang.Number dji.midware.data.params.P3.ParamInfo.value' on a null object reference
	at dji.internal.logics.IMULogic.updateSensor(Unknown Source:13)
	at dji.internal.logics.IMULogic.fdd(Unknown Source:0)
	at dji.internal.logics.IMULogic.access$lambda$0(Unknown Source:0)
	at dji.internal.logics.IMULogic$$Lambda$1.call(Unknown Source:2)
	at dji.thirdparty.rx.Observable$27.onNext(Observable.java:8571)
	at dji.thirdparty.rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
	at dji.thirdparty.rx.internal.operators.OperatorSubscribeOn$1$1.onNext(OperatorSubscribeOn.java:53)
	at dji.thirdparty.rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:378)
	at dji.thirdparty.rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:340)
	at dji.thirdparty.rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:825)
	at dji.thirdparty.rx.observers.SerializedObserver.onNext(SerializedObserver.java:95)
	at dji.thirdparty.rx.observers.SerializedSubscriber.onNext(SerializedSubscriber.java:95)
	at dji.thirdparty.rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.innerNext(OnSubscribeConcatMap.java:182)
	at dji.thirdparty.rx.internal.operators.OnSubscribeConcatMap$ConcatMapInnerScalarProducer.request(OnSubscribeConcatMap.java:366)
	at dji.thirdparty.rx.internal.producers.ProducerArbiter.setProducer(ProducerArbiter.java:126)
	at dji.thirdparty.rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.drain(OnSubscribeConcatMap.java:278)
	at dji.thirdparty.rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.onNext(OnSubscribeConcatMap.java:144)
	at dji.thirdparty.rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.slowPath(OnSubscribeFromArray.java:100)
	at dji.thirdparty.rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.request(OnSubscribeFromArray.java:63)
	at dji.thirdparty.rx.Subscriber.setProducer(Subscriber.java:211)
	at dji.thirdparty.rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:32)
	at dji.thirdparty.rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:24)
	at dji.thirdparty.rx.Observable.unsafeSubscribe(Observable.java:8741)
	at dji.thirdparty.rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:94)
	at dji.thirdparty.rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:42)
	at dji.thirdparty.rx.Observable.unsafeSubscribe(Observable.java:8741)
	at dji.thirdparty.rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:245)
	at dji.thirdparty.rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:145)
	at dji.thirdparty.rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.fastPath(OnSubscribeFromArray.java:76)
	at dji.thirdparty.rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.request(OnSubscribeFromArray.java:58)
	at dji.thirdparty.rx.Subscriber.setProducer(Subscriber.java:211)
	at dji.thirdparty.rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:32)
	at dji.thirdparty.rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:24)
	at dji.thirdparty.rx.Observable$2.call(Observable.java:233)
	at dji.thirdparty.rx.Observable$2.call(Observable.java:225)
	at dji.thirdparty.rx.Observable.unsafeSubscribe(Observable.java:8741)
	at dji.thirdparty.rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
	at dji.thirdparty.rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:784)

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/45335'>Zendesk ticket #45335</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
试一下官方4.14.1demo能否复现。
https://github.com/dji-sdk/Mobile-SDK-Android

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
