### ISSUE TITLE
NullPointerException - CameraConfigEVWidget.updateWidget

### ISSUE THREAD

**Issue by luoyexk** [dji-sdk/Mobile-SDK-Android#829]
```
Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.String dji.common.camera.SettingsDefinitions$ExposureCompensation.name()' on a null object reference
dji.ux.d.k.a
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String dji.common.camera.SettingsDefinitions$ExposureCompensation.name()' on a null object reference
       at dji.ux.d.k.a()
       at dji.ux.widget.config.CameraConfigEVWidget.updateWidget(:65)
       at dji.ux.base.o.a(:4)
       at dji.ux.base.o.call(:2)
       at dji.thirdparty.rx.Observable.unsafeSubscribe(Observable.java:8741)
       at dji.thirdparty.rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
       at dji.thirdparty.rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

开发时是没有问题的，但是app到飞手上用后，经常会发生这个异常。

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/45593'>Zendesk ticket #45593</a>:<br><br>尊敬的用户，

您好！感谢您联系DJI 大疆创新。
为了快速收集问题细节，麻烦您详细填写如下表格。
https://formcrafts.com/a/dji-developer-feedback-cn

在收到您的详细细节信息后，我们将会进行快速处理。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
