### ISSUE TITLE
DJIAnalyticsHeaderManager NullPointerException

### ISSUE THREAD

**Issue by luoyexk** [dji-sdk/Mobile-SDK-Android#839]
线上版本遇到的，目前无法复现

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
       at dji.internal.analytics.helper.DJIAnalyticsHeaderManager.refreshProductInformation(:27)
       at dji.internal.analytics.DJIAnalyticsEngine.trackRefreshProductConnectionStatus(:47)
       at dji.internal.analytics.gfd.onValueChange(:20)
       at dji.sdksharedlib.listener.DJISDKCacheListenerLayer$ValueChangeRunnable.run(:10)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by luoyexk** [comment]
Android 10
Galaxy Tab A (8.4", 2020)

代码里没有使用DJIAnalyticsHeaderManager类

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/46122'>Zendesk ticket #46122</a>:<br><br>尊敬的用户，

您好！感谢您联系DJI 大疆创新。
这个问题需要详细调查下，为了快速收集问题细节，麻烦您详细填写如下表格。
https://formcrafts.com/a/dji-developer-feedback-cn

在收到您的详细细节信息后，我们将会进行快速处理。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
