### ISSUE TITLE
App Crash : FATAL EXCEPTION: RxComputationThreadPool-5

### ISSUE THREAD

**Issue by mayurpatil307** [dji-sdk/Mobile-SDK-Android#900]
Android Devices used: DJI Smart Controller Enterprise, LG V60 ThinQ 5G
DJI SDK Version: 4.14
App crashes with following crash logs when connected to M300. 

--------- beginning of crash
06-03 11:00:01.629 23419 23851 E AndroidRuntime: FATAL EXCEPTION: RxComputationThreadPool-5
06-03 11:00:01.629 23419 23851 E AndroidRuntime: java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
06-03 11:00:01.629 23419 23851 E AndroidRuntime: 	at dji.thirdparty.rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
06-03 11:00:01.629 23419 23851 E AndroidRuntime: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
06-03 11:00:01.629 23419 23851 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
06-03 11:00:01.629 23419 23851 E AndroidRuntime: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
06-03 11:00:01.629 23419 23851 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-03 11:00:01.629 23419 23851 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-03 11:00:01.629 23419 23851 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
06-03 11:00:01.629 23419 23851 E AndroidRuntime: Caused by: dji.thirdparty.rx.exceptions.OnErrorNotImplementedException: java.lang.NoSuchFieldException: LINK_LTE
06-03 11:00:01.629 23419 23851 E AndroidRuntime: 	at dji.thirdparty.rx.Observable$27.onError(Observable.java:8566)
06-03 11:00:01.629 23419 23851 E AndroidRuntime: 	at dji.thirdparty.rx.observers.SafeSubscriber._onError(SafeSubscriber.java:157)
06-03 11:00:01.629 23419 23851 E AndroidRuntime: 	at dji.thirdparty.rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
06-03 11:00:01.629 23419 23851 E AndroidRuntime: 	at dji.thirdparty.rx.exceptions.Exceptions.throwOrReport(Exceptions.java:201)
06-03 11:00:01.629 23419 23851 E AndroidRuntime: 	at dji.thirdparty.rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:144)
06-03 11:00:01.629 23419 23851 E AndroidRuntime: 	at dji.thirdparty.rx.internal.util.ScalarSynchronousObservable$ScalarAsyncProducer.call(ScalarSynchronousObservable.java:192)
06-03 11:00:01.629 23419 23851 E AndroidRuntime: 	at dji.thirdparty.rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
06-03 11:00:01.629 23419 23851 E AndroidRuntime: 	... 6 more
06-03 11:00:01.629 23419 23851 E AndroidRuntime: Caused by: java.lang.AssertionError: java.lang.NoSuchFieldException: LINK_LTE
06-03 11:00:01.629 23419 23851 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:792)
06-03 11:00:01.629 23419 23851 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapters$30.create(TypeAdapters.java:818)
06-03 11:00:01.629 23419 23851 E AndroidRuntime: 	at com.google.gson.Gson.getAdapter(Gson.java:458)
06-03 11:00:01.629 23419 23851 E AndroidRuntime: 	at com.google.gson.Gson.toJson(Gson.java:696)
06-03 11:00:01.629 23419 23851 E AndroidRuntime: 	at com.google.gson.Gson.toJson(Gson.java:683)
06-03 11:00:01.629 23419 23851 E AndroidRuntime: 	at com.google.gson.Gson.toJson(Gson.java:638)
06-03 11:00:01.629 23419 23851 E AndroidRuntime: 	at com.google.gson.Gson.toJson(Gson.java:618)
06-03 11:00:01.629 23419 23851 E AndroidRuntime: 	at com.dji.frame.util.V_JsonUtil.toJson(Unknown Source:4)
06-03 11:00:01.629 23419 23851 E AndroidRuntime: 	at dji.internal.analytics.listener.DJIAnalyticsCacheInteractionListener.getValueJson(Unknown Source:0)
06-03 11:00:01.629 23419 23851 E AndroidRuntime: 	at dji.internal.analytics.listener.DJIAnalyticsCacheInteractionListener.metaDataWithKeyPath(Unknown Source:72)
06-03 11:00:01.629 23419 23851 E AndroidRuntime: 	at dji.internal.analytics.listener.DJIAnalyticsCacheInteractionListener.onEvent(Unknown Source:36)
06-03 11:00:01.629 23419 23851 E AndroidRuntime: 	at dji.sdksharedlib.DJISDKCache.fdd(Unknown Source:27)
06-03 11:00:01.629 23419 23851 E AndroidRuntime: 	at dji.sdksharedlib.DJISDKCache.access$lambda$0(Unknown Source:0)
06-03 11:00:01.629 23419 23851 E AndroidRuntime: 	at dji.sdksharedlib.DJISDKCache$$Lambda$1.call(Unknown Source:13)
06-03 11:00:01.629 23419 23851 E AndroidRuntime: 	at dji.thirdparty.rx.Observable$27.onNext(Observable.java:8571)
06-03 11:00:01.629 23419 23851 E AndroidRuntime: 	at dji.thirdparty.rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
06-03 11:00:01.629 23419 23851 E AndroidRuntime: 	... 8 more
06-03 11:00:01.629 23419 23851 E AndroidRuntime: Caused by: java.lang.NoSuchFieldException: LINK_LTE
06-03 11:00:01.629 23419 23851 E AndroidRuntime: 	at java.lang.Class.getField(Class.java:1604)
06-03 11:00:01.629 23419 23851 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:781)
06-03 11:00:01.629 23419 23851 E AndroidRuntime: 	... 23 more

We are unable to use the app further. 
Please help with the resolution to this issue.

Thanks.

**Comment by Hoker-** [comment]
看你版本还是，DJI SDK Version: 4.14
这个是4.14上的bug，在4.14.1上有解决，可以更新后再试试。

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/48585'>Zendesk ticket #48585</a>:<br><br>Dear Client
Thank you for contacting DJI.

We solved in 4.14.1 version.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support
<br><p><em><small>°°°</small></em></p>
