### ISSUE TITLE
Method addObserver must be called on the main thread

### ISSUE THREAD

**Issue by zijian98** [dji-sdk/Mobile-SDK-Android#909]
Hi, I am trying to import the SDK but have been having crashes while trying to register the app. This is the error: 

2021-06-16 10:59:27.960 15534-15680/com.dji.FlyDJI E/AndroidRuntime: FATAL EXCEPTION: UrgentThreadPool#1
    Process: com.dji.FlyDJI, PID: 15534
    java.lang.IllegalStateException: Method addObserver must be called on the main thread
        at androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded(:317)
        at androidx.lifecycle.LifecycleRegistry.addObserver(:172)
        at dji.sdk.sdkmanager.DJISDKManager.initParams(Unknown Source:192)
        at dji.sdk.sdkmanager.DJISDKManager.initSDKManager(Unknown Source:12)
        at dji.sdk.sdkmanager.DJISDKManager.registerApp(Unknown Source:42)
        at dji.sdk.sdkmanager.DJISDKManager.access$800(Unknown Source:0)
        at dji.sdk.sdkmanager.DJISDKManager$6$1.onDownloadSuccess(Unknown Source:8)
        at dji.internal.ghu.ghu.fdd(Unknown Source:19)
        at dji.sdk.sdkmanager.DJISDKManager$6.run(Unknown Source:37)
        at dji.sdksharedlib.gfd.koy.run(Unknown Source:5)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)
2021-06-16 10:59:27.989 15534-15680/com.dji.FlyDJI I/HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=com.dji.FlyDJI#10513#0
2021-06-16 10:59:27.989 15534-15680/com.dji.FlyDJI I/HwApiCacheMangerEx: need clear apicache,because volumes changed,oldCnt=1 newCnt=1
2021-06-16 10:59:27.994 15534-15680/com.dji.FlyDJI E/UsbAccessoryService: final destroy() 71
2021-06-16 10:59:28.094 15534-15680/com.dji.FlyDJI E/UsbAccessoryService: final destroy() 72
2021-06-16 10:59:28.094 15534-15680/com.dji.FlyDJI E/wm220: ****resetSwitchFromWifiFlag
2021-06-16 10:59:28.094 15534-15680/com.dji.FlyDJI E/DJIUsbAccessoryReceiver: receiver destroySession
2021-06-16 10:59:28.095 15534-15680/com.dji.FlyDJI E/UsbAccessoryService: final destroy() 73
2021-06-16 10:59:28.096 15534-15680/com.dji.FlyDJI E/UsbAccessoryService: final destroy() 75
2021-06-16 10:59:28.096 15534-15680/com.dji.FlyDJI E/UsbAccessoryService: final destroy() 76
2021-06-16 10:59:28.096 15534-15680/com.dji.FlyDJI E/DJICrashHandler: uncaughtException 3

My gradle build:

`apply plugin: 'com.android.application'

repositories {
    mavenLocal()
    mavenCentral()
}

android {
    compileSdkVersion 30
    buildToolsVersion "30.0.3"
    useLibrary 'org.apache.http.legacy'

    defaultConfig {
        applicationId "com.dji.FlyDJI"
        minSdkVersion 19
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        ndk {
            // On x86 devices that run Android API 23 or above, if the application is targeted with API 23 or
            // above, FFmpeg lib might lead to runtime crashes or warnings.
            abiFilters 'armeabi-v7a', 'x86', 'arm64-v8a'
        }

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            shrinkResources true
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    dexOptions {
        javaMaxHeapSize "4g"
    }

    packagingOptions {
        doNotStrip "*/*/libdjivideo.so"
        doNotStrip "*/*/libSDKRelativeJNI.so"
        doNotStrip "*/*/libFlyForbid.so"
        doNotStrip "*/*/libduml_vision_bokeh.so"
        doNotStrip "*/*/libyuv2.so"
        doNotStrip "*/*/libGroudStation.so"
        doNotStrip "*/*/libFRCorkscrew.so"
        doNotStrip "*/*/libUpgradeVerify.so"
        doNotStrip "*/*/libFR.so"
        doNotStrip "*/*/libDJIFlySafeCore.so"
        doNotStrip "*/*/libdjifs_jni.so"
        doNotStrip "*/*/libsfjni.so"
        doNotStrip "*/*/libDJICommonJNI.so"
        doNotStrip "*/*/libDJICSDKCommon.so"
        doNotStrip "*/*/libDJIUpgradeCore.so"
        doNotStrip "*/*/libDJIUpgradeJNI.so"
        doNotStrip "*/*/libDJIWaypointV2Core.so"
        doNotStrip "*/*/libAMapSDK_MAP_v6_9_2.so"
        doNotStrip "*/*/libDJIMOP.so"
        doNotStrip "*/*/libDJISDKLOGJNI.so"
        exclude 'META-INF/rxjava.properties'
        exclude 'assets/location_map_gps_locked.png'
        exclude 'assets/location_map_gps_3d.png'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation('com.dji:dji-sdk:4.14.1', {
        /**
         * Uncomment the "library-anti-distortion" if your app does not need Anti Distortion for Mavic 2 Pro and Mavic 2 Zoom.
         * Uncomment the "fly-safe-database" if you need database for release, or we will download it when DJISDKManager.getInstance().registerApp
         * is called.
         * Both will greatly reducing the size of the APK.
         */
        exclude module: 'library-anti-distortion'
        //exclude module: 'fly-safe-database'
    })
    compileOnly 'com.dji:dji-sdk-provided:4.14.1'

    implementation 'androidx.appcompat:appcompat:1.3.0'
    implementation 'com.google.android.material:material:1.3.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
    implementation 'androidx.recyclerview:recyclerview:1.2.1'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'
    implementation 'androidx.annotation:annotation:1.2.0'
    implementation 'androidx.core:core:1.5.0'
}`

How do I fix this?

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/49025'>Zendesk ticket #49025</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
The registration process must be executed in the main thread.
Here is a sample, please try to refer to it.
https://github.com/dji-sdk/Mobile-SDK-Android/blob/master/Sample%20Code/app/src/main/java/com/dji/sdk/sample/internal/view/MainContent.java

Thanks,

Luce Luo
DJI Developer Support
<br><p><em><small>°°°</small></em></p>
