### ISSUE TITLE
点击登录报错NullPointerException

### ISSUE THREAD

**Issue by fansmc** [dji-sdk/Mobile-SDK-Android#925]
SDK版本:
com.dji:dji-sdk-provided:4.14.1
com.dji:dji-sdk:4.14.1

编译环境:
compileSdkVersion 29
buildToolsVersion '29.0.3'

崩溃日志:
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' 
    on a null object reference
        at dji.midware.util.hgf.fdd(Unknown Source:0)
        at dji.midware.util.hgf.fdd(Unknown Source:0)
        at dji.internal.useraccount.nbb.ghu(Unknown Source:12)
        at dji.internal.useraccount.nbb.nhf(Unknown Source:4)
        at dji.sdk.useraccount.UserAccountManager.updateInternalUserAccountState(Unknown Source:8)
        at dji.sdk.useraccount.UserAccountManager.<init>(Unknown Source:3)
        at dji.sdk.useraccount.UserAccountManager.getInstance(Unknown Source:9)
        at com.szewec.emergency.fly.MainActivity$onCreate$1$1.run(MainActivity.kt:24)
        at android.app.Activity.runOnUiThread(Activity.java:6318)
        at com.szewec.emergency.fly.MainActivity$onCreate$1.onClick(MainActivity.kt:23)
        at android.view.View.performClick(View.java:6636)
        at android.view.View.performClickInternal(View.java:6613)
        at android.view.View.access$3100(View.java:788)
        at android.view.View$PerformClick.run(View.java:26098)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7025)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:937)

调用代码:

      `loginBtn.setOnClickListener {
            UserAccountManager.getInstance().logIntoDJIUserAccount(applicationContext,
                object : CommonCallbacks.CompletionCallbackWith<UserAccountState> {

                    override fun onSuccess(state: UserAccountState?) {
                        loginBtn.visibility = View.GONE
                        logoutBtn.visibility = View.VISIBLE
                    }

                    override fun onFailure(error: DJIError?) {
                    }
                })
        }`

**Comment by Hoker-** [comment]
请问是在registerApp成功后，再调用UserAccountManager.getInstance().logIntoDJIUserAccount么？

**Comment by fansmc** [comment]
这个我也遇到了, 要先调用registerApp  然后在logIntoDJIUserAccount  否则会崩溃
