### ISSUE TITLE
NativeRcController: Couldn't load libusbdec.so

### ISSUE THREAD

**Issue by lt594963425** [dji-sdk/Mobile-SDK-Android#959]
app启动后 出现   NativeRcController: Couldn't load libusbdec.so
是什么原因呢？

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/50087'>Zendesk ticket #50087</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
是不是使用了安卓模拟器？MSDK不支持在模拟器上使用，需要使用真机。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>

**Comment by davidWhynum01** [comment]
我使用的是真机，从4.13到4.14 再到4.15都不行

**Comment by davidWhynum01** [comment]
E/NativeRcController: Couldn't load libusbdec.so
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/ProcessLifecycleOwner;
        at dji.sdk.sdkmanager.DJISDKManager.initParams(Unknown Source:182)
        at dji.sdk.sdkmanager.DJISDKManager.initSDKManager(Unknown Source:15)
        at dji.sdk.sdkmanager.DJISDKManager.registerApp(Unknown Source:42)
        at dji.sdk.sdkmanager.DJISDKManager.access$700(Unknown Source:0)
        at dji.sdk.sdkmanager.DJISDKManager$6$1.onDownloadSuccess(Unknown Source:6)

**Comment by DJI-William** [comment]
请问问题解决了吗？换一台安卓设备是否能解决你的问题呢？
