### ISSUE TITLE
LiveVideoResolution and LiveVideoBitRateMode class not found exceptions

### ISSUE THREAD

**Issue by niccellular** [dji-sdk/Mobile-SDK-Android#978]
When attempting to set the video resolution and bitrate mode through the LiveStreamManager invoking the LiveVideoResolution or LiveVideoBitRateMode classes they both fail to resolve.

Using sdk version
```
com.dji:dji-uxsdk:4.14
com.dji:dji-sdk-provided:4.15
```

Example code:
```
                    private LiveStreamManager l;
                    l = DJISDKManager.getInstance().getLiveStreamManager();
                    if (!l.isStreaming()) {
                        l.registerListener((x) -> {
                            Log.d(TAG, "LiveStream callback:" + x);
                        });
                        l.setAudioMuted(true);
                        l.setVideoSource(LiveStreamManager.LiveStreamVideoSource.Primary);
                        l.setVideoEncodingEnabled(true);
                        l.setLiveVideoResolution(new LiveVideoResolution(480, 360)); // !! Exception Here !!
                        l.setLiveUrl(RTMP_URL);
                        int rc = 0;
                        rc = l.startStream();
                        ....
```                        

```
07-21 09:17:54.414 29336 29336 E AndroidRuntime: FATAL EXCEPTION: main
07-21 09:17:54.414 29336 29336 E AndroidRuntime: Process: org.FreeTak.FreeTAKUAS, PID: 29336
07-21 09:17:54.414 29336 29336 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Ldji/sdk/sdkmanager/LiveVideoResolution;
07-21 09:17:54.414 29336 29336 E AndroidRuntime: 	at org.FreeTak.FreeTAKUAS.CompleteWidgetActivity.<clinit>(CompleteWidgetActivity.java:120)
07-21 09:17:54.414 29336 29336 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
07-21 09:17:54.414 29336 29336 E AndroidRuntime: 	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
07-21 09:17:54.414 29336 29336 E AndroidRuntime: 	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:43)
07-21 09:17:54.414 29336 29336 E AndroidRuntime: 	at android.app.Instrumentation.newActivity(Instrumentation.java:1251)
07-21 09:17:54.414 29336 29336 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3535)
07-21 09:17:54.414 29336 29336 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
07-21 09:17:54.414 29336 29336 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
07-21 09:17:54.414 29336 29336 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
07-21 09:17:54.414 29336 29336 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
07-21 09:17:54.414 29336 29336 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
07-21 09:17:54.414 29336 29336 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
07-21 09:17:54.414 29336 29336 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:237)
07-21 09:17:54.414 29336 29336 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8167)
07-21 09:17:54.414 29336 29336 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-21 09:17:54.414 29336 29336 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
07-21 09:17:54.414 29336 29336 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
07-21 09:17:54.414 29336 29336 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: dji.sdk.sdkmanager.LiveVideoResolution
07-21 09:17:54.414 29336 29336 E AndroidRuntime: 	... 17 more

```

**Comment by DJI-William** [comment]
This is because you havn't exclude the MSDK 4.14 version in UXSDK 4.14 version. Please add exclude moudle "dji-sdk" in UXSDK 4.14, then this will fix. You can refer to the UXSDK Sample.

**Comment by niccellular** [comment]
> This is because you havn't exclude the MSDK 4.14 version in UXSDK 4.14 version. Please add exclude moudle "dji-sdk" in UXSDK 4.14, then this will fix. You can refer to the UXSDK Sample.

Thank you for taking the time to answer my question. Your solution is correct and it has fixed my issue.
