### ISSUE TITLE
App crashes for M200 + SDK version 4.14.1: FATAL EXCEPTION: RxComputationThreadPool-3

### ISSUE THREAD

**Issue by mayurpatil307** [dji-sdk/Mobile-SDK-Android#979]
**DJI SDK Version: 4.14.1**
App crashes with following crash logs when connected to M200.

--------- beginning of crash
07-21 13:46:01.690  7878  8098 E AndroidRuntime: FATAL EXCEPTION: RxComputationThreadPool-3
07-21 13:46:01.690  7878  8098 E AndroidRuntime: Process: com.flytbase.flytos, PID: 7878
07-21 13:46:01.690  7878  8098 E AndroidRuntime: java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
07-21 13:46:01.690  7878  8098 E AndroidRuntime: 	at dji.thirdparty.rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
07-21 13:46:01.690  7878  8098 E AndroidRuntime: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
07-21 13:46:01.690  7878  8098 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
07-21 13:46:01.690  7878  8098 E AndroidRuntime: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
07-21 13:46:01.690  7878  8098 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-21 13:46:01.690  7878  8098 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-21 13:46:01.690  7878  8098 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
07-21 13:46:01.690  7878  8098 E AndroidRuntime: Caused by: dji.thirdparty.rx.exceptions.OnErrorNotImplementedException: java.lang.NoSuchFieldException: FIRST_STREAM
07-21 13:46:01.690  7878  8098 E AndroidRuntime: 	at dji.thirdparty.rx.Observable$27.onError(Observable.java:8566)
07-21 13:46:01.690  7878  8098 E AndroidRuntime: 	at dji.thirdparty.rx.observers.SafeSubscriber._onError(SafeSubscriber.java:157)
07-21 13:46:01.690  7878  8098 E AndroidRuntime: 	at dji.thirdparty.rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
07-21 13:46:01.690  7878  8098 E AndroidRuntime: 	at dji.thirdparty.rx.exceptions.Exceptions.throwOrReport(Exceptions.java:201)
07-21 13:46:01.690  7878  8098 E AndroidRuntime: 	at dji.thirdparty.rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:144)
07-21 13:46:01.690  7878  8098 E AndroidRuntime: 	at dji.thirdparty.rx.internal.util.ScalarSynchronousObservable$ScalarAsyncProducer.call(ScalarSynchronousObservable.java:192)
07-21 13:46:01.690  7878  8098 E AndroidRuntime: 	at dji.thirdparty.rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
07-21 13:46:01.690  7878  8098 E AndroidRuntime: 	... 6 more
07-21 13:46:01.690  7878  8098 E AndroidRuntime: Caused by: java.lang.AssertionError: java.lang.NoSuchFieldException: FIRST_STREAM
07-21 13:46:01.690  7878  8098 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:792)
07-21 13:46:01.690  7878  8098 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapters$30.create(TypeAdapters.java:818)
07-21 13:46:01.690  7878  8098 E AndroidRuntime: 	at com.google.gson.Gson.getAdapter(Gson.java:458)
07-21 13:46:01.690  7878  8098 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
07-21 13:46:01.690  7878  8098 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
07-21 13:46:01.690  7878  8098 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
07-21 13:46:01.690  7878  8098 E AndroidRuntime: 	at com.google.gson.Gson.getAdapter(Gson.java:458)
07-21 13:46:01.690  7878  8098 E AndroidRuntime: 	at com.google.gson.Gson.toJson(Gson.java:696)
07-21 13:46:01.690  7878  8098 E AndroidRuntime: 	at com.google.gson.Gson.toJson(Gson.java:683)
07-21 13:46:01.690  7878  8098 E AndroidRuntime: 	at com.google.gson.Gson.toJson(Gson.java:638)
07-21 13:46:01.690  7878  8098 E AndroidRuntime: 	at com.google.gson.Gson.toJson(Gson.java:618)
07-21 13:46:01.690  7878  8098 E AndroidRuntime: 	at com.dji.frame.util.V_JsonUtil.toJson(Unknown Source:4)
07-21 13:46:01.690  7878  8098 E AndroidRuntime: 	at dji.internal.analytics.listener.DJIAnalyticsCacheInteractionListener.getValueJson(Unknown Source:0)
07-21 13:46:01.690  7878  8098 E AndroidRuntime: 	at dji.internal.analytics.listener.DJIAnalyticsCacheInteractionListener.metaDataWithKeyPath(Unknown Source:72)
07-21 13:46:01.690  7878  8098 E AndroidRuntime: 	at dji.internal.analytics.listener.DJIAnalyticsCacheInteractionListener.onEvent(Unknown Source:36)
07-21 13:46:01.690  7878  8098 E AndroidRuntime: 	at dji.sdksharedlib.DJISDKCache.fdd(Unknown Source:27)
07-21 13:46:01.690  7878  8098 E AndroidRuntime: 	at dji.sdksharedlib.DJISDKCache.access$lambda$0(Unknown Source:0)
07-21 13:46:01.690  7878  8098 E AndroidRuntime: 	at dji.sdksharedlib.DJISDKCache$$Lambda$1.call(Unknown Source:13)
07-21 13:46:01.690  7878  8098 E AndroidRuntime: 	at dji.thirdparty.rx.Observable$27.onNext(Observable.java:8571)
07-21 13:46:01.690  7878  8098 E AndroidRuntime: 	at dji.thirdparty.rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
07-21 13:46:01.690  7878  8098 E AndroidRuntime: 	... 8 more
07-21 13:46:01.690  7878  8098 E AndroidRuntime: Caused by: java.lang.NoSuchFieldException: FIRST_STREAM
07-21 13:46:01.690  7878  8098 E AndroidRuntime: 	at java.lang.Class.getField(Class.java:1604)
07-21 13:46:01.690  7878  8098 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:781)
07-21 13:46:01.690  7878  8098 E AndroidRuntime: 	... 27 more

We are unable to use the app further.
Please help with the resolution to this issue.

Thanks.

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/50650'>Zendesk ticket #50650</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Are you using the UXSDK?
This problem will occur when using the UXSKD, but the UXSKD will not be maintained.
Please consider using the open-source UXSDK instead.
https://github.com/dji-sdk/Mobile-UXSDK-Beta-Android

Thanks,

Luce Luo
DJI Developer Support
<br><p><em><small>°°°</small></em></p>

**Comment by mayurpatil307** [comment]
@dji-dev 
We are using DJI UX SDK 4.14.1

DJI UX SDK 4.15 is in Beta stage and also consumes app space since we have to import each module.
Do we have any other way to resolve this? Would degrading the SDK version/UX SDK versions would help? If yes, then to which versions should app be degraded to??
