### ISSUE TITLE
更新从4.13更新到4.15启动 报错

### ISSUE THREAD

**Issue by davidWhynum01** [dji-sdk/Mobile-SDK-Android#993]
UnsatisfiedLinkError: No implementation found for void com.dji.megatronking.stringfog.StringUtilsJNI.test()(tried Java_com_dji_megatronking_stringfog_StringUtilsJNI_test and Java_com_dji_megatronking_stringfog_StringUtilsJNI_test__)
        at com.dji.megatronking.stringfog.StringUtilsJNI.test(Native Method)
        at com.dji.megatronking.stringfog.fdd.dgh.fdd(Unknown Source:3)
        at com.dji.megatronking.stringfog.fdd.dgh.fdd(Unknown Source:5)
        at dji.thirdparty.afinal.core.AsyncTask.<clinit>(Unknown Source:2)
        at dji.thirdparty.afinal.core.AsyncTask.execute(Unknown Source:0)

另一款软件4.13可以。 ndk {
            abiFilters "armeabi-v7a" //,"armeabi"
        } 真机 Android 10 华为平板AGS3-W00D，请问是什么原因，可以解决吗？

另外4.13添加  doNotStrip "*/*/libDJISDKLOGJNI.so"  后 报E/NativeRcController: Couldn't load libusbdec.so
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/ProcessLifecycleOwner;
        at dji.sdk.sdkmanager.DJISDKManager.initParams(Unknown Source:182)
        at dji.sdk.sdkmanager.DJISDKManager.initSDKManager(Unknown Source:15)
        at dji.sdk.sdkmanager.DJISDKManager.registerApp(Unknown Source:42)
        at dji.sdk.sdkmanager.DJISDKManager.access$700(Unknown Source:0)
        at dji.sdk.sdkmanager.DJISDKManager$6$1.onDownloadSuccess(Unknown Source:6)
        at dji.internal.ghu.ghu.fdd(Unknown Source:19)
        at dji.sdk.sdkmanager.DJISDKManager$6.run(Unknown Source:33)
        at dji.sdksharedlib.gfd.koy.run(Unknown Source:5)

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/51260'>Zendesk ticket #51260</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by DJI-William** [comment]
请问问题解决了吗？我们现在更新到了4.15.1版本，你下载一下4.15.1的Samplek看看是否运行有问题呢？
